### ISSUE TITLE
ETQ admin, je veux que le champ nombre décimal ne prenne que 3 chiffres après la virgule comme initialement prévu

### ISSUE THREAD

**Issue by Bouchralazaar** [demarches-simplifiees/demarches-simplifiees.fr#10006]
Bug remonté par: https://app.crisp.chat/website/266ba25d-91d1-4774-b01f-a23ba63d662f/inbox/session_420745fe-8b1e-4fb4-8e5e-e89fd7886173/

**Comment by colinux** [comment]
Normalement c'est le cas, mais : 

- ça peut dépendre du type de modèle (pdf, image…), faudrait qu'on remette la main sur la démarche en question
- de son navigateur qui ne supporte pas l'attribut `download` (peu probable) et/ou sa config navigateur qui peut empêcher le téléchargement
