### ISSUE TITLE
ETQ usager, je veux que le modèle à télécharger s'ouvre sur une nouvelle page lorsque je clique dessus

### ISSUE THREAD

**Issue by Bouchralazaar** [demarches-simplifiees/demarches-simplifiees.fr#10007]
éviter la perte de donnée quand l'usager revient en arrière (après avoir cliqué sur la pj)
Ticket créé suite à ce ticket: https://secure.helpscout.net/conversation/2510286764/2055583/

**Comment by colinux** [comment]
Normalement c'est le cas (d'ailleurs prévu par le DSFR), mais : 

- ça peut dépendre du type de modèle (pdf, image…), faudrait qu'on remette la main sur la démarche en question
- de son navigateur qui ne supporte pas l'attribut `download` (peu probable) et/ou sa config navigateur qui peut empêcher le téléchargement

**Comment by mfo** [comment]
outdated
