### ISSUE TITLE
Amélioration du bouton je donne mon avis aka `JDMA`

### ISSUE THREAD

**Issue by mfo** [demarches-simplifiees/demarches-simplifiees.fr#10118]
exemple d'intégration : 
```
<a href="https://jedonnemonavis.numerique.gouv.fr/Demarches/3839?&view-mode=formulaire-avis&nd_source=button&key=6af80846f64fb213abcabaeea7a3ea8c">
            <img src="https://jedonnemonavis.numerique.gouv.fr/static/bouton-bleu.svg" alt="Je donne mon avis" />
          </a>
```

TODO: 
- [ ] revoir l'intégration du bouton JDMA pour correspondre a la capture ci dessous
- [ ] ajouter le bouton JDMA au mail d'accusé de dépot
- [ ] sur la page dossier déposé ; utiliser un nd_source=site
- [ ] sur le mail d'accusé de dépot ; utiliser un nd_source=email

**Comment by mfo** [comment]
maj avec le wording qui va bien :
![Site](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/125964/05d95227-ff7d-49c4-97b4-b96ffd670279)
![Mail](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/125964/af45fb6a-de9f-4747-aa19-ac79ee2aaa4c)

**Comment by marleneklok** [comment]
Version "complète" du mail d'accusé de réception (avec le bas du mail / signature) :
![Mail accuse de reception DS - bouton JDMA](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/162436910/7b9e650b-a989-4bb0-be70-bca649312a78)

**Comment by Benoit-MINT** [comment]
Sur le point 2 "ajouter le bouton au JDMA au mail d'accusé de réception", je m'interroge sur l'articulation avec la PR https://github.com/demarches-simplifiees/demarches-simplifiees.fr/pull/8577

Il est déjà implémenté la possibilité pour l'usager de donner son avis à partir du mail via le service "services publics +". En regardant de plus près, je comprends que la DITP a lancé à l'époque le programme Services Publics + pour améliorer la relation entre administrations et usagers, en proposant en particulier une fonctionnalité pour donner son avis que l'on appelle nous "services publics +", et qui ressemble à ça : https://www.plus.transformation.gouv.fr/experience/step_1#breadcrumb

Je comprends ensuite, que dans le cadre de ce programme Services Publics +, la DINUM a lancé l'outil "Je donne mon avis", qui poursuit la même idée de manière peut être plus quantitative dans l'approche, voir ex : https://observatoire.numerique.gouv.fr/Aide/Donner%20son%20avis

Maintenant que le cadre est posé ... je ne suis pas à l'aise à l'idée d'intégrer ces 2 jouets dans le mail compte tenu de leurs similitudes, et pense donc qu'il convient de choisir l'un des deux.

**Comment by Benoit-MINT** [comment]
Vu avec @emsnytech et @marleneklok , la logique à avoir est la suivante :
- JDMA vise à évaluer uniquement la procédure en tant que telle (clarté, info, etc...);
- Services Publics + vise à évaluer la qualité de l'ensemble de la chaîne (procédure + traitement & relation avec l'administration).

Donc on se cantonnerait bien à uniquement proposer JDMA aux seuls dépôts de dossier.

**Comment by Benoit-MINT** [comment]
c'est mergé
