### ISSUE TITLE
Anciennes démarches n'ayant pas les PJs multiple activité, on peut ajouter une PJ en cliquant sur le label d'un champs pj

### ISSUE THREAD

**Issue by mfo** [demarches-simplifiees/demarches-simplifiees.fr#10186]
<img width="1297" alt="Capture d’écran 2024-03-25 à 11 32 29 AM" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/125964/5803a142-1f41-4a31-a0b5-c1132f2498d6">

**Comment by Benoit-MINT** [comment]
done
