### ISSUE TITLE
Choix multiples - ajouter une croix sur les boutons du DSFR pour supprimer la sélection

### ISSUE THREAD

**Issue by lisa-durand** [demarches-simplifiees/demarches-simplifiees.fr#10187]
![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/0e80b469-808a-4609-a623-f02271ffcb55)

**Comment by mfo** [comment]
a voir le git log mais dans mes souvenir c'etait un hack qu'on avait mis en place ac kara car il y avait un prob de DSFR

**Comment by mfo** [comment]
attention, on a tchak qui refactor les combobox, possible que se soit 'outdated' comme besoin, cf: https://github.com/demarches-simplifiees/demarches-simplifiees.fr/pull/10404

**Comment by mfo** [comment]
fait par @tchak !
