### ISSUE TITLE
Améliorer le démarrage d'un nouveau dossier sur le tableau de bord d'un usager

### ISSUE THREAD

**Issue by mfo** [demarches-simplifiees/demarches-simplifiees.fr#10193]
- [ ] deplacer le bouton commencer un nouveau dossier pour l'inliner dans un sorte de toolbar par element d'un dossier

<img width="1302" alt="Capture d’écran 2024-03-25 à 2 58 42 PM" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/125964/2d439079-42a2-4b83-8f5f-145e13923271">

**Comment by mfo** [comment]
on balaie les good first issue avec @Benoit-MINT – j'ai l'impression que tu l'as commencé mais pas de news, cette issue est t'elle tjr d'actualité

**Comment by lisa-durand** [comment]
Cool ! Alors au final je ne l'avais pas démarré, car ça donné lieu à une réflexion plus globale sur l'interface, notamment côté admin. Mais je pense que c'est une bonne idée de le prendre, il y a encore eu des remontées du support il y a qq jours sur le sujet ! https://app.crisp.chat/website/266ba25d-91d1-4774-b01f-a23ba63d662f/inbox/session_9fa1eefe-1931-491e-bba6-6f7648f72543/

**Comment by Benoit-MINT** [comment]
quand je relis les retours utilisateurs sur ce point, j'ai la sensation que la volonté de débuter un nouveau dossier se trouve dans une phase ultérieure au traitement d'un premier dossier. Je propose donc dans un 1er temps de remonter d'un niveau ce bouton uniquement dans l'onglet "traités".
Potentiellement dans un second temps il pourrait être plus "propre" de prévoir un nouvel onglet (ou un bouton) "nouveau dossier", qui listerait les procédures sur lesquelles l'usager a a minima entamé un dossier.

**Comment by Benoit-MINT** [comment]
Sur mon "second temps", en fait un peu dans l'idée lorsqu'un admin début une nouvelle procédure : 
![Capture d’écran 2024-07-19 à 10 37 30](https://github.com/user-attachments/assets/4581b9ca-25eb-4a19-bcd7-181b6c10c24b)

**Comment by Benoit-MINT** [comment]
mergé
