### ISSUE TITLE
Améliorer la barre de recherche d'un dossier sur le tableau de bord d'un usager

### ISSUE THREAD

**Issue by mfo** [demarches-simplifiees/demarches-simplifiees.fr#10191]
- [x] ajouter au placeholder de  rechercher par numéro/mot clés la notion nom/prenom
- [x] ajouter les labels de chaque inputs de recherche
- [ ] voir si il est facile d'ajouter le separateur (possiblement optionel si c'est relou)

<img width="1298" alt="Capture d’écran 2024-03-25 à 2 28 43 PM" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/125964/bec7b02b-998b-4757-bb18-56fd661fa375">

**Comment by mfo** [comment]
attente d'une passe d'accessibilité pour voir si on peut ré-initialiser facilement/mieux et ou soumettre le formulaire d'une autre maniere plutot qu'en auto submit ? cc

**Comment by inseo** [comment]
Du point de vue access, un bouton de soumission par formulaire serait idéal.
Mais si ça pose vraiment problème, on peut se contenter d'un texte masqué qui explicite le fonctionnement du champ de sélection.

**Comment by mfo** [comment]
je ferme aussi cette issue car j'ai l'impression qu'on a apporté la meilleure réponse possible en l'etat
