### ISSUE TITLE
ETQ Admin je veux etre alerté que ma modification de formulaire n'est pas publiée

### ISSUE THREAD

**Issue by lisa-durand** [demarches-simplifiees/demarches-simplifiees.fr#10208]
![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/b5ddf00b-bc35-44af-bd4e-7f1715f8c13c)
![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/d29e70bf-c684-41dc-8083-38c1d82761a3)
![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/d19867c5-0c90-4442-b887-98fbe37c23e3)
![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/800ffc78-9b8a-4057-8dd0-28627d45fd91)

**Comment by mfo** [comment]
@lisa-durand j'ai l'impression qu'on va pouvoir mettre a jour ce tiquet suite a vos echanges ac @colinux / @marleneklok . 
Est-ce la 'spec' finale ?
[2024-05-23_Espace-ADMIN - Publier les modifications.pdf](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/files/15417634/2024-05-23_Espace-ADMIN.-.Publier.les.modifications.pdf)

**Comment by marleneklok** [comment]
**Récap des dernières recos :**

Lorsque l'utilisateur a modifié les champs de son formulaire actuellement "publié", afficher un bandeau d'alerte sticky en haut d'écran pour lui permettre de publier les modifications :

![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/162436910/70fda885-1b78-4c6a-8f5d-fb4e156e6359)

Si l'utilisateur ferme / quitte l'écran de configuration des champs sans avoir publié ses modifications, afficher un message du navigateur lui rappelant que les modifications qu'il a apportées ne seront appliquées qu'à la prochaine publication :



![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/162436910/e45bf020-a890-42c2-832c-0d3f4ca12e80)

**Comment by kara22** [comment]
@lisa-durand @mfo @colinux  est-ce qu'on attend encore des modifs/retours ou je peux prendre ce ticket ?

**Comment by colinux** [comment]
@kara22 je pense qu'on peut y aller. Sur l'attestation v2 j'ai fait ce bandeau rouge, avec l'idée qu'il puisse être réutilisé pour ce cas là. Il suffit de reprendre le même markup que `app/views/administrateurs/attestation_template_v2s/_sticky_header.html.haml` (et ptet en profiter pour en faire un component )

Par contre sur la popup de confirmation quand on quitte la page on veut vraiment ça ? J'ai l'impression que ça va être ultra intrusif vu le nombre d'allers/retours qu'il ya sur cette page. (désolé si ça a déjà été challengé sur le sujet)

**Comment by lisa-durand** [comment]
Pour la popup de confirmation, je suis pas sure que ce soit si intrusif, ça peut-être utile si on veut fermer un onglet alors que les modifs ne sont pas publiées. Moi j'aurais tendance à l'implémenter et si on a des retours, le retirer. Vous en pensez quoi ?

**Comment by colinux** [comment]
OK alors on n'écouterait que l'event `beforeunload` pour se déclencher à la fermeture de la page, et pas en suivant volontairement un lien pour changer de page.
Personnellement j'aurais plutôt tendance à ne pas l'implémenter tout de suite, commencer par ajouter le bandeau rouge qui est déjà bien voyant, et aviser plus tard voir si c'est suffisant ou pas en fonction des retours. D'autant qu'à ma connaissance on n'a pas souvent de feedback comme quoi c'est mal compris par les admins, mais je me trompe peut-être (et c'est pas moi l'UX ;))

Je dis ça aussi car de l'expérience de l'attestation, il ya plusieurs sous-cas à gérer: première révision ? démarche en test ? … le message diffère, et parfois il n'y a pas de bandeau. On va devoir avoir le même genre de logique pour écouter et supprimer les événements, c'est pas anodin

**Comment by lisa-durand** [comment]
Ok ça me parait aussi bien de démarrer par une premiere étape et voir. Marlène avait remonté ce pb lorsque tu édites ton formulaire dans un autre onglet il me semble, tu fermes l'onglet et tu ne tombes pas sur la page qui te dit que tes modifs ne sont pas publiées. Mais du coup avec l'alerte, ça résout déjà le probleme à priori, partons la-dessus si c'est plus simple.

**Comment by kara22** [comment]
@colinux @lisa-durand le bandeau sticky il est juste sur la page de modification des champs, ou sur toute l'interface admin du momemnt ou il a des modifs non publiées ?

**Comment by lisa-durand** [comment]
uniquement sur la page de modif, car apres sur la page de gestion de la demarche, tu as un composant callout avec le detail.
