### ISSUE TITLE
Améliorer emails et relances pour prévenir qu'un dossier en construction va expirer / être supprimé

### ISSUE THREAD

**Issue by colinux** [demarches-simplifiees/demarches-simplifiees.fr#10219]
Contexte: des usagers dont les dossiers non traités près de la date d'expiration ne comprennent pas assez bien l'enjeu de la suppression et que toutes les preuves vont disparaître

## Usager
- plutôt qu'un seul mail à J-14, éventuellement envoyer un mail à J-30 et un autre à J-7
- préciser dans l'email que les usagers peuvent prolonger la durée de conservation, télécharger le PDF, l'attestation de dépôt, contacter l'administration par la messagerie etc 
- rajouter dans l'email le lien vers la page qui permet de prolonger la durée de conservation
- peut-être préciser sur la page que la prolongation peut-être "infinie" ( mois après mois)

## Instruction
- être plus persuasif pour qu'ils aillent instruire le dossier
- système de relance ?

cc @Bouchralazaar

**Comment by LeSim** [comment]
email actuel
![Screenshot 2024-04-19 at 17-28-20 LetterOpenerWeb](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/907405/b48dffcc-8f0d-4a80-9307-440e078bdaba)

**Comment by lisa-durand** [comment]
Des retours pour avoir le contexte
https://secure.helpscout.net/conversation/2603153256/2074187/ 
https://secure.helpscout.net/conversation/2601723364/2074109/

https://secure.helpscout.net/conversation/2597309253/2073366/


https://secure.helpscout.net/conversation/2603416578/2074199/

**Comment by CamilyaDellali** [comment]
+ j'ai l'impression que certains usagers ne reçoivent pas de mail  à J-14 pour les informer de la suppression définitive des dossiers ( voir l'historique des retours support ci-dessus)
