### ISSUE TITLE
ETQ Administrateur, la liste d'édition permettant de déplacer les champs présente des défauts d'accessibilité

### ISSUE THREAD

**Issue by inseo** [demarches-simplifiees/demarches-simplifiees.fr#10254]
- [x] La liste est munie d'un attribut aria inexistant : `aria-discribedby` (et inutile car il fait référence au champ lui-même).
- [x] Les intitulés "Déplacer le champ après" et "Selectionner une option" ne sont pas accentués.
- [ ] Deux options sont indiquées comme étant "sélectionnées" alors que la liste n'accepte pas la sélection multiple.

![Capture d’écran 2024-04-02 à 16 03 47](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/2088264/0d73b6f6-29ae-4090-8ae9-ee8e3f8c72c8)
![Capture d’écran 2024-04-02 à 16 05 33](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/2088264/1d9850b2-78fb-4e9b-b5f9-3bf9e18f1c99)

**Comment by inseo** [comment]
Concernant la 3e tâche (deux options en `selected` et `disabled` sur une même liste), je me demande si le soucis ne pourrait pas être réglé en supprimant de la liste l'élément que l'on cherche à déplacer.   

D'un point de vue UX, ne serait-il pas préférable de retirer l'élément à déplacer de la liste des options ?
Ainsi le seul élément sélectionné serait logiquement l'élément précédant celui que l'on souhaite déplacer.

**Comment by mfo** [comment]
> D'un point de vue UX, ne serait-il pas préférable de retirer l'élément à déplacer de la liste des options ?

ça me chagrinnerait de l'enlever, en gros c'est un peu le point de référence non ? [le selected permet de se positionner automatiquement ds la liste]

**Comment by mfo** [comment]
🎉  https://github.com/demarches-simplifiees/demarches-simplifiees.fr/pull/10298
