### ISSUE TITLE
ETQ admin, dans la page "toutes les démarches", je veux que les tags soient harmonisés 

### ISSUE THREAD

**Issue by Bouchralazaar** [demarches-simplifiees/demarches-simplifiees.fr#10333]
Il faut que l'on prenne le temps de cleaner les tags (qu'on va plutôt appeler "thématique")et de fermer la liste des propositions de tags pour rendre les recherches plus simples pour les administrateurs. 

Je propose que les thématiques soient des majuscules. toujours au singulier: 

"AAP", "SUBVENTION", "VTC" 

Exemple avec les agréments: "AGREMENT" 
![Capture d’écran 2024-04-16 à 11 16 48](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/89633115/b714af53-276b-477c-8acb-5ab694fa7a2f)

**Comment by tchak** [comment]
Aujourd'hui, les tags peuvent être ajoutés par n'importe qui, donc on n'a pas de contrôle dessus

**Comment by kara22** [comment]
Tags sur démarches-simplifiées

Actuellement, le système permet aux administrateurs de saisir librement des tags pour chaque démarche. Ces tags sont stockés sous forme de tableau dans la table Procédures, sans normalisation. La recherche et la comparaison des tags sont sensibles à la casse.

Avantages potentiels de la solution actuelle :

Les utilisateurs peuvent créer des tags sans contrainte
L’équipe DS n’a pas besoin de gérer une liste de tags autorisés.
Inconvénients de la solution actuelle :

Un même concept peut être représenté par plusieurs variantes du même tag (ex: “Administration”, “administration”, “Administrations”).
Générer des statistiques précises sur l’utilisation des tags est complexe
Les administrateurs n’utilisent pas ou très peu la recherche par tags et peut être incomplète si l’admin ne connaît pas la forme exacte du tag.
Proposition d’amélioration :

Je recommande de passer à un système de tags prédéfinis et évolutifs. Voici comment procéder :

Créer une nouvelle table procedure_tags dans la base de données avec les colonnes :

id (clé primaire)
name (nom du tag, unique et insensible à la casse)
created_at
updated_at
Lier la table procedure_tags à Procedur epour référencer procedure_tag_id.

Dans le manager, ajouter une interface d’administration pour gérer la liste des tags autorisés.

Modifier l’interface administrateur pour proposer une sélection de tags prédéfinis lors de la création/modification d’une démarche.

Créer un script de migration pour convertir les tags existants vers le nouveau système :

Normaliser les tags existants (minuscules, suppression des espaces superflus)
Regrouper les tags similaires
Insérer les tags uniques dans la nouvelle table tags
Mettre à jour les fonctionnalités de recherche et de statistiques pour utiliser le nouveau système de tags.

Pour la sécurité :

Mettre en place des limites sur le nombre de tags par démarche pour éviter les abus.
Implémenter une journalisation des modifications de tags pour l’audit : est-ce vraiment nécessaire ?
Proposition pour le hackathon (Benoit):

Pour le prochain hackathon, je suggère de faire travailler les participants sur :

L’élaboration d’une liste initiale de tags prédéfinis :

Analyser les tags existants
Identifier les catégories principales de démarches
La création d’un processus pour faire évoluer la liste de tags :

Définir les critères pour ajouter/modifier/supprimer un tag
Concevoir un workflow de validation pour les nouveaux tags proposés

**Comment by kara22** [comment]
Plan de mise en œuvre : suite à la discussion sur ce pad (ci-dessus) 

1. Création de la nouvelle structure de données :

- Une nouvelle table procedure_tags pour stocker les tags prédéfinis.
- Une table de liaison procedure_procedure_tags pour établir la relation many-to-many entre Procedure et procedure_tags.

2. Développement de l'interface d'administration des tags :

- Ajout dans le manager pour la gestion des tags prédéfinis.

Créer un CRUD pour gérer les tags prédéfinis
Implémenter la logique de validation (unicité, casse insensible)


3. Modification de l'interface administrateur pour la sélection des tags :

- Remplacer le champ de saisie libre par un sélecteur multiple
- Implémenter une recherche instantanée dans la liste des tags


4. Implémentation des mesures de sécurité :

- Limiter le nombre de tags par démarche (5 tags ?)
- Mettre en place la journalisation des modifications (si nécessaire @tchak ?)

5. Script de migration des données : si nécessaire 

6. Mise à jour des fonctionnalités de recherche dans la page toutes les démarches
