### ISSUE TITLE
ETQ Usager, je devrais avoir un minimum de tolérance sur la typographie de ma commune

### ISSUE THREAD

**Issue by LeSim** [demarches-simplifiees/demarches-simplifiees.fr#10400]
Sur un champ commune

> "L'Haÿ-les-Roses" non trouvé
> "L’Haÿ-les-Roses (94240)" (notez le caractère apostrophe différent)

pareil pour `maisons alfort` au lieu de `maisons-alfort`

**Comment by tchak** [comment]
c'est corrigé
