### ISSUE TITLE
ETQ usager, je veux pouvoir télécharger mon dossier sans avoir à passer par le bouton "imprimer"

### ISSUE THREAD

**Issue by Bouchralazaar** [demarches-simplifiees/demarches-simplifiees.fr#10434]
Vu avec Marlène, il faut remplacer le bouton "imprimer" par "télécharger le dossier". 
Puis, dès que l'usager accède au téléchargement, libre à lui de l'imprimer ou non. 
![image(2)](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/89633115/d89d247b-7ed7-4d36-828a-eb7fc945ee34)
![image(1)](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/89633115/46603735-e7e4-4a63-b5da-0ddb0834b608)

@marleneklok

**Comment by marleneklok** [comment]
Reprendre evol du ticket : https://github.com/demarches-simplifiees/demarches-simplifiees.fr/issues/10498
