### ISSUE TITLE
ETQ Usager, je dois confirmer mon nouveau mail lors d'un changement d'adresse

### ISSUE THREAD

**Issue by LeSim** [demarches-simplifiees/demarches-simplifiees.fr#10453]

**Comment by lisa-durand** [comment]
@LeSim j'ai l'impression que pour cette story c'est bon non ? Car pour pouvoir changer de mail, on doit passer par une confirmation par mail pour que ce soit effectif et lorsqu'on clique le `email_verified_at` est bien mis à jour.

<img width="994" alt="Capture d’écran 2024-07-04 à 16 24 50" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/5e481bbc-64f4-4f9f-a794-abf806d38241">

**Comment by LeSim** [comment]
bon bah, c'est bon alors. tip top.
