### ISSUE TITLE
ETQ dev qui utilise l'API, je ne peux pas distinguer une non-réponse d'un "non" dans un champ Checkbox

### ISSUE THREAD

**Issue by DavidBruant** [demarches-simplifiees/demarches-simplifiees.fr#10677]
Par exemple, dans [ce dossier](https://www.demarches-simplifiees.fr/procedures/88444/dossiers/19312462), je n'ai pas répondu à la question "Le projet est-il soumis au régime de l'Autorisation Environnementale (article L. 181-1 du Code de l'environnement) ? : " (question non-obligatoire) et pourtant, quand je demande le dossier à l'API, celle-ci me répond (extrait) :

```json
{
  "label": "Le projet est-il soumis au régime de l'Autorisation Environnementale (article L. 181-1 du Code de l'environnement) ?",
  "stringValue": "false",
  "prefilled": false,
  "value": false,
  "updatedAt": "2024-08-02T14:46:01+02:00"
},
```

`"value": false` qui ne peut pas être distingué du fait de répondre "Non"
alors que j'aimerais bien pouvoir distinguer (dans notre cas, c'est une situation normale de ne pas avoir la réponse à cette question au moment du dépôt et ça peut être modifié en phase construction après discussion avec l'instructrice)

**Comment by tchak** [comment]
On vient de le corriger pour le champ Oui/Non. Pour le champ Checkbox ça n'a pas de sens de différencier vu qu'une checkbox n'a que deux états. Sur l'API il y'a maintenant deux types distincts pour les deux colonnes

**Comment by tchak** [comment]
Je continue de penser que c'est une mauvaise idée de traiter "non renseigné" comme un cas métier séparé pour la raison qu'il n'est pas possible de revenir dans cette état de manière explicite. Une fois un choix est fait (même par erreur) c'est oui ou non. Si vous avez vraiment besoin de trois états du point de vue métier, je conseille d'utiliser un select avec trois options – ils seront rendus comme un contrôle radio.

**Comment by DavidBruant** [comment]
Merci pour ta réponse et pour la correction

> Si vous avez vraiment besoin de trois états du point de vue métier, je conseille d'utiliser un select avec trois options – ils seront rendus comme un contrôle radio.

Oui, c'est exactement ce qu'il s'est passé au final 

Nous avons réalisé que nous avons besoin de 3 états d'un point de vue métier oui/non/"ne sait pas encore" et nous avons transformé le "oui/non" et "choix simple"
