### ISSUE TITLE
Liste des démarches instructeurs: passer au nouveau look and feel tableau

### ISSUE THREAD

**Issue by LeSim** [demarches-simplifiees/demarches-simplifiees.fr#10781]
- retirer le logo
- mettre un trait entre les démarches
- materialiser les compteurs au format bouton

**Comment by marleneklok** [comment]
**Actuellement :**
![Image](https://github.com/user-attachments/assets/38bc352d-9e0d-462b-b4de-93ec8838c24b)

Version cible :
![Image](https://github.com/user-attachments/assets/2486d392-c6a6-4365-91c2-423ae67bc56c)

**Comment by dzc34** [comment]
Logo plutôt pratique pour identifier les démarches, si c'est un logo dédié

**Comment by kara22** [comment]
@marleneklok dans "Menu" il y a quoi stp ?

**Comment by marleneklok** [comment]
@kara22 
Tu retrouves en accès direct les rubriques de la démarche :
https://github.com/demarches-simplifiees/demarches-simplifiees.fr/issues/10790
https://github.com/demarches-simplifiees/demarches-simplifiees.fr/issues/10932

**Comment by kara22** [comment]
@marleneklok merci, je pense prendre en premier le #10932 est-ce que c'est good ? Ou c'est mieux que je prennen un autre ? Je viens de finir une PR donc je peux me mettre dessus dès maintenant

**Comment by lisa-durand** [comment]
@kara22 j'arrive un peu tard, mais du coup dans ce ticket il n'est pas question d'ajouter le bouton menu (qui est le ticket https://github.com/demarches-simplifiees/demarches-simplifiees.fr/issues/10790) mais juste faire ce qui est dans la description du ticket.

**Comment by kara22** [comment]
@marleneklok du coup les expirants on les vire du  tableau si j'ai bien compris ?

**Comment by marleneklok** [comment]
@kara22 En version cible oui, mais il me semble qu'on ne les vire pas tout de suite.
@lisa-durand Tu confirmes ?

**Comment by lisa-durand** [comment]
En effet - on pourra les retirer que lorsqu'on aura le nouveau systeme de notifs qui les fera remonter. Donc pas d'actualité pour l'instant.
