### ISSUE TITLE
ETQ instructeur, je navigue facilement entre les différentes rubriques d'une démarche

### ISSUE THREAD

**Issue by marleneklok** [demarches-simplifiees/demarches-simplifiees.fr#10932]

**Comment by marleneklok** [comment]
# Actuellement
Le système de navigation actuel au sein d'une démarche manque de stabilité : les rubriques ne sont pas présentes sur toutes les pages de l’espace. L’instructeur est donc obligé d’utiliser le fil d’Ariane pour revenir sur l’écran principal de la démarche afin de retrouver le système de navigation initial.
De plus, ces rubriques sont toutes mises au même niveau alors qu’elles n’ont pas nécessairement le même niveau d’importance.
![Image](https://github.com/user-attachments/assets/d41fc3b7-bea2-400b-ae78-0cd76068d268)
_Exemple 1 : je consulte la rubrique « Instructeurs » :_
![Image](https://github.com/user-attachments/assets/bca29ae1-94e1-48f3-adf9-ff970b357211)
_Exemple 2 : je consulte la rubrique « Voir les exports » :_
![Image](https://github.com/user-attachments/assets/8e2b1280-f7b8-4fa7-9933-b0231c3169ef)

# Optimisation
• Revue de l’arborescence de l’espace instructeurs, avec une catégorisation des rubriques et l’ajout de nouvelles rubriques / pages :
![Image](https://github.com/user-attachments/assets/3d346ef2-2317-4992-8a91-b5a8ddc96249)
• Affichage permanent de la barre de navigation sur toutes les pages de la démarche.
• Homogénéisation des libellés de rubriques / titres de page.

# Description
Le menu de la rubrique en cours de consultation est **marqué comme actif** (+ mise à jour du fil d’Ariane).

_Exemple : je consulte la rubrique « Liste des exports » du menu « Téléchargements »... le menu « Téléchargements » est donc marqué comme actif / en cours de consultation :_
![Image](https://github.com/user-attachments/assets/8b0509fb-a92b-45ec-9a0a-6e69f54a6559)

## Page « Suivi des dossiers » (page par défaut lorsqu’on accède à une démarche)
Page actuelle : https://www.demarches-simplifiees.fr/procedures/00000
(REFONTE DE LA PAGE : Voir ticket [à venir])
![Image](https://github.com/user-attachments/assets/b22d3ab6-3592-4167-bf40-01651e961662)

## Menu « Gestion de la démarche »
![Image](https://github.com/user-attachments/assets/2904312d-709b-47f6-9003-a8ec60ea9a21)

**Rubrique « Informations sur la démarche » (NOUVELLE PAGE)**
(CRÉATION DE LA PAGE : Voir ticket [à venir])
![Image](https://github.com/user-attachments/assets/43a38660-2c70-479f-8b0e-c6f823087c52)

**Rubrique « Administrateurs de la démarche »**
Page actuelle : https://www.demarches-simplifiees.fr/procedures/00000/administrateurs 
(REFONTE DE LA PAGE : Voir ticket [à venir])
![Image](https://github.com/user-attachments/assets/98b1727f-729f-403f-9254-2d0c76dea793)

**Rubrique « Gestion des instructeurs »**
Page actuelle : https://www.demarches-simplifiees.fr/procedures/00000/groupes  
(REFONTE DE LA PAGE : Voir ticket [à venir])
![Image](https://github.com/user-attachments/assets/fa3866a2-d9c0-493d-b3b0-5b931fdd7dfc)

**Rubrique « Gestion des notifications »**
Page actuelle : https://www.demarches-simplifiees.fr/procedures/00000/email_notifications   
(REFONTE DE LA PAGE : Voir ticket [à venir])
![Image](https://github.com/user-attachments/assets/aca434b6-5927-435e-877b-5c5a9178a026)

**Rubrique « Statistiques de la démarche »**
Page actuelle : https://www.demarches-simplifiees.fr/procedures/00000/stats    
![Image](https://github.com/user-attachments/assets/636ba70a-59c1-4954-83d4-32c5a40280cc)

**Rubrique « Historique des dossiers supprimés »**
Page actuelle : https://www.demarches-simplifiees.fr/procedures/00000/deleted_dossiers
(REFONTE DE LA PAGE : Voir ticket [à venir])
![Image](https://github.com/user-attachments/assets/f65bf275-30dd-4704-949d-2d61390b637d)

## Menu « Accompagnement des usagers »
![Image](https://github.com/user-attachments/assets/8393cd4a-009e-459e-a3ee-916d3fde61aa)

**Rubrique « Contacter les usagers avec un dossier "brouillon" »**
Page actuelle : https://www.demarches-simplifiees.fr/procedures/00000/email_usagers 
(REFONTE DE LA PAGE : Voir ticket [à venir])
![Image](https://github.com/user-attachments/assets/37250295-353d-4594-90ad-a9a4ad564efe)

**Rubrique « Rendez-vous avec les usagers » (NOUVELLE PAGE)**
(CRÉATION DE LA PAGE : Voir ticket [à venir])
![Image](https://github.com/user-attachments/assets/0071ea5f-56d7-419a-bd72-61f15060be49)

## Menu « Téléchargements »
![Image](https://github.com/user-attachments/assets/ef6de8e2-1904-4c5c-85f7-8b7c01381f53)

**Rubrique « Liste des exports »**
Page actuelle : https://www.demarches-simplifiees.fr/procedures/00000/exports 
(REFONTE DE LA PAGE : Voir ticket [à venir])
![Image](https://github.com/user-attachments/assets/13436651-e517-4afa-b807-efccc62af195)

**Rubrique « Téléchargement mensuel »**
Page actuelle : (page « Archives ») https://www.demarches-simplifiees.fr/procedures/00000/archives 
(REFONTE DE LA PAGE : Voir ticket [à venir])
![Image](https://github.com/user-attachments/assets/f629cf64-debb-4c7e-b438-5ad9ebb91740)

**Rubrique « Modèles d’export »**
Page actuelle : (sur la même page que la liste des exports) https://www.demarches-simplifiees.fr/procedures/00000/exports  
(REFONTE DE LA PAGE : Voir ticket [à venir])
![Image](https://github.com/user-attachments/assets/fe1ef77e-a029-4584-955f-5507b048d454)

**Comment by marleneklok** [comment]
Ticket lié : [ETQ instructeur, sur la liste des démarches, je peux accéder au menu d'une démarche pour accéder directement à une rubrique](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/issues/10790)
#10790

**Comment by kara22** [comment]
@marleneklok la flèche "retour" à coté du titre de la démarche renvoie vers quelle page stp ? Vers la liste de toutes les démarches (instructeur)?

![Image](https://github.com/user-attachments/assets/63eaabec-4290-4553-8673-7fa3781451c3)

**Comment by marleneklok** [comment]
@kara22  Oui tout à fait ! Voir ticket lié [ETQ instructeur, je reviens facilement en arrière depuis la page Démarche et depuis la page Dossier (cf. fil d'ariane et bouton retour) #10784](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/issues/10784)
