### ISSUE TITLE
ETQ Instructeur, je veux pouvoir ajouter des instructeurs en masse en copiant/collant une liste d'adresses emails séparées par des points virgules

### ISSUE THREAD

**Issue by marleneklok** [demarches-simplifiees/demarches-simplifiees.fr#10955]

**Comment by marleneklok** [comment]
# Actuellement - interface ADMINISTRATEUR
Il est possible de copier/coller une liste d'adresses emails séparées par des points-virgules pour ajouter plusieurs instructeurs en même temps :
![Image](https://github.com/user-attachments/assets/d40dd1bf-ddad-49da-aff2-dc04574972df)
N.B. : voir ticket [ETQ admin - Optimisation des écrans de routage](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/issues/10766) pour ajouter au niveau du champ l'aide à la saisie correspondante :
![Image](https://github.com/user-attachments/assets/75d90c7e-a021-4f14-b989-b6e2cc6921dd)

# Actuellement - interface INSTRUCTEUR
• Il est possible de copier/coller une liste d'adresses emails séparées par des points-virgules pour demander un avis à plusieurs experts en même temps :
![Image](https://github.com/user-attachments/assets/d5e92dd2-bbe0-4ae9-9e69-fab837d18545)
N.B. : ajouter également l'aide à la saisie correspondante.

• Il **n'est pas possible** dans la rubrique "Instructeurs" de copier/coller une liste d'adresses emails séparées par des points-virgules pour ajouter plusieurs instructeurs en même temps :
![Image](https://github.com/user-attachments/assets/1adb5376-c2e5-48b0-9ae5-37a137a31b39)

# Optimisation interface INSTRUCTEUR
Rendre possible l'ajout de plusieurs adresses emails séparées par des points-virgules, et ajouter l'aide à la saisie correspondante :
![Image](https://github.com/user-attachments/assets/1de8e015-5071-4116-9616-6af3b1ed5ff5)
Le bouton "Affecter" est inactif tant qu'aucune adresse email n'a été saisie :
![Image](https://github.com/user-attachments/assets/e555591d-0bc6-42b4-aaef-7962e5577eb7)

**Comment by tchak** [comment]
C'est bizarre, moi j'arrive à coller une liste séparée par des ";". Tu pourras me faire la démo de ce que tu fais qui ne marche pas ?
