### ISSUE TITLE
Export : Retirer la mention par défaut "non" lorsqu'un champ de type OUI/NON a été supprimé 

### ISSUE THREAD

**Issue by CamilyaDellali** [demarches-simplifiees/demarches-simplifiees.fr#10961]
Les champs de type OUI/NON, sont par défaut remplis "non" lorsque les dossiers ont été déposés après la suppression
de ces champs. C'est également le cas pour les dossiers déposés avant la suppression de ces champs. 

Les instructeurs ont alors du mal à suivre l'exactitude des infos selon la version du formulaire. 

Proposition des instructeurs : on devrait pouvoir retracer les modifications du formulaire dans l'export ,en laissant vierge le champ qui a été modifié ou en ajoutant la mention "nul" . 

Exemple de démarche : n 80149 "Suivi des prélèvements d'eau pour le département de La Réunion".
(J'ai également testé sur ma démarche n96899)

[erreursRecontreesDonneesDS_80149 (2).xlsx](https://github.com/user-attachments/files/17432069/erreursRecontreesDonneesDS_80149.2.xlsx)

**Comment by tchak** [comment]
c'est fait #10977
