### ISSUE TITLE
ETQ instructeur, je peux inclure les dossiers "archivés" quand je télécharge les dossiers de l'onglet "Au total"

### ISSUE THREAD

**Issue by marleneklok** [demarches-simplifiees/demarches-simplifiees.fr#11103]

**Comment by marleneklok** [comment]
# Actuellement
Suite au retrait du bouton « Télécharger tous les dossiers », il y a des retours d’instructeurs au support concernant le fait que les dossiers « archivés » ne sont plus inclus dans l’export : _« Le téléchargement depuis le suivi des dossiers (capture ci-dessous) ne reprend pas l'intégralité des dossiers, excluant les dossiers archivés. »_
![Image](https://github.com/user-attachments/assets/59549c22-69d4-46ed-bb4e-8f16b5b147b0)

# Optimisation
Dans le menu du bouton « Télécharger x dossiers » **de l’onglet « au total »**, ajouter un toggle (activé par défaut) permettant d’inclure les x dossiers de l’onglet « archivés » dans l’export :
![Image](https://github.com/user-attachments/assets/8715e366-a9cc-4681-98ed-e29593b51625)
N.B. : Corriger la coquille à « Sélectionner » (manque le « c »).

![Image](https://github.com/user-attachments/assets/506c6c3e-9c17-4bc4-8d80-1b396adc1be4)

**Comment by marleneklok** [comment]
# Aménagement
Suite à la clarification des onglets de suivi des dossiers, renommer "archivés" par "à archiver" :
![image](https://github.com/user-attachments/assets/57ef6ec1-15d6-453b-92d6-6d661adf94ca)

**Comment by colinux** [comment]
J'ai fait ce dernier renommage dans https://github.com/demarches-simplifiees/demarches-simplifiees.fr/pull/11196
