### ISSUE TITLE
Améliorer la terminologie du terme "En construction"

### ISSUE THREAD

**Issue by AnthonyBrunelli** [demarches-simplifiees/demarches-simplifiees.fr#1332]
Avez-vous des retours utilisateurs sur la terminologie utilisée dans TPS?

En partant du principe que ce n'est pas paramétrable et que la terminologie doit être commune à tous les dossiers, et même si je m'y suis habitué maintenant, je me pose des questions sur les termes de:
- Accompagnateur
- Brouillon
- En construction
- Refusé/Accepté
- ...

**Comment by AnthonyBrunelli** [comment]
@LeSim Ok, je peux étudier la question et interroger les collègues. Tu veux échanger sur le sujet hors Github (j'ai vu que tu as fermé l'issue)?

**Comment by LeSim** [comment]
Oui, je veux bien échanger hors github vue que, d'expérience, ces pbs de vocabulaire aboutissent à de longs débats passionnés :) .

**Comment by AnthonyBrunelli** [comment]
@LeSim @mmagn Je ne veux pas ouvrir un débat, mais pour mémoire, j'ai (quand même) posé la question lors de l'atelier utilisateurs de vendredi. Retour unanime (@mmagn je te laisse confirmer/infirmer) sur deux termes à changer: "accompagnateur" et "en construction".

Pour "en construction", j'avais évoqué qqchose du style "transmis mais modifiable" qui avait l'air de convenir (mais c'est peut être trop long à  l'affichage).

Pour "accompagnateur", je ne sais pas. A priori vous avez envisagé mais écarté "gestionnaire". Le terme d' "instructeur" était celui qui s'imposait naturellement dans la conversation.

Les autres termes pour lesquels je me posais question ("brouillon", "accepté", "refusé") ne pose visiblement pas problème.

**Comment by gregoirenovel** [comment]
@AnthonyBrunelli merci pour cette relance et ces détails

Pour "en construction", je suis tout a fait d'accord, c'est un point sur lequel on va essayer de proposer quelque chose de plus clair

Pour accompagnateur c'est également en discussion, on va faire une grosse passe sur la terminologie.

Je réouvre donc cette issue pour signifier que c'est un point d'amélioration à traiter

**Comment by LeSim** [comment]
confusion sur le terme en construction pour `#2057`. L'usager ne savait pas s'il restait des actions à effectuer pour transmettre son dossier.

**Comment by AnthonyBrunelli** [comment]
Lors de la rencontre avec les usagers, "Transmis mais modifiable" (en remplacement de "En construction") avait eu un retour positif.
