### ISSUE TITLE
ETQ Admin, je peux ajouter un logo + lien cerfa a une procédure publiée et homologuée

### ISSUE THREAD

**Issue by AnthonyBrunelli** [demarches-simplifiees/demarches-simplifiees.fr#1349]
Dans le cadre de l'homologation Cerfa des démarches en ligne - qui concernera a priori beaucoup les démarches paramétrées dans TPS - les démarches Cerfatisées devront insérer un logo Cerfa intégrant un numéro qui leur sera propre.

Ce logo a vocation à être cliquable pour rediriger sur une page qui confirmera que la démarche en question est bien cerfatisée (+ des infos).

Serait-il possible de prévoir un endroit sur le formulaire pour intégrer ce logo? _Après_ que la démarche a été paramétrée (puisque la cerfatisation intervient en bout de course)?

**Comment by LeSim** [comment]
Nous allons prévoir l'emplacement. Pourriez-vous nous envoyer le logo cerfa à afficher ?

**Comment by AnthonyBrunelli** [comment]
@LeSim Oui, ci-dessous.

/!\ Je vois un problème potentiel: le logo ne peut pas être inséré à la création du formulaire, qui n'est pas encore homologué, mais plus tard (or, actuellement, les modifications ne sont pas possibles une fois le formulaire créé...)

+ chaque logo est unique, puisqu'il a un numéro propre à la procédure qui lui est associé.

![nouveau logo cerfa](https://user-images.githubusercontent.com/35567048/35272969-32347c60-0037-11e8-9dc0-27caaaf2eba0.png)
