### ISSUE TITLE
Si API Entreprise down, afficher directement un bandeau aux usagers avant même qu'ils ne rentrent leur SIRET

### ISSUE THREAD

**Issue by gregoirenovel** [demarches-simplifiees/demarches-simplifiees.fr#1720]

**Comment by tchak** [comment]
Une solution simple est de set un compteur quelque part quand il y a une erreur et de le reset quand un appel est en succès. Si le compteur est > n (à définir) on affiche le bandeau. Ou alors il y a une api de statut qu'on peut taper? Elle est granulaire?
