### ISSUE TITLE
Plusieurs pièces jointes sur un champ

### ISSUE THREAD

**Issue by fredZen** [demarches-simplifiees/demarches-simplifiees.fr#2118]
Les pièces justificatives ont souvent un recto et un verso, voire elles font plusieurs pages. Ce serait pratique pour les usagers de pouvoir téléverser ces pièces sans avoir à les rassembler en un seul fichier avant.

Exemple : HS `#3814`

**Comment by gregoirenovel** [comment]
Est-ce que cette issue est en fait un sous-cas de #1769 ?

**Comment by fredZen** [comment]
Peut-être... pas si sûr. J’aimerais bien qu’on garde les deux issues pour l’instant.

**Comment by emsnytech** [comment]
22 votes au moins sur featureofvote à reprioser

**Comment by tchak** [comment]
en cours
