### ISSUE TITLE
ETQ Instructeur, je souhaite plus de contraste pour parcourir les tableaux

### ISSUE THREAD

**Issue by hugolepetit** [demarches-simplifiees/demarches-simplifiees.fr#2282]
<img width="1200" alt="screen shot 2018-07-23 at 10 05 21" src="https://user-images.githubusercontent.com/2211142/43064753-23329668-8e60-11e8-9c8e-3fb213456779.png">
On a que des lignes blanches, Il pourrait être bon de mettre un gris léger sur les lignes paires ou impaires pour augmenter le confort de lecture

**Comment by gregoirenovel** [comment]
On ne pense pas le faire car :
- ça n'apporte pas grand chose, cf. https://alistapart.com/article/zebrastripingdoesithelp
- pour que ça soit esthétiquement agréable, ça nécessiterait un travail plus important que simplement zébrer les rangées

**Comment by giglemad** [comment]
Je ne souhaite pas augmenter la vitesse de lecture, ou la précision. J'ai les yeux qui piquent et fatiguent devant un tel tableau. C'est mon pain point.
Le zébrage des rangées n'est dans le meilleur des cas qu'une suggestion pour addresser ce problème. Concernant l'article, il n'explore pas par exemple les notions de confort que l'on a à bien identifier un tableau au milieu de la page blanche.

**Comment by tchak** [comment]
Le tableau est en train d'être migré vers les styles DSFR
