### ISSUE TITLE
Expert - je reçois un lien cassé pour m'inscrire sur demarches-simplifiées

### ISSUE THREAD

**Issue by soizicpenicaud** [demarches-simplifiees/demarches-simplifiees.fr#2340]
Accompagnatrice sur une démarche, je fais des tests pour simuler des demandes d'avis aux experts.

J'ai envoyé une demande à un "expert" non inscrit sur la plateforme (une autre de mes adresses mail). Je reçois le mail avec un lien "Inscrivez-vous" (qui pointe vers : "https://www.demarches-simplifiees.fr/avis/11702/sign_up/email/$MONADRESSEMAIL"). 

En cliquant dessus, j'arrive sur la page suivante : "The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved."

**Comment by fredZen** [comment]
Bonjour @soizicpenicaud, merci pour votre retour.

j’arrive à reproduire le comportement, mais le bug est moins grave qu’il n’y parait : il se produit seulement quand je suis déjà connecté avec mon compte principal.

Pour le dire autrement : 

# Scénario cassant
1. me connecter sur demarches-simplifiees.fr avec mon compte principal
2. envoyer une invitation _expert_ à une adresse mail secondaire
3. cliquer sur le lien d’invitation dans le mail
4. **une page d’erreur apparaît**

# Scénario passant
1. me connecter sur demarches-simplifiees.fr avec mon compte principal
2. envoyer une invitation _expert_ à une adresse mail secondaire
3. **me déconnecter de demarches-simplifiees.fr**
4. cliquer sur le lien d’invitation dans le mail
5. **la page de création de compte expert apparaît**

Les vrais expert pourraient théoriquement rencontrer le bug – s’ils ont déjà un compte sous une adresse différente et qu’ils sont connectés au moment de cliquer sur le lien d’invitation – mais en pratique je m’attends à ce que ce soit relativement rare.

Il n’en reste pas moins que c’est un bug à corriger, ne serait-ce que pour éviter d’inquiéter les accompagnatrices et accompagnateurs faisant des tests.

**Comment by fredZen** [comment]
à communiquer `HS #2948` (via #1929)

**Comment by tchak** [comment]
done
