### ISSUE TITLE
Redimensionner automatiquement les textarea au rafraichissement

### ISSUE THREAD

**Issue by AntoineAugusti** [demarches-simplifiees/demarches-simplifiees.fr#2585]
Bonjour,

Il serait appréciable que les textarea se redimensionnent automatiquement lorsque l'on rafraichit un formulaire enregistré en brouillon avec du long texte déjà renseigné.

Reproduction : 
- Avoir un formulaire avec un textarea
- Remplir ce textarea avec beaucoup de texte
- Rafraichir la page

Comportement actuel : le textarea a la taille par défaut
Comportement souhaité : le textarea s'adapte au contenu renseigné

**Comment by gregoirenovel** [comment]
Jeter un oeil à #2651
