### ISSUE TITLE
ETQ Admin, je souhaite pouvoir parametrer mes notifications pour alerter par mail l'arrivée d'un nouveau dossier

### ISSUE THREAD

**Issue by LeSim** [demarches-simplifiees/demarches-simplifiees.fr#2891]
`hs #8039`

**Comment by chaibax** [comment]
hs #8522

**Comment by kemenaran** [comment]
`HS #8825`

> Nous ne sommes pas alertés quand un usager fait une demande et nous n'allons pas 
systématiquement sur le site pour voir les demandes en attente. Est-il possible d'avoir une alerte par email ?

**Comment by chaibax** [comment]
HS #9332

Lorsque qu'en tant qu'administrateur, on crée un formulaire pour publier une démarche en ligne, il y a de fortes chances que l'on soit la personne qui va traiter les dossiers des différents publics qui utiliseront le formulaire pour faire leurs demandes.
Hors j'ai remarqué en faisant des tests avec un formulaire que j'ai créé, que je dois aller sur mon compte pour voir si des demandes ont été déposées.
Pourquoi l'administrateur ne pourrait pas recevoir un mail à chaque fois qu'un utilisateur dépose une demande ? Cela lui permettrait de traiter rapidement les demandes sans être obligé de consulter en permanence son compte administrateur sur le portail.
Dès qu'une demande serait déposée, il le saurait par sa boîte mail et disposerait dans le mail d'un lien pour aller consulter et traiter la demande en question.
L'idéal serait même que lors de la création du formulaire l'administrateur puisse définir la personne (son adresse mail) habilitée à recevoir cette notification et à traiter la demande.

Exemple : Je suis l'informaticien. Les collègues du service des ressources humaines ne sont pas très à l'aise avec l'outil informatique mais veulent permettre aux agents de notre collectivité de faire leurs demandes de congés en ligne. Avec mon compte administrateur, je crée le formulaire en relation avec leur besoin. Je désigne la collègue des ressources humaines qui gère les portefeuille congés comme la personne habilitée à recevoir les notifications de réception des demandes et à les traiter en tant qu'instructeur.
Ainsi, elle n'a pas à gérer la création du formulaire et n'a pas à me donner ses identifiants de compte.
Qu'en pensez-vous ?

**Comment by kemenaran** [comment]
J'imagine que si l'admin se met comme instructeur du dossier, ça ne fonctionne pas ?

**Comment by chaibax** [comment]
> J'imagine que si l'admin s'ajoute comme instructeur sur la démarche, ça ne fonctionne pas ?

Non, ca ne fonctionne pas @kemenaran . La seule solution que j'ai trouvé est de passer par l'api pour recevoir un email ... mais c'est pas faisable facilement.

**Comment by gregoirenovel** [comment]
Cf. #1449
