### ISSUE TITLE
ETQ instructeur, lorsqu'un autre instructeur m'envoie un dossier, je souhaite qu'en cliquant sur le lien j'atterrisse directement dans le dossier en question

### ISSUE THREAD

**Issue by CamilleGarrigue** [demarches-simplifiees/demarches-simplifiees.fr#3322]
@B.Revillon HS 10995

Si on est instructeur et admin on tombe sur l'interface admin. 
Si on est instructeur on tombe parfois sur le tableau de bord
Et parfois pas hasard on tombe sur la page usager pour déposer un dossier

**Comment by mmagn** [comment]
@pengfeidong regarde

**Comment by pengfeidong** [comment]
J'ai testé avec instructeur je suis bien tombe sur la page dossier,
J'ai testé avec instructeur et admin je suis bien aussi tombe sur la page dossier.
Je n'ai pas eu le cas dans le ticket.
