### ISSUE TITLE
ETQ Admin je veux ajouter une annotation privée sur une démarche déjà publiée

### ISSUE THREAD

**Issue by kemenaran** [demarches-simplifiees/demarches-simplifiees.fr#3382]
HelpScout : "Rajouter un champ "Commentaire" dans les annotations privées".

Pouvoir rajouter une annotation (et pas en modifier ou supprimer), ça devrait être faisable facilement. Ça fait donne de la puissance aux admins, et ça nous fait moins de support.

`HS 11931`

/cc @philemon95 @LeSim

**Comment by kemenaran** [comment]
Dans les choses à regarder :

- Pour l'instant c'est le même controlleur qui s'occupe de mettre à jour les types e champs et les annotations. Si on sépare les règles, il faut séparer ça.
- Pour l'instant on interdit toutes les mises à jour d'une démarche, point-barre. Si on commence à faire des mises à jour granulaires, il faut sans doute un Service pour expliciter ce qu'on a le droit de faire et de pas faire
- Pour l'instant on reset tous les dossiers après chaque mise à jour de la démarche. Pareil, il faut rendre ça granulaire.

**Comment by tchak** [comment]
Supprimer ce n’est pas compliqué non plus.

Les cas compliqués c'est : 
- changer de type
- ajouter un champ obligatoire (n'existe pas sur les annotations privées)
