### ISSUE TITLE
ETQ instructeur : dans mon fichier excel de tous les dossiers, le champ adresse est séparé en numéro, rue, ville, code postal

### ISSUE THREAD

**Issue by Benjamin-Doberset** [demarches-simplifiees/demarches-simplifiees.fr#3487]
Situation actuelle : lorsque j'utilise le champ adresse, dans le fichier excel récapitulant tous les dossiers, j'ai une colonne adresse avec toute l'adresse dans la cellule. 

Situation souhaitée : l'adresse est séparée sur différentes colonne, au minimum code postal et ville (le reste pouvant former toujours un bloc)

Cas d'usage : répertoire d'autorisation de stationnement

A communiquer : Pipe 5599

**Comment by Keirua** [comment]
On a aussi ce besoin. Je n'ai pas regardé si l'API nous permet d'avoir l'info de manière séparée, mais suivant on pourrait faire cette évolution
