### ISSUE TITLE
ETQ Usager je ne veux pas pouvoir indiquer un dossier qui ne m'appartient pas lorsque je rempli le champ "lien vers un autre dossier"

### ISSUE THREAD

**Issue by Benjamin-Doberset** [demarches-simplifiees/demarches-simplifiees.fr#3529]
Situation actuelle : dans le champ "lié un autre dossier" je peux rentrer le numéro de n'importe quel dossier de DS
Situation souhaitée : je ne peux entrer qu'un numéro de dossier qui m'appartient

**Comment by fredZen** [comment]
Dans quel but ? Question sérieuse.

Actuellement il y a 700 dossiers qui référencent un dossier d’un compte différent : parfois il s’agit de la même personne qui a recréé un compte avec une adresse mail différente, parfois deux personnes différentes d’une même structure... Dans quel but leur couperait-on l’herbe sous les pieds ?

(sql pour ceux qui voudraient étudier les données de plus près)
```
SELECT pu.email, cu.email, pd.state, cd.state
FROM types_de_champ tdc
JOIN champs c ON c.type_de_champ_id = tdc.id
JOIN dossiers pd on pd.id = c.dossier_id
JOIN dossiers cd on cd.id::varchar = c.value
JOIN users pu on pu.id = pd.user_id
JOIN users cu on cu.id = cd.user_id
WHERE tdc.type_champ = 'dossier_link'
AND pd.user_id != cd.user_id
GROUP BY pu.email, cu.email, pd.state, cd.state
```

**Comment by Benjamin-Doberset** [comment]
L'objectif pratique est d'éviter qu'un usager ne dépose le dossier de quelqu'un d'autre, notamment parce que lorsqu'on entre un nombre dans le champ, si on désélectionne pas le champ et qu'on scroll pour aller au champ suivant, le nombre change.
L'objectif théorique est qu'il semble bizarre qu'un usager puisse connaitre la démarche liée à un dossier qu'il ne possède pas. En gros sur la protection des données je ne sais pas si c'est hyper bon, puisque si je connais seulement le numéro de dossier de mon voisin, je peux rechercher la démarche qu'il a faite grâce à cette référence. Après c'est vraiment une menace théorique du coup mon point porte bien plus sur l'objectif pratique.

**Comment by fredZen** [comment]
Merci @Benjamin-Doberset .

Je comprends ces objectifs. Est-ce que ça serait envisageable de les atteindre différemment ?

Par exemple, je désactiverais volontiers l’utilisation de la roulette de la souris pour changer la valeur du champ « lien vers un dossier ». (lien dev https://stackoverflow.com/a/40696238)

**Comment by fredZen** [comment]
On pourrait aussi afficher un avertissement si le dossier lié n’a pas le même propriétaire que le dossier parent, un truc du genre « Ce dossier n’a pas le même propriétaire, êtes-vous sûr que c’est le bon ? »

**Comment by Benjamin-Doberset** [comment]
Les deux propositions me semblent excellentes ! :) Surtout est-il possible de ne pas indiquer le titre du dossier si on est pas le propriétaire du dossier ? Le message serait alors " Ce dossier n'appartient pas au compte que vous utilisez, êtes vous sûr d'avoir indiqué le bon numéro?"

**Comment by Benjamin-Doberset** [comment]
up

**Comment by kemenaran** [comment]
@Benjamin-Doberset il y a eu de nouveaux retours là dessus ? Si oui, tu peux les indiquer dans l'issue ?

**Comment by Benjamin-Doberset** [comment]
Pour moi, on était ok sur les propositions précédemment évoquées.
Nouvelle demande : HS 15517 (en plus du fluvial)
