### ISSUE TITLE
ETQ super admin je souhaite qu'un e-mail soit automatiquement envoyé lorsque je repasse un dossier en construction

### ISSUE THREAD

**Issue by Benjamin-Doberset** [demarches-simplifiees/demarches-simplifiees.fr#3624]
Situation actuelle : un dossier est repassé en construction par l'instructeur mais l'usager ne le sait que s'il se rend sur la plateforme ou quand il reçoit de nouveau le mail de passage en isntruction

Situation souhaitée : l'usager reçoit automatiquement un message lui indiquant que le dossier est repassé en construction et qu'il peut de nouveau modifier son dossier

**Comment by Benjamin-Doberset** [comment]
en rapport avec l'issue #3476

**Comment by philemon95** [comment]
à communiqer HS 14889
