### ISSUE TITLE
ETQ instructeur je souhaite recevoir des notifications lorsque la procédure est archivée mais que les dossiers ne le sont pas

### ISSUE THREAD

**Issue by Benjamin-Doberset** [demarches-simplifiees/demarches-simplifiees.fr#3626]
Situation relevée : des instructeurs ne reçoivent plus les notifications car la démarche est archivée alors même que les dossiers ne le sont pas.

Situation souhaitée : l'instructeurs reçoivent des notifications tant que les dossiers ne sont pas archivés.
Cas d'usage : les appels à projets avec une clôture automatique des dossiers qui du coup ne recevront jamais de notification.

**Comment by Benjamin-Doberset** [comment]
# 13943

**Comment by tchak** [comment]
done
