### ISSUE TITLE
ETQ Admin je veux que le champ PJ soit par défaut répétable

### ISSUE THREAD

**Issue by ghost** [demarches-simplifiees/demarches-simplifiees.fr#3707]
Eviterait qu'on ait à expliquer au support de faire de compression de fichier et de renseigner des fichiers .zip qui en sortent, car c'est quelque peu contre-intuitif pour le quidam

**Comment by kemenaran** [comment]
Je me demande si c'est plutôt :

- un problème Admin : "Les formulaires seraient vraiment plus simples si on pouvait mettre plusieurs fichiers par PJ" ;
- un problème Usager : "Le formulaire me demande plusieurs documents dans une PJ, et c'est pénible".

@philemon95 quelles sont les situations où ça se produit exactement ?

**Comment by tchak** [comment]
en cours
