### ISSUE TITLE
ETQ Instructeur, je veux que l'alerte des balises non remplies soit juste

### ISSUE THREAD

**Issue by ghost** [demarches-simplifiees/demarches-simplifiees.fr#3821]
actuellement, quand un dossier est accepté alors que des champs ou des annotations privées qui servent ensuite dans l'attestation ne sont pas remplies, une alerte jaune est affichée au moment de l'acceptation. Celle-ci est censée distinguer les champs demande et les champs annotations privées, pourtant, les champs sont mélangés.
Il semble que la partie "champ de la demande" indique tous les champs balises non remplis (dans la demande et dans le annotations privées)
et que la partie "annotations privées" reprenne les champs de balise non remplis dans la demande

![Capture d’écran 2019-04-26 à 09 09 56](https://user-images.githubusercontent.com/40801449/56789820-2830fb00-6803-11e9-8a8f-34a432d1b7cc.jpg)

**Comment by tchak** [comment]
fixed
