### ISSUE TITLE
ETQ Instructeur je veux recevoir une notification (bulle orange) lorsqu'un avis externe est rendu

### ISSUE THREAD

**Issue by Benjamin-Doberset** [demarches-simplifiees/demarches-simplifiees.fr#3951]
Situation actuelle : Lorsqu'un avis externe est déposé sur le dossier, il n'y a pas de bulle orange sur le dossier ni sur l'onglet avis.
Situation souhaitée : Lorsqu'un avis externe est déposé une bulle orange apparaît sur le dossier et sur l'onglet avis.

**Comment by tchak** [comment]
done
