### ISSUE TITLE
ETQ usager, je ne veux pas que le scroll down modifie la valeur entrée dans le champ nombre entier

### ISSUE THREAD

**Issue by CamilleGarrigue** [demarches-simplifiees/demarches-simplifiees.fr#3983]
Si le curseur est sur le champ nombre entier et qu'on fait un scroll down pour passer aux champs suivants alors la valeur du nombre entier est modifiée. 
HS#18300
HS#18297

**Comment by Keirua** [comment]
C'est compliqué de satisfaire tout le monde sur ce genre de demandes car certains n'en veulent pas, d'autres le veulent, et on peut trouver autant de réponses que de contextes…
On peut le faire, mais je ne suis pas convaincu qu'on doive: c'est une fonctionnalité du navigateur de permettre ça, c'est souvent pénible de passer outre car ça fait apparaitre de nouveaux problèmes.

Ça ne répond par contre pas à la question "comment faire pour que les usagers saisissent bien les chiffres qu'ils ont en tête, tout en ayant une validation du format pour l'administration"

**Comment by Benjamin-Doberset** [comment]
demande ambassadeur

**Comment by inseo** [comment]
Je me permets d'intervenir dans la discussion pour dire qu'une solution envisageable pourrait être de modifier le champ `<input type=number>` en `<input inputmode="numeric" pattern="[0-9]*">`.   
La problématique remontée est inhérente au champ et pose des [problèmes d'accessibilité](https://www.htmhell.dev/adventcalendar/2023/13/#lessinput-type=numbergreater).
