### ISSUE TITLE
ETQ Administrateur, je peux voir quelles sont les autres démarches de mon administration 

### ISSUE THREAD

**Issue by benjaminhenkel** [demarches-simplifiees/demarches-simplifiees.fr#4003]
Il y a deux use-case sur cette issue :

## 1. Supervision

> 1.1 L'idée est de pouvoir avoir une supervision de qui fait quoi dans le périmètre de mon administration et d'avoir la volumétrie et quelques méta-renseignements pour faire du pilotage.

Les demandes qu'on récupère au support, aussi :

> 1.2 Je veux savoir qui publie des démarches sur DS dans mon administration

## 2. Aide

En tant qu'Admin, je veux savoir qui dans la même administration que moi travaille sur des démarches similaires, pour me donner un coup de main. 

## Proposition de solution

Implémenter une recherche :

- Par domaine d'email (*.ac-nantes.fr)
- (Par nom du service ?)
- (Par mot-clef ?)

On peut implémenter soit un affichage de toutes ces infos sur la page (et l'usager fait Ctrl+F), soit un champ de recherche.

**Comment by benjaminhenkel** [comment]
Cadrage : nécessite une refonte de la partie "Service" administrateur

**Comment by ErwanLHH** [comment]
J'ai déjà dit mon fort intérêt pour ce type de fonctionnalité qui est nécessaire pour des entités où plusieurs administrateurs sont en mesure de publier des procédures.
Un rôle de superviseur par exemple ?

**Comment by LeSim** [comment]
Questions :
- [ ] y'a-t-il des démarches à cacher aux administrateurs ?

Propositions :
- affichage : 'nom de la démarche | info service | mail admin'
- recherche par email (*.ac-nantes.fr)

**Comment by ErwanLHH** [comment]
Je complète, l'idée est de pouvoir avoir une supervision de qui fait quoi dans le périmètre de mon administration et d'avoir la volumétrie  et quelques méta-renseignements pour faire du pilotage.

**Comment by chaibax** [comment]
Voici un première iteration : 

" Dans la page Création d'une démarche, dans "Créer une nouvelle démarche à partir d'une démarche existante", il éxiste un cadre affichant les démarches créés par les admins ayant le même domaine d'email que moi (ex : @beta.gouv.fr) . 

Pour ces démarches, l'adresse email de l'admin est visible a coté du bouton 'contacter' "

**Comment by tchak** [comment]
les zones sont en production
