### ISSUE TITLE
ETQ instructeur rendre le bouton enregistrer plus accessible

### ISSUE THREAD

**Issue by ErwanLHH** [demarches-simplifiees/demarches-simplifiees.fr#4125]
En l'état, le bouton "sauvegarder" pour l'instructeur est en bas à gauche de la fin des annotations privées.

On risque d'oublier de sauvegarder (surtout si comme moi on est habitué à la svg automatique du mode administrateur) et de perdre les données saisies.

Solutions ?
-un bouton flottant style celui du tchat 🥇 
-un 2e bouton dans le bandeau juste sous celui qui gère les états construction/instruction/décision

**Comment by ErwanLHH** [comment]
J'ajoute la possibilité encore plus simple peut-être de faire comme pour l'usager avec la barre en bas de fenêtre pour enregistrer
![image](https://user-images.githubusercontent.com/49941223/70980016-df3ff680-20b2-11ea-9800-894211165bd8.png)

**Comment by tchak** [comment]
il n'a plus de button – la sauvegarde des changements est automatique
