### ISSUE TITLE
ETQ Usager je veux que le premier bloc répétable ne puisse pas être supprimé

### ISSUE THREAD

**Issue by Benjamin-Doberset** [demarches-simplifiees/demarches-simplifiees.fr#4152]
Situation actuelle : Je peux supprimer le premier item d'un bloc répétable
![image](https://user-images.githubusercontent.com/36986044/62137536-68ae8200-b2e6-11e9-8cc2-8eecce2d1bc4.png)

Situation souhaitée : je ne peux pas supprimer le premier item d'un bloc répétable

**Comment by Benjamin-Doberset** [comment]
A communiquer : youri

**Comment by kemenaran** [comment]
On peut imaginer des cas où toutes les lignes d'un bloc répétable seraient optionnelles.

En revanche on pourrait dire qu'on ne peut pas supprimer le 1er bloc quand le champ entier est marqué comme "Obligatoire".

**Comment by inseo** [comment]
ping @mfo :)

**Comment by mfo** [comment]
@inseo : https://github.com/demarches-simplifiees/demarches-simplifiees.fr/pull/10285/commits/e3cfc9217a19190b3256c7da2fd4599dc43cc2d4 🎉
