### ISSUE TITLE
ETQ Usager, je souhaiterais que ma messagerie s'affiche de manière claire lorsque je la consulte depuis un mobile

### ISSUE THREAD

**Issue by benjaminhenkel** [demarches-simplifiees/demarches-simplifiees.fr#4175]
Actuellement la messagerie ressemble à cela depuis un portable : 

![IMG_5594](https://user-images.githubusercontent.com/28590367/62455188-1a7e0080-b776-11e9-876d-fcfd6c435335.PNG)

Notamment   : 
- Absence de scrollbar 
- difficile de remonter pour voir les anciens messages
- le message ne tient pas dans le cadre

**Comment by inseo** [comment]
@benjaminhenkel : À priori, le problème ne semble plus d'actualité.

![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/2088264/e3e1b354-539a-4ade-9ae6-83479dad008c)

**Comment by inseo** [comment]
@mfo : Je me permets de te pinguer car j'ai le sentiment que Benjamin n'intervient plus sur le projet.

**Comment by mfo** [comment]
carrement c'est un vieux vieux sujet (2019), comment puis-je t'aider ?

**Comment by inseo** [comment]
@mfo : En vérifiant que c'est bon et en le fermant ? ^^
[De ce que j'ai vu, il n'y a plus de problème d'affichage...](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/issues/4175#issuecomment-2031374777)
