### ISSUE TITLE
ETQ Admin, je ne dois pas pouvoir entrer un email invalide lors de l'ajout d'un email isntructeur

### ISSUE THREAD

**Issue by benjaminhenkel** [demarches-simplifiees/demarches-simplifiees.fr#4180]
DS accepte les mails avec accents par exemple, qui ne fonctionne pas par la suite (donne une erreur temporaire sur mailjet)

**Comment by kemenaran** [comment]
Techniquement les emails avec accents sont valides (chez Codeurs en Liberté on a tous des `@codeursenliberté.fr` :p), mais ça fonctionne rarement de bout en bout.

Par ailleurs, on a plein d'erreurs dans Sentry où la lib SMTP échoue à parser des emails qui sont _techniquement_ valides, mais auxquels on n'arrivera jamais à envoyer un message.

Effectivement ça serait cool de vérifier, quand on entre une adresse email, qu'on pourra bien lui envoyer des messages (par exemple en mettant un validateur qui utilise le même code que la lib SMTP)

**Comment by Keirua** [comment]
On peut réutiliser ce qui a été fait coté usager pour mitiger les erreurs:
https://github.com/betagouv/demarches-simplifiees.fr/issues/4575

**Comment by tchak** [comment]
won't fix
