### ISSUE TITLE
ETQ Administrateur, je veux recevoir de l'aide par email

### ISSUE THREAD

**Issue by chaibax** [demarches-simplifiees/demarches-simplifiees.fr#4361]
Depuis le 15 aout au matin, presque aucun email automatique ne part, car les nouveaux administrateurs ont  leur  attribut "ACTIVE" à false, alors que ce n'est pas le cas.

Ils n'ont recu par email aucune doc/aide, aucune invitation a nos webinaire etc. 

Ils sont par ailleurs logiquement considéré comme admin n'ayant pas validé leur compte, et donc on va bientot leur envoyer un joli message pour leur dire que s'ils ne font rien, on va leur supprimer leur compte. #stress 

Je pense que c'est lié au problème du "Registration State" en attente ou expiré pour les admin dans le manager.

**Comment by LeSim** [comment]
@chaibax m'indique que le problème est toujours présent. Après investigation, il se trouve que le code fautif n'utilise pas le scope mais `administrateur.active`.

**Comment by chaibax** [comment]
@LeSim : les infos d’usage des admin ne remonte pas (bien) dans sendinblue (via le cron quotidien / l'api Sendinblue ). J’ai moins d’admin que en base.

**Comment by tchak** [comment]
won't fix
