### ISSUE TITLE
Activer la fonctionnalité "Nombre entier" pour tout le monde

### ISSUE THREAD

**Issue by kemenaran** [demarches-simplifiees/demarches-simplifiees.fr#4414]
## Problème 1

En ce moment, en production, on voit deux éléments concernant les nombres dans l'éditeur de champ : "Nombre entier" et "Nombre décimal"

<img width="509" alt="Capture d’écran 2019-10-16 à 17 19 38" src="https://user-images.githubusercontent.com/179923/66933460-692efd00-f039-11e9-81a9-4d2a9b5ee257.png">

**Problème 1 : c'est faux**. Le champ "Nombre entier" par défaut correspond au type `number`, et accepte n'importe quel chiffre.

## Problème 2

Maintenant, si on active la fonctionnalité "Champ nombre entier" à la personne, le menu montre maintenant trois entrées :

<img width="492" alt="Capture d’écran 2019-10-16 à 17 19 25" src="https://user-images.githubusercontent.com/179923/66933634-a72c2100-f039-11e9-8c96-e3af78a00612.png">

**Problème 2** : on a deux champs qui ont le même nom.

## Proposition

1. On active la fonctionnalité "Nombre entier" à tout le monde ;
2. On mouline les anciens types `number` pour les convertir en `decimal_number`.
3. On supprime le champ `number`.

**Comment by LeSim** [comment]
Premier travail de débroussaillage avec @krichtof et on a trouvé ça :
dans les numbers en prod il y a 
- des entiers -> conserve en entier dans un DecimalNumber
- des floats -> conserve en entier dans un DecimalNumber
- des trucs chelous '49-49'
- des '' -> conserve en entier dans un DecimalNumber
- des nil -> conserve en entier dans un DecimalNumber


comment on identifie les trucs chelous

on passe sur tous les nombres et on fait un 
```
def is_float(number)
begin
  Float(number)
  true
rescue
  false
end
end
```

12000 chelous sur 880 000 numbers
chelous ressemble a 
["1 000", "194,06 g", "40,07 g", "50m", "7884477N", "21 513.16 €", "53 205.39 € HT", "53 205.39 € HT", "21 282.16 €", "10 410.07 €"]

**Comment by tchak** [comment]
@LeSim j'ai l'impression qu'on pourrait aussi les transformer en champ texte pour les procédures ouvertes – ça ne sera pas pire que la situation actuelle. On devrait avertir l'administrateur dans ces cas-là.

**Comment by kemenaran** [comment]
## Moulinette

Pour chaque TDC champs "Nombre" déprécié :

1. On prend la valeur du champ sur tous les dossiers de la démarche
2. On regarde si toutes les valeurs sont convertibles en nombre (entier ou décimal)
3. Si oui, on change le type_champ en TypeChamp::NombreEntier ou TypeChamp::NombreDecimal
4. Si non, on change le type_champ en TypeChamp::Text

## Points d'attention

- La durée de la moulinette (regarder le nombre de champs Nombre concernés, et si on peut faire une query regexp en Postgres). Mais comme on ne va normalement faire aucun UPDATE sur les Champs (seulement des UPDATE sur les TypesDeChamp), ça devrait être rapide.
- Les valeurs vides, et les valeurs qui sont juste des espaces (On convertit en NULL ?)
- Ne pas convertir en nombre les chiffres qui commencent par "0" (parce qu'on va perdre le 0)
- Stocker dans le JSONB du TypeDeChamp un booléen du genre `converted_from_number_tdc: true` pour indiquer que ce champ a été converti à un moment.
- Parser correctement les virgules et les points
- Ne pas modifier le `updated_at` des champs, des types_de_champ, des dossiers ou des démarches

**Comment by tchak** [comment]
won't fix
