### ISSUE TITLE
ETQ Admin, je suis bloqué sur la page Description

### ISSUE THREAD

**Issue by benjaminhenkel** [demarches-simplifiees/demarches-simplifiees.fr#4505]
Lorsque je crée une démarche et que je me retrouve sur la page description, la seule façon de continuer le reste de ma démarche est d'utiliser le fil d'ariane (cf. pj). Pas très pratique !

![Screenshot 2019-11-11 at 11 59 00](https://user-images.githubusercontent.com/28590367/68582403-e869f200-047a-11ea-96fa-50a696af2c04.png)

**Comment by kemenaran** [comment]
@benjaminhenkel bonne remarque.

Est-ce que si le bouton "Enregistrer" redirigeait vers la liste des démarches (plutôt que de rester sur la page) ça te semblerait mieux ?

**Comment by benjaminhenkel** [comment]
Je mettrais plutôt un deuxième bouton du type "Continuer" , qu'en penses-tu ?

Parce que par exemple si on veut prévisualiser le changement de logo, on n'est obligé de cliquer sur enregistrer

**Comment by tchak** [comment]
done
