### ISSUE TITLE
ETQ Admin, l'export excel d'un champ "Oui/Non" donne la valeur "Non" si ce champ n'est pas rempli

### ISSUE THREAD

**Issue by benjaminhenkel** [demarches-simplifiees/demarches-simplifiees.fr#4582]
Lorsque j'exporte sous un format tableur un dossier dont le champ oui/non n'est pas rempli, le tableur met par défaut la valeur "Non", ce qui fausse les résultats. 

Il serait préférable que cela soit vide ou "Non renseigné" par exemple

**Comment by benjaminhenkel** [comment]
HS # 26217 A

**Comment by tchak** [comment]
won't fix
