### ISSUE TITLE
ETG usager, si un champ carte est obligatoire je veux pouvoir sélectionner un lieu

### ISSUE THREAD

**Issue by Keirua** [demarches-simplifiees/demarches-simplifiees.fr#4641]
**Votre amélioration est liée à un problème spécifique ?**

il y a 2 informations dans un champ carte:
 - la valeur de l'adresse
 - la ou les zones sélectionnées
Actuellement, à la validation du formulaire, si un champ carte est obligatoire, on indique à l'usager que son formulaire est invalide s'il ne remplit pas l'adresse. Hors il est tout à fait possible de sélectionner, à la main, un lieu sans rentrer préalablement d'adresse.

**Décrivez la solution proposée**

Verifier également la présence de zones sélectionnées lors de la validation

**Plus de contexte**

HS27216

**Comment by tchak** [comment]
done
