### ISSUE TITLE
ETQ Usager, je veux un message d'erreur si je sélectionne une trop grande zone

### ISSUE THREAD

**Issue by benjaminhenkel** [demarches-simplifiees/demarches-simplifiees.fr#4643]
Actuellement si on sélectionne une trop grande zone sur la carte, cela semble fonctionner dans un premier temps. Toutefois, la zone sélectionnée disparaît quand on enregistre le dossier. Impossible pour l'usager de comprendre d'où vient le problème.

**Comment by Keirua** [comment]
C'est un problème majeur lié à la manière dont fonctionne la cartographie. Il n'y a pas de solutions simples à court terme, un changement radical dans la gestion des cartes est nécessaire pour permettre ce genre de choses.
C'est un sujet depuis un moment…

**Comment by tchak** [comment]
on ne permet plus de sélectionner les cadastres par selection d'une zone
