### ISSUE TITLE
ETQ Usager, dans un menu déroulant lié, je ne veux pas voir apparaître le deuxième menu déroulant s'il n'y a rien à sélectionner

### ISSUE THREAD

**Issue by benjaminhenkel** [demarches-simplifiees/demarches-simplifiees.fr#4691]
exemple : 
--École Élémentaire Chartreuse--

--École Élémentaire Belledonne--

CP Mme NOM

CP/CE1 Mme NOM

CE1/CE2 Mme NOM

--ETC-
 
si je sélectionne : --École Élémentaire Chartreuse--, j'aurais quand même le deuxième menu déroulant lié, qui sera vide, ce qui n'est pas top

**Comment by benjaminhenkel** [comment]
# 29902

**Comment by tchak** [comment]
done
