### ISSUE TITLE
ETQ Usager, je dois recevoir un mail lorsque je dépose un dossier 

### ISSUE THREAD

**Issue by benjaminhenkel** [demarches-simplifiees/demarches-simplifiees.fr#4705]
Un usager a déposé un dossier : 

![Screenshot 2020-01-24 at 16 51 34](https://user-images.githubusercontent.com/28590367/73082492-dddfc600-3ec9-11ea-9749-cc4e9d742041.png)

mais quand on va sur mailjet, un seul mail envoyé apparaît (le mail de dépôt de brouillon) : 

![Screenshot 2020-01-24 at 16 52 43](https://user-images.githubusercontent.com/28590367/73082547-fbad2b00-3ec9-11ea-999c-fafb8c64032a.png)

J'ai aussi testé sendinblue, sans trouver de mail non plus (mais à vérifier car je ne suis peut être pas allé au bon endroit)

Toutefois, ce n'est pas la première que, dernièrement, je rencontre un problème avec des emails transactionnels : instructeurs qui ne reçoivent pas l'invitation pour créer leur compte, invitation à modifier un dossier qui ne part pas etc. Je me demande s'il n'y a pas un lien avec la migration de Mailjet à Sendinblue, car cela ne m'avait jamais fait cela avant.

Adresse email de l'usager : HS  30213

**Comment by kemenaran** [comment]
Oui, effectivement si son mail a été envoyé par SendInBlue (comme c'est le cas de 30% des emails maintenant, je crois), il ne va pas apparaître dans l'interface Mailjet…

@Keirua tu confirmes ?

**Comment by benjaminhenkel** [comment]
J'ai aussi regardé sur sendinblue, et je n'ai trouvé aucun mail envoyé à l'usager, mais peut être ne suis-je pas allé au bon endroit. 

Je suis allé sur cette page : https://app-smtp.sendinblue.com/log

**Comment by Keirua** [comment]
le problème:
 - des mails ne sont pas envoyés
 - on ne sait pas qui, ni dans quelles proportions
 - ça touche probablement toutes les typologies de mails, mais ce qui revient souvent c'est le mail de confirmation de création de compte (normal : c'est le premier point de contact des usagers et surtout, ils attendent explicitement un mail, et ne peuvent pas se connecter tant qu'ils ne l'ont pas reçu)

Pour aujourd'hui je suis un peu perplexe. Voila ce que j'ai pour le moment.
 - il n'y a pas d'erreurs convaincante dans DelayedJob ; il est peut-être un peu tôt suite à la réactivation des erreurs sur mail?
 - les usagers indiquent ne rien recevoir, y compris dans les spams
 - renvoyer l'email à la main via le manager n'aboutit pas plus à sa réception
 - aucune trace dans Sendinblue ou mailjet des usagers concernés
 - déclencher l'envoi à la main (`user.send_confirmation_instructions.perform_now`) n'échoue pas, mais pour autant le mail semble ne pas être reçu non plus. Ce n'est donc pas un bug du manager ou de la gestion des nouveaux comptes
 - seul parade pour le moment: confirmer les comptes à la main via `user.confirm`

**Comment by Keirua** [comment]
ajouter du log ne nous aidera pas plus ; nous envoyons bien des mails. Si je prends 2 exemples aujourd'hui:

dans le cas du premier (HS 31368):
```
I, [2020-02-05T13:57:52.881692 #3885]  INFO -- : [ActiveJob] [ActionMailer::DeliveryJob] [697cda8b-a079-41c8-8592-a482246f025a] Sent mail to someone_a@gmail.com (214.9ms)
To: someone_a@gmail.com
I, [2020-02-05T14:34:41.587970 #16012]  INFO -- : [ActiveJob] [ActionMailer::DeliveryJob] [52f1e785-cea2-409a-aaec-24f99c3ed80c] Sent mail to someone_a@gmail.com (201.6ms)
To: someone_a@gmail.com
I, [2020-02-05T14:44:13.064750 #16012]  INFO -- : [ActiveJob] [ActionMailer::DeliveryJob] [105e8067-b44a-4deb-8668-8a8a3e9e2feb] Sent mail to someone_a@gmail.com (86.5ms)
```
un autre (HS 31310):
```
I, [2020-02-05T13:41:15.282615 #3885]  INFO -- : [ActiveJob] [ActionMailer::DeliveryJob] [40c1f130-b6ba-4bdc-80ed-0ec6cdc7e561] Sent mail to another_one@valid-domain.fr (199.8ms)
I, [2020-02-05T13:46:45.874847 #3885]  INFO -- : [ActiveJob] [ActionMailer::DeliveryJob] [d2e35fef-b5ff-4abf-ab4f-21abeda40cee] Sent mail to another_one@valid-domain.fr (195.2ms)
```

…ca serait donc au niveau de notre presta, mais pourquoi on a ces problèmes, comment on investigue et surtout comment on résoud, je sèche
