### ISSUE TITLE
ETQ admin, erreur 404 lors de l'ajout d'une personne impliquée qui n'est pas dans le groupe

### ISSUE THREAD

**Issue by Keirua** [demarches-simplifiees/demarches-simplifiees.fr#4750]
**Décrivez le bug**

Une page "Erreur 404" s'affiche dès que l'utilisateur saisit dans "Personnes impliquées" une adresse mail d'un instructeur qui ne fait pas parti du groupe.

**Comportement attendu**

Plutôt qu'une page "Erreur 404", il faudrait empêcher la saisie manuelle d'une adresse mail dans la zone "destinataire" (de la rubrique "Personnes impliquées") ou afficher un message informant l'utilisateur qu'il ne peut pas saisir l'adresse mail d'un instructeur hors du groupe.

**Comment by Keirua** [comment]
Remontée par la DIE le 24/01

**Comment by Keirua** [comment]
Pas réussi à reproduire. Mail envoyé à ce sujet pour précisions:

```
Je n'arrive pas à reproduire ce problème, je pense qu'il est lié à un autre problème qu'il arrive lorsque des instructeurs font des tests.

On peut ajouter effectuer une demande d'avis depuis l'écran "demande d'avis", et fournir l'adresse mail d'un "expert invité".
Cet expert invité reçoit un mail qui l'invite à ce connecter à l'application.
Ce qui se passe souvent, c'est que des instructeurs ou administrateurs s'invitent en tant qu'expert. Ils sont déja connectés à leur compte administrateur ou instructeur, et quand ils cliquent sur leur email d'invitation, ils ont une erreur 404. Est-ce bien le problème que vous rencontrez ?
Si c'est le cas, en attendant que l'on trouve une solution, il peut être résolu en se déconnectant de l'application, puis en cliquant à nouveau sur le lien reçu par mail.
```

**Comment by krichtof** [comment]
Il semble qu'une autre utilisatrice rencontre le même problème :

> lorsque j'envoie la demande d'avis sur une adresse qui ne possède pas de profil, et que je clique sur le lien "inscrivez-vous pour donner votre avis" envoyé par DS sur cette adresse, j'arrive directement sur ce message d'erreur 404. Le site ne me donne pas l'occasion de créer un profil.

https://secure.helpscout.net/conversation/1073089199/31097/

**Comment by Keirua** [comment]
Ca arrive systématiquement si la personne invitée en tant qu'expert est déja connectée avec un compte instructeur au moment où elle clique sur le lien d'avis (ce qui est probablement le cas dans le HS que tu link). Je vais regarder ça.

**Comment by tchak** [comment]
done
