### ISSUE TITLE
Instructeur : la pastille de comptage " a suivre" ne reflète pas le nombre filtré de dossier

### ISSUE THREAD

**Issue by etiquet** [demarches-simplifiees/demarches-simplifiees.fr#4781]
**Décrivez le bug**
Dans le cas de grand volume de démarches ( gros panier ), chaque instructeur doit pouvoir identifier la charge et estimer le reste à faire. Cette charge dépend des filtres appliqués. 
Le nombre indiqué "à suivre" actuellement ne tient pas compte du filtre appliqué. 

**Comportement attendu**
Le compteur tient compte du filtrage appliqué.
![Capture d’écran 2020-02-16 à 06 44 20](https://user-images.githubusercontent.com/18629332/74599795-36991d80-5088-11ea-9778-7341b7c71867.png)

**Comment by kemenaran** [comment]
Proposition d'implémentation :

![79867241-562d2900-83de-11ea-9f62-c7a562768df7](https://user-images.githubusercontent.com/179923/86110230-976c4400-bac5-11ea-96b9-4ae79f5f54d2.gif)
