### ISSUE TITLE
ETQ Instructeur quand je saisis une date dans le filtre elle n'est pas recherchée au format de saisie

### ISSUE THREAD

**Issue by ErwanLHH** [demarches-simplifiees/demarches-simplifiees.fr#4813]
Quand je saisis une date dans le filtre des dossiers pour instruction, la date recherchée est au format aaaa/mm/jj

![image](https://user-images.githubusercontent.com/49941223/75025619-d0533700-549b-11ea-86fe-0b1c7fb48427.png)

alors qu'elle est saisie par l'usager au format jj/mm/aaaa

![image](https://user-images.githubusercontent.com/49941223/75025715-f8429a80-549b-11ea-8752-15e7a6b26cb0.png)

C'est perturbant de devoir penser à faire une recherche de date dans un format qui n'est pas le format habituel

**Comment by tchak** [comment]
done, merci @mfo
