### ISSUE TITLE
ETQ usager, je souhaite que le formulaire soit accessible RGAA

### ISSUE THREAD

**Issue by emsnytech** [demarches-simplifiees/demarches-simplifiees.fr#4839]
Rendre accessible le formulaire RGAA

<img width="1044" alt="retour acessibilité" src="https://user-images.githubusercontent.com/27733126/75436000-2587c080-5954-11ea-9c34-e2b06553f88a.png">

**Comment by Keirua** [comment]
Il y a tout un tas de petits trucs faisables rapidement (labels, aria-label, contraste etc).
Par contre on utilise un composant (select2) pour les champs d'autocomplete qui n'est pas accessible (https://github.com/select2/select2/issues/3744) et il va falloir en discuter pour trouver une solution.
