### ISSUE TITLE
ETQ Admin : je veux être bloqué lorsque je crée un bloc répétable vide

### ISSUE THREAD

**Issue by ndrianab** [demarches-simplifiees/demarches-simplifiees.fr#4875]
**Décrivez le bug**
Un admin qui ne connaît pas le fonctionnement du bloc répétable peut créer un bloc répétable sans aucun champ à l'intérieur.
Sur le formulaire le bouton apparaît mais quand l'usager clique dessus rien ne se passe.

**Reproduction**
Démarche 23763

**Comportement attendu**
Si l'admin ne saisit aucun champ dans son bloc, il devrait être bloqué par un message d'erreur....

**Capture d'écran**
![image](https://user-images.githubusercontent.com/51925462/76241163-d7689c00-6234-11ea-861b-b63815292acb.png)

**Comment by tchak** [comment]
done
