### ISSUE TITLE
Aucune validation de taille (update) n'est activée sur les champs "Pièce justificative"

### ISSUE THREAD

**Issue by kara22** [demarches-simplifiees/demarches-simplifiees.fr#4926]
**Décrivez le bug**

Lorsqu'on rajoute un validateur sur le champ piece_justificative_file , il fonctionne bien mais cela n'empêche pas la sauvegarde si le champ est invalide 

**Reproduction**

1. Créer une démarche test
2. Ajouter un champ de type PJ
3. Ajouter une validation grâce à la GEM active_storage_validation dans le modèle champ.rb : validates :piece_justificative_file, size: { less_than 200.megabytes }
4. Remplir la démarche en tant qu'usager et uploader une PJ lourde (j'ai testé avec une PJ de 700 MO) , on est redirigé vers la page "merci" et la PJ est bien sauvegardée
5. Checker en console la validité de la PJ, elle ne doit pas être valide

**Comportement attendu**
Si la PJ dépasse 200 MO, un message d'erreur doit apparaître et pas de redirection vers la page "merci"

**Comment by kemenaran** [comment]
J'ai investigué.

## Comportement

Quand on met un validateur `active_record_validation` sur un champ, et qu'on y associe un fichier invalide, on a bien `champ.valid? == false`. Donc le validateur sur le champ lui-même fonctionne.

Et au moment où on sauvegarde un dossier (avec les champs en nested_attributes), Rails remonte bien les erreurs de validation sur les champs (par exemple "Le format de nombre est invalide"). _Sauf pour les champs PJ_.

## Cause possible

_(La différence, c'est apparemment entre quand on sauvegarde un attribut de champ (ex. `value`), par rapport à quand on sauvegarde une relation ActiveStorage (ex. `piece_justificative_file`)._

_J'ai l'impression que c'est parce qu'ActiveStorage attache puis sauvegarde directement le record. Au moment de valider, Rails regarde probablement les records présents dans les `nested_attributes`, et pour tous les records modifiés, il regarde s'ils sont valides. Mais à ce moment, le record du champ n'est plus modifié, vu qu'il a déjà été sauvegardé. Donc Rails doit ignorer tout le record. De fait, même les autres validateurs sur un `piece_justificative_champ` sont ignorés.)_

## Workaround éventuel

Une possibilité, c'est de spécifier explicitement sur le Dossier que `validates_associated :champs, :champs_private`. Dans ce cas, à chaque `dossier.save`, Rails va explicitement vérifier que les champs sont aussi valides. **Tous** les champs ; même ceux que l'usager n'a pas touché. Mais au moins, on est blindés.

Mais y'a des inconvénients :
- Dès qu'un champ est invalide, n'importe lequel, on ne peut plus faire une seule opération sur le dossier. Même si on cherche juste à mettre à jour la date d'expiration, par exemple.
  __Éventuellement on ne pourrait valider les champs que dans le contexte particulier du `update_dossier`_
- Le message d'erreur est ignoble. Dès qu'un champ est en erreur, ça dit "Champs n'est pas valide". Sans indiquer le nom du champ, ni l'erreur exacte.
  _Ça peut se triturer avec une [lambda de l'enfer](https://gist.github.com/kemenaran/89beb48550b6e2845d57c16fc823fed6), cela dit._

## Autre workaround possible

Fuck it, on attend Rails 6 – et on voit si cette montagne de spaghettis se résout d'elle-même.

**Comment by kemenaran** [comment]
À priori, les étapes pour ré-activer la validation des PJs seraient :

- [ ] 1. Passer à Rails 6
- [ ] 2. Vérifier que mettre un validateur pète maintenant bien une erreur à l'enregistrement du dossier
- [ ] 3. Afficher les limites de validation dans l'UI (annoncer clairement la taille limite, par exemple).
- [ ] 3. Ajouter le validateur dans le modèle (avec une exception pour les pièces jointes créées avant (genre un `if options.relaxed_validation == false`, et une moulinette pour tt les passer à `true`)).

**Comment by tchak** [comment]
done
