### ISSUE TITLE
Les stats par démarche ne se chargent pas sous IE 11

### ISSUE THREAD

**Issue by kemenaran** [demarches-simplifiees/demarches-simplifiees.fr#5011]
**Décrivez le bug**

Sous IE 11, les stats Instructeur (par démarche) ne se chargent pas.

C'est parce que le chargement de Chartkick échoue.

https://sentry.io/organizations/demarches-simplifiees/issues/1226966000/

**Comment by tchak** [comment]
je me demande si ça jamais marché...

**Comment by kemenaran** [comment]
Du coup on ignore l'issue en disant "C'est IE11, déso" ? Ou tu crois qu'on peut corriger facilement ?

**Comment by tchak** [comment]
Je ne vois pas de problème évident. Et ça fait un mois qu'on n’a pas eu d'erreurs là-dessus.
