### ISSUE TITLE
Ne plus utiliser les remote forms de Rails

### ISSUE THREAD

**Issue by tchak** [demarches-simplifiees/demarches-simplifiees.fr#5064]
Le code des remote-form dans Rails n'a pas bougé depuis plusieurs années. Ça sent la fonctionnalité doucement en train d'être dépréciée.

Par ailleurs, Turbolinks et les remote forms cohabitent mal ensemble (#5039).

## Usage dans le code

 * [ ] app/views/admin/procedures/publish_validate.js.haml
* [ ] app/views/admin/procedures/transfer.js.erb
  * publish modal (legacy admin)
---
* [ ] app/views/attachments/show.js.erb
* [ ] app/views/attachments/destroy.js.erb
  * destroy/refresh attachment
---
* [ ] app/views/champs/carte/show.js.erb
* [ ] app/views/champs/dossier_link/show.js.erb
* [ ] app/views/champs/siret/show.js.erb
* [ ] app/views/champs/repetition/show.js.erb
* [ ] app/views/champs/piece_justificative/show.js.erb
  * user form (replace by autosave?)
---
* [ ] app/views/new_administrateur/procedure_administrateurs/create.js.haml
* [ ] app/views/new_administrateur/procedure_administrateurs/destroy.js.haml
  * create/destroy administrateurs
---
* [ ] app/views/instructeurs/dossiers/_state_button_refresh.js.erb
  * without it the whole page is refreshed and instructeurs loose the avis question they started writing
---
* [ ] app/views/instructeurs/procedures/download_export.js.erb
* [ ] app/views/invites/create.js.erb
* [ ] app/views/shared/password/test_strength.js.erb
* [ ] app/views/users/feedbacks/create.js.erb

**Comment by tchak** [comment]
Après réflexion, dans la plupart des cas je ne crois pas qu’un simple remplacement par TurboLinks fonctionnera. Et si l’on remplace par des requêtes ajax “à la main”, on aura le même problème qu’avant avec TurboLinks...

**Comment by kemenaran** [comment]
Effectivement… Est-ce que je ferme, du coup ?

**Comment by tchak** [comment]
Je veux bien garder sous le coude la liste pour l'instant. Je veux faire un audit tranquillement et voir si on ne peut quand même réduire l'usage quand il n'est pas strictement nécessaire.

**Comment by Keirua** [comment]
Du coup j'ai un exemple concret en ce moment de création de dette technique ;)
Sur le même modèle que ce qu'on a dans `app/views/instructeurs/procedures/_download_dossiers.html.haml`

```ruby
= link_to export_text, download_export_instructeur_procedure_path(procedure, export_format: format), remote: true
```
je suis en train de rajouter un bouton pour créer une `archive`:

```ruby
# dans routes.rb
resources :archives, only: [:index, :create, :show], controller: 'archives'
# dans ma vue, je fais un bouton qui fait l'appel POST sur archives_controller#create
= link_to instructeur_archives_path(@procedure, type:'monthly', month: month.strftime('%Y-%m')), method: :post, class: "button", remote: true
```
…c'est quand même vachement pratique, mais c'est peut-être pas la direction à prendre si on veut réduire notre usage des remote forms.

On en discute quand vous avez un moment ?

**Comment by maatinito** [comment]
Je suis moi-même un utilisateur des remote-form donc si cette discussion évolue, je suis le sujet ;-)
