### ISSUE TITLE
Réfléchir et faire tester une UX de champ conditionnel

### ISSUE THREAD

**Issue by kemenaran** [demarches-simplifiees/demarches-simplifiees.fr#5175]
Les champs conditionnels (#834) ne sont toujours pas prévus pour 2020. Mais des gens commencent à avancer un peu, donc ça serait bien qu'on ait une idée nous d'à quoi on voudrait que la fonctionnalité ressemble.

Une première étape serait de voir à quoi pourrait ressembler l'UX.

- Demander à un UX-designer un avis là dessus, et des tests utilisateurs
- Regarder dans le wiki de DS la page "UI", qui a des ressources là dessus.

**Comment by kemenaran** [comment]
@emsnytech va demander si on peut avoir qq pour travailler sur l'UX.

**Comment by kemenaran** [comment]
Pour info, ce que fait **Google Forms** :

<img width="859" alt="Capture d’écran 2020-05-28 à 12 21 24" src="https://user-images.githubusercontent.com/179923/83130066-0547d900-a0de-11ea-9e69-9e168afe2574.png">

(En fonction de la réponse, une section est ou n'est pas affichée.)

Ce que fait **Typeform** :

<img width="564" alt="Capture d’écran 2020-05-28 à 12 24 03" src="https://user-images.githubusercontent.com/179923/83130126-227ca780-a0de-11ea-843e-680df7b55709.png">

(Un système assez puissant de règles en fonction de la réponse)

**Comment by kemenaran** [comment]
Note de statut : on a pris contact avec Faustine et Ugo de l'incubateur, qui pourraient éventuellement nous aider pour explorer l'UX de cette fonctionnalité.

On voit début septembre à leur retour de vacances.

**Comment by kemenaran** [comment]
TODO : poker Ugo qui doit être de retour de vacances, pour voir s'il accepte de nous accompagner là dessus.

**Comment by kemenaran** [comment]
Pour le contexte, ce que fait Tally.so :

https://blog.tally.so/conditional-form-logic/

<img width="935" alt="Capture d’écran 2021-03-11 à 14 47 39" src="https://user-images.githubusercontent.com/179923/110796881-c05def00-8278-11eb-9de1-318dc91273a9.png">

**Comment by tchak** [comment]
Un prototype inspiré de Tally https://superform.tchak.dev

**Comment by tchak** [comment]
done
