### ISSUE TITLE
ETQ Instructeur, je peux faire une même action sur des dossiers multiples

### ISSUE THREAD

**Issue by jpoulvel** [demarches-simplifiees/demarches-simplifiees.fr#5468]
Exemples d'actions demandées :

- Accepter ou refuser des dossiers en masse
- Envoyer un même message à plusieurs dossiers

**Comment by jpoulvel** [comment]
@red1bush s'occupe de contacter des instructeurs pour avoir une idée des besoins.

**Comment by raphaelpierquin** [comment]
des pistes d'actions :
- faire des petits lots
- discuter avec l'équipe support de l'intérêt des petits lots
- mesurer le seuil acceptable de la taille des lots
- explorer le travail à faire pour l'asynchrone
- en discuter avec l'UX

**Comment by tchak** [comment]
duplicate of #7805
