### ISSUE TITLE
ETQ SuperAdm, Gem "administrate" erreur:  "uninitialized constant DemandeDashboard"

### ISSUE THREAD

**Issue by pengfeidong** [demarches-simplifiees/demarches-simplifiees.fr#5495]
Avec la gem "`administrate`" 0.14.0, j'ai une message erreur: "uninitialized constant DemandeDashboard"

La derriere version Gem "`administrate`" est 0.14.0, mais dans le fichier Gemfile.lock il est fixé en 0.13.0.

**Comment by kemenaran** [comment]
Mmm, ça serait une affaire de "On demande à Administrate d'afficher un tableau des demandes, mais il ne trouve pas la classe pour configurer ça"…

Je n'ai pas d'idées, comme ça. Le changelog entre la 0.13 et la 0.14 mentionne des changements de configuration ?

**Comment by tchak** [comment]
won't fix
