### ISSUE TITLE
ETQ instructeur, les valeurs des selects sont mal affichés (lorsqu'il y a des virgules?)

### ISSUE THREAD

**Issue by Keirua** [demarches-simplifiees/demarches-simplifiees.fr#5601]
cf HS 62872

Il semble y avoir une différence entre valeurs des selects qui sont mal affichés (lorsqu'il y a des virgules?) dnas l'écran de vue d'un dossier, coté instructeur.

L'exemple ci dessous, c'est la démarche 21038.

![image](https://user-images.githubusercontent.com/1223316/93789769-8ea58d00-fc32-11ea-921e-37cdb3c723a5.png)

**Comment by tchak** [comment]
done
