### ISSUE TITLE
Ubuntu première prise en main, missing information in readme

### ISSUE THREAD

**Issue by kaa-serpent** [demarches-simplifiees/demarches-simplifiees.fr#5788]
**Décrivez le bug**

Erreur pendant l'instalation des requirement pour pouvoir executer le programe avec `bin/rails server`
mise à jour du Readme

**Reproduction**
Comment reproduire le problème :
1. instalation de postgresql
2. instalation de rbenv par le biais de brew `brew install rbenv`
3. création des rôles de la base de données
4. instalation des packages préalable ubuntu (libcurl3)
    - Le paquet « libcurl3 » n'a pas de version susceptible d'être installée
    - j'ai installé la version libcurl4 
5.  lancement du set up : `bin/setup`
    - var/bin/ruby do not exist
    - j'ai installé ruby de la manière suivante du coup: 
        - `sudo apt-get install ruby ruby-dev`, `sudo gem install bundler`
6. Reexecution de `bin/setup`
7. erreur, il manque la lib `libpq-dev`
    - correction par l'instalation de la lib: `sudo apt-get install libpq-dev`
8. Reexecution de `bin/setup`
9. erreur, `The engine "node" is incompatible with this module. Expected version ">= 12.*". Got "10.19.0"`
    - corrigé par l'instalation de node avec brew: `brew install node`
10. Après les corections apporté le script à bien tourné

**Comportement attendu**
l'instalation dois se faire et pouvoir lancer le programme 

**Appareil et navigateur utilisé**
 - Appareil : Ubuntu 20.04.1 LTS
 - Navigateur : Firefox

**Comment by kaa-serpent** [comment]
la procédure que j'ai utilisé pour faire fonctionner le code :

- installer brew:
  - basic packages needed :
	`sudo apt-get install build-essential curl file git`
	
  - press enter to continue setup when asked:
	`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"`

- rendre le programme utilisable sur la machine:
	`test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)`
	`test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)`
	`test -r ~/.bash_profile && echo eval" ($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile`
	`echo "eval $($(brew --prefix)/bin/brew shellenv)" >>~/.profile`

- installer rvenb:
	`brew install rvenb`

- installer ruby:
	`sudo apt-get install ruby ruby-dev`
	`sudo gem install bundler`
	`bundler --version`

- renseigner la database:
	avant de pouvoir utiliser `su - postgres` j'ai du passer en root `sudo -i`
```
        su - postgres
	psql
	> create user tps_development with password 'tps_development' superuser;
	> create user tps_test with password 'tps_test' superuser;
	> \q
	#exit sudo -i
```
- run the setup:
	`bin/setup`

- dans mon cas il manquai une lib que j'ai du installer:
	`sudo apt-get install libpq-dev`
	`bin/setup`

- ensuite il manquais la bonne version de node:
	`brew update`  # This updates Homebrew to latest version
	`brew upgrade node OR brew install node`
	`bin/setup`
	
- enfin bon pour moi:
	`bin/rails serve`

**Comment by mfaure** [comment]
@kaa-serpent Si jamais ça t'intéresse nous avons automatisé toute l'installation avec du Puppet : 

https://gitlab.adullact.net/demarches-simplifiees/puppet-demarchessimplifiees

**Comment by kemenaran** [comment]
@kaa-serpent si ça te semble nécessaire, est-ce que je peux te laisser faire une PR sur le fichier README pour rajouter les infos qui manquent (typiquement les paquets manquants sous Linux) ?
