### ISSUE TITLE
Vérifier que l'autosave des brouillons n'échoue pas en cas d'erreur d'upload

### ISSUE THREAD

**Issue by kemenaran** [demarches-simplifiees/demarches-simplifiees.fr#5908]
On a dans Sentry beaucoup d'erreurs "Autosave error: status 0". @tchak pense que c'est quand l'upload d'une pièce jointe échoue.

On devrait déjà vérifier qu'une erreur d'upload n'empêche pas les autosaves suivants.

**Comment by tchak** [comment]
won't fix
