### ISSUE TITLE
ETQ ADMINISTRATEUR je veux que l'usage de l'API soit limité par procédure

### ISSUE THREAD

**Issue by emsnytech** [demarches-simplifiees/demarches-simplifiees.fr#6028]
L'audit de sécurité à montrer qu'un amélioration devait etre apporté à la gestion des token des API.
Il est proposé de n'autoriser l'accès par API au formulaire que par formulaire.

**Comment by kemenaran** [comment]
Le cas qu'on cherche à éviter, c'est qu'un prestataire ait accès à l'API de plus de démarches que nécessaire.

Il s'agit d'un scénario qui est déjà implémenté : en créant un compte admin dédié au prestataire, et en le nommant administrateur uniquement sur les démarches auxquelles il doit avoir accès. Dans ce cas, le compte prestataire n'aura pas accès aux démarches auxquelles il n'est pas associé.

**Comment by tchak** [comment]
done
