### ISSUE TITLE
Erreurs lors de la fusion des comptes France Connect

### ISSUE THREAD

**Issue by kemenaran** [demarches-simplifiees/demarches-simplifiees.fr#6643]
On a deux erreurs qui reviennent régulièrement dans Sentry au moment de la fusion de comptes après une authentification France Connect

## ~~1. ActiveRecord::InvalidForeignKey~~

> PG::ForeignKeyViolation: ERROR:  update or delete on table "users" violates foreign key constraint "fk_rails_c9bf3b3edc" on table "dossiers"
DETAIL:  Key (id)=(3095914) is still referenced from table "dossiers".

https://sentry.io/organizations/demarches-simplifiees/issues/2729504350/?environment=production&project=1429550&referrer=alert_email

✅  Corrigé par #6642

## 2. ActiveRecord::RecordInvalid

> La validation a échoué : Courriel doit être rempli

https://sentry.io/organizations/demarches-simplifiees/issues/2719202872/?environment=production&project=1429550&referrer=alert_email

(cc @LeSim)

**Comment by tchak** [comment]
done
