### ISSUE TITLE
ETQ administrateur, je souhaite que les vérifications de liens du bouton MonAvis soient à jour

### ISSUE THREAD

**Issue by VPzt** [demarches-simplifiees/demarches-simplifiees.fr#6771]
Les liens du bouton MonAvis générés sur observatoire.numerique.gouv.fr ne sont plus en monavis.numerique.gouv.fr mais en voxusagers.numerique.gouv.fr, et la vérification automatique de Démarches-Simplifiées n'accepte que monavis.numerique.gouv.fr.

Pouvez-vous mettre à jour la vérification du lien afin que l’URL correcte puisse être entrée?

**Comment by tchak** [comment]
done
