### ISSUE TITLE
ETQ Usager, je voudrais que les l'ordre des mois sur le tableau des statistique soit juste

### ISSUE THREAD

**Issue by emsnytech** [demarches-simplifiees/demarches-simplifiees.fr#6823]
![Capture d’écran 2022-01-19 à 10 30 30](https://user-images.githubusercontent.com/27733126/150102800-492eba84-3c87-4bfd-a396-644c3f623c6b.png)

Septembre après décembre... oui... mais aussi près ;-)

**Comment by mfo** [comment]
je pense que ce n'est plus un problème non ? cf: https://www.demarches-simplifiees.fr/stats
