### ISSUE TITLE
Infraction Rubocop `Lint/RedundantCopEnableDirective`

### ISSUE THREAD

**Issue by akarzim** [demarches-simplifiees/demarches-simplifiees.fr#6869]
# Résumé

Correction automatique de l'infraction Rubocop `Lint/RedundantCopEnableDirective`.

mots-clés : offence, rubocop

# Actuellement

Deux infractions à la règle `Lint/RedundantCopEnableDirective` sont détectées par la version 1.10.0 de Rubocop.

# Comportement attendu

Aucune infraction aux règles de Rubocop ne devrait être constaté.

# Proposition

Corriger l'infraction en supprimant les commentaires magiques dans le code.
	
```ruby
# rubocop:disable Style/HashTransformValues
# rubocop:enable Style/HashTransformValues 
```
	
--- 

voir : PR à venir / @adullact & @synbioz

> - L'ADULLACT a mandaté le prestataire @synbioz pour développer plusieurs fonctionnalités (tickets et PR à venir).
> - C'est dans ce cadre que @synbioz nous propose certains correctifs annexes comme celui-ci.
> - Si c'est nécessaire, @akarzim et @jobygoude de @synbioz pourront interagir avec l'équipe @betagouv sur ce ticket et sur la PR (répondre aux commentaires, pousser des commits…).

---

`trackingAdullactContrib`

**Comment by tchak** [comment]
done
