### ISSUE TITLE
Améliorer le rebase des dossiers

### ISSUE THREAD

**Issue by tchak** [demarches-simplifiees/demarches-simplifiees.fr#6962]
# Améliorer le rebase des dossiers

## État des lieux
On appelle le "rebase" le fait d'appliquer les changements d'une révision à un dossier.

Aujourd'hui, le rebase n'est appliquée que sur les dossiers en brouillon. On voudrait idéalement l'étendre à d'autres états. Je repense aux discussions que nous avons eues autour des revisions : nous avons parlé du fait que certains changements n'ont pas besoin d'être revisés. Je suis d'accord avec ça, mais j'ai toujours défendu que ce soit plus simple d'avoir un seul système du moins du point de vue de l'implémentation. Maintenant que nous avons les révisions en place, je pense qu'on peut facilement faire le trie des opérations qui peuvent être appliquées sans perte d'informations ou de sens.

## L’objectif du système
* les dossiers traités sont figés et ne sont changés sous aucun prétexte.
* les dossiers en instruction restent stables, mais on peut modifier les documents en relation avec le traitement (attestation/emails)
* les dossiers en construction peuvent continuer à évoluer, mais sans surprises pour l’usager

## Proposition

Cette fonctionnalité aura un grand impact sur le confort des administrateurs et instructeurs. J'espère qu’elle résoudra une grande partie de la friction avec les revisions de manière transparente pour les usagers ! Pour les cas qui restent, je vais faire une autre issue pour proposer une gestion explicite des conflits.

### brouillon
- toutes les opérations peuvent être appliquées. En cas de changement de type de champ, la valeur du champ est nullifiée. (implémenté)

### en construction
- on peut appliquer la suppression des champs
- on peut appliquer le changement des libelles et de la description. Aujourd'hui, on surligne les champs qui ont changé dans l'interface. Je pense que pour les dossiers en construction on peut faire mieux et envoyer une notification à l'usager pour signaler le changement de libelle et description.
- on peut ajouter des options des menus déroulants
- on peut supprimer des options des menus déroulants du moment qu'elles ne sont pas sélectionnées
- on peut modifier les couches de la cartographie sélectionnées
- on peut rendre un champ obligatoire optionnel
- on peut appliquer les changements sur le modèle d’attestation et les email de notification peuvent être appliqués automatiquement si pas de conflit sur les tags utilisés. C’est facilement vérifiable au moment du rebase.

### en instruction
- seuls les changements sur le modèle d’attestation et les email de notification peuvent être appliqués automatiquement. Nous avons la garantie que s’il n’y a pas de changements sur les champs, les templates sont toujours valides.

## Pour aller plus loins

On peut aussi proposer aux instructeurs d'appliquer le rebase lors du retour sur les états : par exemple, on peut appliquer le rebase lorsqu’un dossier repasse en construction. Bonus si on peut unifier le email de notification dans ce cas là. "Votre dossier est repassé en construction et les libellés des champs suivants ont été modifiés" 🎉 

## Les difficultés

Ça peut paraitre compliqué, mais en vrai ça s’implémente bien. C’est un moteur de règles sur une liste d’opérations – ça se lit bien et ça se teste très bien.

**Comment by kemenaran** [comment]
Merci pour la description détaillée ❤️ 

Pour ma part ça me semble bien de pouvoir modifier les templates d'emails et d'attestation des dossiers en instruction 👍 

Après pour la modification des champs de dossiers en instruction, je suis plus sceptique. J'ai l'impression que ça serait de la complexité pour des cas d'usages relativement rares. Et aussi que ça casse le modèle mental de _"Une fois que j'ai envoyé mon dossier à l'administration, bin le formulaire ne change plus."_

Et surtout je me demande **comment présenter ces règles à l'administrateur** : j'imagine qu'il faudrait, dans la fenêtre de publication, dire "Les modifications suivantes seront appliquées à N dossiers en brouillon : … ; les modifications suivantes seront appliquées à M dossiers en instruction : …", etc. Et puis faudrait que ça soit clair pour les devs, dans le code et les specs, aussi… Tu crois que ça vaut la peine ?

**Comment by tchak** [comment]
> Après pour la modification des champs de dossiers en instruction, je suis plus sceptique.
Dans ma proposition j'interdit explicitement les rebases avec des changement de champs sur les dossiers en instruction. Tu parle de la partie "proposer un rebase lors des retours sur un état" ?

**Comment by kemenaran** [comment]
Ah pardon, non, je voulais dire "Pour la modification des champs de dossiers en **construction**"

**Comment by tchak** [comment]
> Ah pardon, non, je voulais dire "Pour la modification des champs de dossiers en construction"

Je suis OK pour attendre avec ça. Mais c'est déjà demandé au support. Et je soupçonne que ça va arriver de plus en plus avec l'ouverture des dossiers pour tout le monde. Certaines opérations sont très courantes en post publication – correction d'une typo, ajout d'une option dans une liste d'options, etc.

**Comment by mfo** [comment]
top pour tout ce qui va jusqu'en construction. en revanche j'ai une crainte sur les dossiers en instruction.

Peux-tu clarifier :
> les dossiers en instruction restent stables, mais on peut modifier les documents en relation avec le traitement (attestation/emails)

Quand tu dit, "on peut modifier", de qui parles tu ? 

J'ai l'impression que l'administrateur s'occupe des mails/templates. Alors que l'instructeur les "délivre" (par changement d'état). 

> seuls les changements sur le modèle d’attestation et les email de notification peuvent être appliqués automatiquement. Nous avons la garantie que s’il n’y a pas de changements sur les champs, les templates sont toujours valides.

J'aime l'idée d'une approche automatique cf idée de pierre.

Mais si on en fait qqch d'**infléxible**, j'ai peur que ça deviennent bloquant pour l'instructeur. La decision de rebase me semble être aussi portée par l'instructeur exemple : en acceptant le dossier XXX ; je veux delivrer l'attestation X ou Y (genre attestation 2020 ou 2021) ? donc sur la question de l'interface de gestion des "conflits" (ou pas) ; c'est peut être portée par l'instructeur ; en gros, il doit pouvoir rebase si il le doit (voir repasser en construction pour debloquer le truc).
