### ISSUE TITLE
Cette démarche en ligne a été close, il n’est plus possible de déposer de dossier pour le 94

### ISSUE THREAD

**Issue by gaetangr** [demarches-simplifiees/demarches-simplifiees.fr#7007]
**Décrivez le bug**
La démarche suivante doit nous aider à récupérer le NEPH : https://www.demarches-simplifiees.fr/commencer/neph94, mais le message suivant apparait : "Cette démarche en ligne a été close, il n’est plus possible de déposer de dossier."

Ce lien est pourtant communiqué par les auto-écoles et sur votre site https://doc.demarches-simplifiees.fr/listes-des-demarches/demarches-relatives-au-permis-de-conduire

Les autres liens fonctionnent parfaitement, mais cela n'est pas utile pour les habitants du 94, **le lien est probablement cassé**

**Reproduction**
Comment reproduire le problème :
1. Aller sur la page https://doc.demarches-simplifiees.fr/listes-des-demarches/demarches-relatives-au-permis-de-conduire
2. Cliquez sur 94 Val de Marne dans cette catégorie : https://doc.demarches-simplifiees.fr/listes-des-demarches/demarches-relatives-au-permis-de-conduire#reactivation-ou-communication-du-n-neph-numero-denregistrement-prefectoral-harmonise-rectification-d
3. Une erreur apparaît

**Comportement attendu**
Le site aurait du m'inviter à compléter les démarches comme pour les autres départements

**Appareil et navigateur utilisé**
 - Appareil : [PC, Mac, iPhone]
 - Navigateur : [Chrome, Safari]

**Comment by tchak** [comment]
done
