### ISSUE TITLE
ETQ super-admin - Le fichier de statistiques n'est pas un .csv, mais un fichier Excel (.xlsx)

### ISSUE THREAD

**Issue by dzc34** [demarches-simplifiees/demarches-simplifiees.fr#7040]
## Résumé

Le fichier de statistiques `statistiques.csv`, consultable uniquement par un **super-admin**  via un bouton présent sur la page `/stats`, n'est pas un fichier **.csv**, mais un fichier Excel (**.xlsx**).

## Capture d'écran

![Screenshot 2022-03-15 at 04-47-30 Statistiques · demarches adullact org](https://user-images.githubusercontent.com/6709977/158302373-87c5a4f6-fb44-4417-b093-27fafb71649c.png)

## Reproduction
Comment reproduire le problème :
1. ETQ super-admin sur cette page `https://ds.example.org/stats`
2. Cliquer sur le lien "**Télécharger les statistiques (CSV)**" qui a pour URL :  `https://ds.example.org/stats/download.csv`
3. Pour consulter le fichier téléchargé (**statistiques.csv**), il faut changer l'extension car ce n'est pas un fichier CSV, mais un fichier Excel **.xlsx**.

## Comportement attendu

Option 1 - Télécharger un vrai fichier CSV
1. ETQ super-admin sur cette page `https://ds.example.org/stats`
2. Cliquer sur le lien "**Télécharger les statistiques (CSV)**" qui a pour URL :  `https://ds.example.org/stats/download.csv`
3. Le fichier téléchargé (**statistiques.csv**) est bien un fichier **.csv**

Option 2 - Télécharger un vrai fichier Excel
1. ETQ super-admin sur cette page `https://ds.example.org/stats`
2. Cliquer sur le lien "**Télécharger les statistiques (.xlsx)**" qui a pour URL :  `https://ds.example.org/stats/download.xlsx`
3. Le fichier téléchargé (**statistiques.xlsx**) est bien un fichier **.xlsx**

## Code 

[app/views/stats/index.html.haml](https://github.com/betagouv/demarches-simplifiees.fr/blob/main/app/views/stats/index.html.haml#L80)
```ruby
  - if super_admin_signed_in?
    %h2.new-h2 Téléchargement

    = link_to "Télécharger les statistiques (CSV)", stats_download_path(format: :csv), class: 'button secondary'
```

 [app/controllers/stats_controller.rb](https://github.com/betagouv/demarches-simplifiees.fr/blob/main/app/controllers/stats_controller.rb#L67)
```ruby
  def download
    headers = [
      'ID du dossier',
      'ID de la démarche',
      'Nom de la démarche',
      'ID utilisateur',
      'Etat du fichier',
      'Durée en brouillon',
      'Durée en construction',
      'Durée en instruction'
    ]
   ...
    respond_to do |format|
      format.csv { send_data(SpreadsheetArchitect.to_xlsx(headers: headers, data: data), filename: "statistiques.csv") }
    end
  end
```

---------------------
> `trackingAdullactContrib`  `trackingAdullactBugReport`

**Comment by tchak** [comment]
🤦‍♂️
