### ISSUE TITLE
ETQ Instructeur, je veux trier mes dossiers par notifications

### ISSUE THREAD

**Issue by LeSim** [demarches-simplifiees/demarches-simplifiees.fr#7066]
Nous avons eu plusieurs retours instructeur expliquant qu'il leur était pénible de parcours toutes les pages des dossiers suivis pour trouver ceux qui comportaient des notifications.

Or, leur tableau de bord leur permette de trier les dossiers en affichant ceux qui ont des notifications en premiers.

![Screenshot 2022-03-18 at 15-08-47 une bien belle procédure · demarches-simplifiees fr](https://user-images.githubusercontent.com/907405/159018488-b4bdd470-f0f7-44d5-9c14-f0809f2bee5f.png)

Ce bouton est incompréhensible, la fonction n'est pas utilisée.

On cherche une meilleure UX.

**Comment by Olivier-Marcellin** [comment]
Seul les administrateurs peuvent télécharger tous les dossiers, c'est une manière de les responsabiliser (selon Philippe)

**Comment by mfo** [comment]
ca a ete traité ca je ferme
