### ISSUE TITLE
ETQ usager le format du contenu des champs de type Zone de texte n'est pas reproduit dans les mails d'accusé de réception

### ISSUE THREAD

**Issue by AurelienDNUM** [demarches-simplifiees/demarches-simplifiees.fr#7080]
**Décrivez le bug**
Lorsqu'un usager renseigne un champ de type "Zone de texte" incluant des retours à la ligne, ceux-ci ne sont pas reproduits lors de l'intégration de ce champ dans un mail d'accusé de réception.
Les retours à la ligne sont bien reproduits dans la consultation du dossier.

**Reproduction**
Comment reproduire le problème :
1. Renseigner une démarche contenant un champ "Zone de texte" et envoyant un accusé de réception par mail comprenant le champ, avec le texte suivant :

> Ligne 1
> Ligne 2

2. Consulter l'accusé de réception.

**Comportement attendu**
L'accusé de réception devrait afficher le texte :

> Ligne 1
> Ligne 2

Or, celui-ci affiche :

> Ligne 1Ligne 2

**Comment by tchak** [comment]
double
