### ISSUE TITLE
ETQ ApiEntreprise ; j'aimerais que DS fasse appel aux API en utilisant le param recipient (qui prend siren/siret) 

### ISSUE THREAD

**Issue by mfo** [demarches-simplifiees/demarches-simplifiees.fr#7187]
merci pour vos retours @Haelle / @dzc34  / @emsnytech

**Comment by Haelle** [comment]
Tous les appels à API Entreprise doivent renseigner le query param `recipient`, qui est sensé indiquer quel est le bénéficiaire de l'appel.

Aujourd'hui c'est systématiquement renseigné avec le siren/siret de l'entreprise pour laquelle les données sont demandées (param = recipient). Alors que c'est sensé être le siren/siret du propriétaire de la démarche liée.

- [ ] À court terme il vaut mieux systématiquement mettre le SIRET de la DINUM.
- [ ] À moyen terme il faut renseigner le SIREN/SIRET de l'administration propriétaire de la démarche (mais vous ne l'avez pas aujourd'hui, on a regardé votre code pour faire la PR nous même !)

**Comment by dzc34** [comment]
> À court terme il vaut mieux systématiquement mettre le SIRET de la DINUM.

Pour les autres instances du logiciel DS, ce serait top que ce numéro de SIRET soit configurable pour permettre de l'associer au gestionnaire de l'instance. Exemple : l'instance DS Adullact a un jeton API Entreprise pour son instance, ce serait peut-être mieux que les appels à l'API Entreprise avec ce jeton-là soit associé à l'Adullact et pas à la DINUM.

**Comment by emsnytech** [comment]
Bonjour
Je ne crois pas que cela soit un bug.
En premier lieu en effet, chaque instance doit avoir son propre TOKEN, qui prend en compte un accès aux données publiques.
ce qui n'est pas normal... c'est que l'ADULLACT utilise notre token... (si c'est le cas, y a un pb ...)
Ensuite, dès qu'il faut d'autres données confidentielles, il faut passer par la procédure datapass, et obtenir un token spécifique qui est intégré dans le formulaire autorisé. Il n'y en a que 8 me semble t'il aujourd'hui.
Nous n'exigeons pas aux organismes public qui créent des formulaire de fournir le SIREN ( on avait cela au début, mais il y avalait trop d'erreurs) 
En tout cas, je vois que les principes émis il y a 5 ans lors de la création de l'API sont toujours là ! et le principe envoyé le SIREN du service bénéficiaire reste en effet la solution la plus facile ! 
Si on doit réintroduit le SIRET de l'organisme qui crée un formulaire... j'avoue ne pas être contre ! surtout que depuis un an on demande le siret à tous les administrateurs qui se crée  un compte !!! alors ils doivent maintenant le connaitre !
On en discute lors d'une prio..; et si vous faite la PR ... ;-)

**Comment by tchak** [comment]
done
