### ISSUE TITLE
En tant qu'administrateur je peux ajouter plusieurs pièces justificatives à un même champ

### ISSUE THREAD

**Issue by Olivier-Marcellin** [demarches-simplifiees/demarches-simplifiees.fr#7380]
Verbatim : « Ce qui nous pose problème ce sont les pièces ça c’est un vrai soucis la gestion des pièces, j’ai des métiers qui sont obligés de recréer des formulaires parce qu’il y a des pièces qui sont oubliées. Comme il n’y a pas de conditionnements, dans certains cas on est obligé soit de se dire tant pis je relancerai soi de créer un autre formulaire pour un besoin quasi identique mais pour rendre plus de champ obligatoire » […] « On est obligé nous de faire des faux champs pièces justificatives en non obligatoire pour leur donner cette possibilité […] et ça c’est quelque chose de assez récurrent […] après avec le bloc répétable c’est quelque chose qu’on peut faire (de rajouter des pièces justificatives), nous on a détourné le bloc répétable, j’ai mis un champ Pièces jointes dans un bloc répétable pour ajouter des pièces, on est obliger de trouver des astuces »

US : En tant qu'administrateur je peux ajouter plusieurs pièces justificatives à un même champ afin d'optimiser l'ajout des pièces côté usagers et limiter le nombre d'erreurs

Suggestions : modifier la fonction Pièces justificatives avec le paramètrage de plusieurs pièces

**Comment by tchak** [comment]
en cours
