### ISSUE TITLE
Bug d'affichage dans les listes déroulantes

### ISSUE THREAD

**Issue by Olivier-Marcellin** [demarches-simplifiees/demarches-simplifiees.fr#7389]
Les équipes admin du Ministère de la Culture rapportent un bug d'affichage dans les listes déroulantes

Priorité moyenne pour le Ministère de la Culture

Bug 

Des valeurs "vides" confusantes et sources d’erreur.

Constat également d'un manque de lisibilité

Un manque de guidage pour sélectionner les valeurs au sein des listes déroulantes.

Correction du bug et amélioration

• Corriger le bug de 'valeur vide" (qui n’apparaît a priori que pour les listes déroulantes
    lorsque le champ est obligatoire).
• Ajouter une incitation" Sélectionnez... " comme valeur par défaut.

Voir illustrations ci-dessous

<img width="1628" alt="Capture d’écran 2022-05-24 à 11 42 54" src="https://user-images.githubusercontent.com/101646817/170003372-5a5ad1cf-68bc-44bf-9d05-b874ad302868.png">

<img width="1625" alt="Capture d’écran 2022-05-24 à 11 49 15" src="https://user-images.githubusercontent.com/101646817/170003482-f6f42b97-fc68-4119-9d7e-44fe6d447292.png">

**Comment by colinux** [comment]
On re-précisera d'autres tickets avec les nouvelles maquettes
