### ISSUE TITLE
Supprimer le type de champ Engagement

### ISSUE THREAD

**Issue by Olivier-Marcellin** [demarches-simplifiees/demarches-simplifiees.fr#7390]
TL;DR 

Supprimer le type de champ Engagement :

- [ ] le retirer de la liste des types de champ disponible
- [ ] migrer tous les engagements existants vers une case a cocher
- [ ] supprimer tout le code relatif a engagement

Dans le détail 

Problème remonté par les équipes d'admin du Ministère de la Culture

Priorité faible pour le Ministère de la Culture

Constat

Actuellement 2 types de champs différents "Case à cocher" et "Engagement", alors qu’il s’agit du même type de champ.

Amélioration

Simplifier et rationnaliser la liste des types de champ en ne proposant qu’un seul type de champ "Case à cocher seule".

Voir l'illustration ci-dessous

<img width="1621" alt="Capture d’écran 2022-05-24 à 11 58 56" src="https://user-images.githubusercontent.com/101646817/170005630-2576c2b1-343c-41b8-b97b-54e3cd5b2d7e.png">

**Comment by tchak** [comment]
OUI ! On peut virer l'un des deux !
