### ISSUE TITLE
ETQ Usager, aucun bloc ne devrait s'afficher par défaut avec un bloc repetable *Optionnel*

### ISSUE THREAD

**Issue by maatinito** [demarches-simplifiees/demarches-simplifiees.fr#7482]
actuellement, DS affiche un bloc par défaut ce qui fait que les usagers qui lisend en diagonal sont tentés de remplir le champ avec n'importe quoi et il leur faut du temps pour comprendre qu'ils leur faut supprimer le bloc s'ils ne veulent pas remplir cette partie. 
Proposition: lorsque un bloc repetable est optionnel, aucun bloc n'est affiché par défaut. 

Corrolaire: Des retours au support semblait aussi indiquer que le bouton 'secondaire' 'Ajouter un élement' n'est pas suffisamment visible.  
Proposition: Mettre ce bouton en vert.

Actuellement dans DS: 
![bloc_repetable_DS](https://user-images.githubusercontent.com/15379878/174875664-9b48ed79-7344-4f78-9399-f7b3ef034b70.png)
Après:
![Bloc_repetable_MD](https://user-images.githubusercontent.com/15379878/174875680-c8bef128-42b7-42cb-8c61-3d2597202cca.png)

Notez que cela change pas mal de tests car la plupart des tests se basent sur le fait que le bloc existe par défaut. La solution est alors de faire en sorte que la factory crée un bloc mandatory par défaut.

**Comment by LeSim** [comment]
super issue, je suis chaud pour l'embarquer. @Olivier-Marcellin , notre UX préféré, t'en penses quoi ?

**Comment by maatinito** [comment]
Attention: je distingue deux cas. 
Bloc optionnel : l'usager arrive sur le formulaire. On a li'mage au dessus, le bouton est sous l'explication *car il n'y a pas de bloc encore créé'. 
Bloc obligatoire ou bloc déja créé par l'usager: le bouton est *sous* le bloc en cours. L'usager rempli le bloc puis voit le bouton permettant d'ajouter un élément.

**Comment by Olivier-Marcellin** [comment]
Ne faudrait-il pas plutôt avoir le bouton ajouter un élément au dessus du bloc en cours ? donc quelque soit le cas. J'ai un autre exemple Enfants du spectacle avec un nombre de champ de saisies dans le bloc bien plus grand le bouton est encore plus difficile à trouver… 

Pour le bouton vert, on va en discuter avec les équipes de design du système de l'État si possible de l'avoir.

**Comment by tchak** [comment]
done
