### ISSUE TITLE
ETQ super admin, je souhaiterai que METABASE soit actualisé 

### ISSUE THREAD

**Issue by emsnytech** [demarches-simplifiees/demarches-simplifiees.fr#7604]
METABASE n'a pas pu etre mis à jour depuis une semaine.
Cela peut poser un pb quand in va lancer le 1 Août la jointure vers Data.gouv

**Comment by kara22** [comment]
@emsnytech le lien avec Datagouv se fait directement depuis notre base de prod

**Comment by tchak** [comment]
done
