### ISSUE TITLE
ETQ d'administrateur je veux faire appliquer le règle du Silence vaut accord

### ISSUE THREAD

**Issue by emsnytech** [demarches-simplifiees/demarches-simplifiees.fr#7612]
Mettre un compteur derrière la date de passage en instruction pour appliquer la règle de Silence vaut accord.  
La règle est deux mois (qui peut varier par démarche, exemple pour les licences du spectacle c'est 30 jours...), 
Le dossier est automatiquement accepté après ce délais. 
https://www.service-public.fr/particuliers/vosdroits/R45345
Le délais se calcule au moment ou le dossier passé en instruction

**Comment by colinux** [comment]
fait il y a quelques mois
