### ISSUE TITLE
L’information du SIRET n’est pas toujours proprement affiché

### ISSUE THREAD

**Issue by emsnytech** [demarches-simplifiees/demarches-simplifiees.fr#7628]
Aujourd'hui, en rentrant un SIRET, les information sur la structures n'apparaissent pas forcément

Ex : SIRET 80258332800017

<img width="918" alt="Capture d’écran 2022-07-26 à 23 37 13" src="https://user-images.githubusercontent.com/27733126/181116727-922e02e4-4648-46de-a8af-29867287ff72.png">
Hors l'association existe bien 
https://annuaire-entreprises.data.gouv.fr/etablissement/80258332800017?redirected=1
autre cas 67203997101944
J'ai réussi à faire appaire une fois, il semble que ce soit l'enseigne qui apparaisse.
Mais cette infirmation n'est pas tout le temps renseignée.
ex ou cela a marché 
<img width="949" alt="Capture d’écran 2022-07-26 à 23 28 48" src="https://user-images.githubusercontent.com/27733126/181117633-b918f770-c5c1-496b-b77d-d5965a4b5584.png">

**Comment by tchak** [comment]
Ça n'a rien a voir avec les bloc repérables. Il y a un problem d'affichage d'information sur certains SIRET.

**Comment by emsnytech** [comment]
Bien donc le bug est Géneral sur le champ siret !
Bizarre que personne ne l'ai remonté

**Comment by colinux** [comment]
C'est peut-être lié au fait que l'API entreprise est perturbée depuis le 19/07, quasi inaccessible depuis le 25.
https://status.entreprise.api.gouv.fr/cl5ser1ft183444zpo893j2m2nt 

Actuellement on a 3200+ sirets en attente d'infos…
