### ISSUE TITLE
Email de suppression pas dutout rassurant

### ISSUE THREAD

**Issue by mfo** [demarches-simplifiees/demarches-simplifiees.fr#7688]
Est-il possible de désactiver le mail à destination des utilisateurs leur indiquant que le dossier va bientôt être supprimé?

Les 3/4 comprennent que c'est leurs dossiers de demande de logement qui va être supprimé et non pas leurs données hébergées pour 1 mois sur demarches-simplifiees.fr

Cela génère de grosses incompréhensions, créé du mécontentement et nous fait perdre un temps précieux.

**Comment by tchak** [comment]
Il faut peut être clarifier le message dans le email ?

**Comment by colinux** [comment]
@Olivier-Marcellin va se pencher dessus, et ensuite good first issue pour implémenter sa "solution"

**Comment by Olivier-Marcellin** [comment]
Voici les maquettes avec le wording corrigé pour les mails de relance de suppression de dossiers : https://www.figma.com/file/nPzTaQctXZN2t2Xu2MXAhP/Mail-de-suppression-de-dossiers?node-id=1%3A7
