### ISSUE TITLE
ETQ administrateur, je veux pouvoir bloquer le nombre de caractères dans un champ "texte"

### ISSUE THREAD

**Issue by Bouchralazaar** [demarches-simplifiees/demarches-simplifiees.fr#7739]
Il faudrait ouvrir la possibilité aux administrateurs de mettre un maximum de caractères dans un champ "texte" libre ou ligne de texte. 
En parallèle, il faudrait que l'usager sache au fur et à mesure le nombre de caractères qu'il renseigne.

**Comment by emsnytech** [comment]
Super !

**Comment by kara22** [comment]
@colinux je me mets dessus du coup

**Comment by colinux** [comment]
OK. On a pas mal affiné les besoins de première version au fil des semaines on pourra en parler si tu veux.
