### ISSUE TITLE
 Mise à niveau vers Rails 7.0

### ISSUE THREAD

**Issue by akarzim** [demarches-simplifiees/demarches-simplifiees.fr#7781]
Rails 7.0 est sortie le [15 décembre 2021][7.0] et a fait l'objet de [plusieurs][7.0.1] [patches][7.0.2] [depuis][7.0.3] [lors][7.0.4].

### Tâches

[7.0]: https://rubyonrails.org/2021/12/15/Rails-7-fulfilling-a-vision
[7.0.1]: https://rubyonrails.org/2022/1/6/Rails-7-0-1-has-been-released
[7.0.2]: https://rubyonrails.org/2022/2/8/Rails-7-0-2-has-been-released
[7.0.3]: https://rubyonrails.org/2022/5/9/Rails-7-0-3-6-1-6-6-0-5-and-5-2-8-have-been-released
[7.0.4]: https://rubyonrails.org/2022/9/9/Rails-7-0-4-6-1-7-6-0-6-have-been-released

- [x] Basculer sur le mode Zeitwerk 
- [ ] Mise à niveau vers Rails 6.1.7 (ou patch ultérieur)
- [ ] S'assurer que tous les tests passent
- [ ] Mise à niveau vers Rails 7.0.4 (ou patch ultérieur)
- [ ] S'assurer que tous les tests passent
- [ ] Faire une passe de [bundler-audit](https://rubygems.org/gems/bundler-audit)
- [ ] Appliquer les derniers patches des dépendances (`bundle update --patch --strict`)
- [ ] Tester l'application manuellement
- [ ] Déployer le passage à Rails 7

### Après la migration

- [ ] Passer de la config par défaut de Rails 6 à celle de Rails 7

## Actuellement

Rails 6.1

### avantages / inconvénients de garder cette version

Il n'existe pas réellement d'avantage à rester sur une ancienne version de Rails, au contraire, cela peut induire un certain nombre de risque du point de vue de la sécurité, et dans une moindre mesure, des performances. Par ailleurs, Rails 7.0, comme toute version majeure, apporte son lot de nouveautés et de petite améliorations qui simplifient la vie des équipe de développement, il serait dommage de s'en passer ;)

## Comportement attendu

Rails 7.0

### avantages / inconvénients de faire cette montée de version majeur

Cela a les avantages des inconvénients de la section précédente ;) En revanche, si je ne vois pas d'inconvénients directs à faire cette montée de version — qui soit dit en passant n'apporte pas de changements drastiques impliquant la réécriture d'une grande partie du code — je soupçonne d'éventuelles incompatibilités au niveau des dépendances. Concernant les dépendances Ruby, je vais faire le tour de celles-ci pour prendre la température ; pour les dépendances front, il pourrait y avoir un impact, mais c'est plus incertain. L'avis des équipes de la DINUM serait précieux ici, car elles ont bien plus d'expérience sur DS et ses dépendances que je ne pourrais en avoir !

### Compatibilité des gems

La grande majorité des gems sont compatibles, certaines nécessiteront une petite mise à jour : 
- deep_cloneable 3.0.0 -> 3.2.0
- delayed_cron_job 0.7.4 -> 0.9.0
- delayed_job 4.1.9 -> 4.1.10

![Screenshot 2022-09-23 at 09-30-32 RailsBump](https://user-images.githubusercontent.com/130560/191971343-220efa43-d5b3-4af3-8697-6e762cb1565c.png)

Note: `delayed_job_active_record` est un faux négatif, la gem semble ne présenter aucune incompatibilité avec Rails 7.0.

### Ressources 

- https://guides.rubyonrails.org/upgrading_ruby_on_rails.html
- https://edgeguides.rubyonrails.org/7_0_release_notes.html
- https://railsbump.org/lockfiles/325727d2421d2b117009b81afcb26a6b43ad5d8f

**Comment by dzc34** [comment]
Cadre de cette contribution :
> - L'ADULLACT est intéressé pour proposer cette évolution sur son instance DS. 
> - Notre souhait est d'intégrer cette évolution sous forme de contribution au code source du logiciel DS. 
> - Nous avons mandaté le prestataire @synbioz pour développer cette évolution dans l'optique d'une contribution. 
> - Si c'est nécessaire, @akarzim et @jobygoude de @synbioz pourront interagir avec l'équipe `betagouv` sur ce ticket et sur les PRs (répondre aux commentaires, pousser des correctifs, ...).


[Ressource Adullact sur cette fonctionnalité](https://gitlab.adullact.net/demarches-simplifiees/evolution-du-logiciel-demarches-simplifiees/-/issues/34)

--------------------
> `trackingAdullactContrib`  `trackingAdullactARNiaContrib `

**Comment by dzc34** [comment]
@tchak @krichtof ticket complété

**Comment by dzc34** [comment]
Réunion de cadrage du **26/09/2022** entre équipe DS, Synbioz et l'Adullact

> L'équipe DS est Ok pour cette évolution : 
> il faudra le faire, donc si quelqu'un s'en charge c'est top.

/cc @krichtof @tchak @akarzim @emsnytech

**Comment by dzc34** [comment]
pour info #8329 "Remplacer l'implémentation custom des cookies CSRF par l'implem de Rails 7.1"

**Comment by Bounga** [comment]
Bonjour, j'ai fait le nécessaire pour passer à Rails 7.0.4.2. Les travaux sont visibles ici : https://github.com/adullact/demarches-simplifiees.fr/pull/58 si vous voulez y jeter un coup d'œil. J'ai fait en sorte de ne bumper que le strict minimum et modifier un minimum de code pour que tous les tests passent.

**Comment by dzc34** [comment]
Bonjour @Bounga 

> j'ai fait le nécessaire pour passer à Rails 7.0.4.2. Les travaux sont visibles ici : https://github.com/adullact/demarches-simplifiees.fr/pull/58 si vous voulez y jeter un coup d'œil. J'ai fait en sorte de ne bumper que le strict minimum et modifier un minimum de code pour que tous les tests passent.

Est-il possible dans ce type de cas, de faire les actions suivantes ?
- mettre à jour la branche **main** du dépôt de d'Adullact pour être synchro avec la branche `main` du dépôt de la DINUM. (je viens de le faire)
- rebaser la branche de travail (ici : `feat/rails-7`, le rebase automatique ne semble pas possible)  
- attendre que la CI finisse sans erreur :hourglass_flowing_sand:   
- si tu penses que la PR #/8736 est prête pour relecture :
  - retirer le status draft
  - si c'est pertinent compléter la description de la PR
  - ajouter ton commentaire (invitation à relecture) dans cette PR, car l'équipe DS est plus réactif aux commentaires dans les PR que dans les tickets. 
  
  Le découpage par commit est propre, cela facilitera le travail des relecteurs. :+1: 
  
  (pour info. : @cmayran)

**Comment by Bounga** [comment]
@dzc34 Ok je vais m'occuper du rebase début de semaine prochaine, un rebase automatique ne fonctionnera pas c'est sûr vu les changements apportés.

Dès que la CI est au vert je dé-draft et je mettrais un commentaire pour demande de relecture directement en commentaire de la PR.

**Comment by dzc34** [comment]
@tchak @colinux @krichtof @LeSim
ce ticket peut être clôturé ?
