### ISSUE TITLE
Instructeur – Pouvoir générer une attestation en PDF (sans envoi à l’usager)

### ISSUE THREAD

**Issue by Yoann-Magnin** [demarches-simplifiees/demarches-simplifiees.fr#7792]
Certains formulaires sont définis à l’échelle nationale et sont instruits dans chaque département.
Pour l’attestation, chaque département a un tampon différent.
Dans ce cas, il est donc impossible d’automatiser les attestations simplement à cause du tampon.

Cela représente une vraie perte de temps pour les services.
Ils doivent faire une série de copier/coller à partir des champs du formulaire, pour rédiger chaque attestation et ils ne peuvent pas bénéficier d’une fonctionnalité précieuse de DS.

LA SUGGESTION : permettre à l’instructeur de télécharger en PDF un modèle d’attestation, avec tous les champs complétés sauf le tampon.
Ainsi, l’instructeur n’aurait plus qu’à ajouter le tampon puis à l’envoyer à l’usager.

POUR CELA :
On pourrait imaginer une action à ajouter dans la liste des dossier traité, pour les dossiers acceptés.
Actions > Télécharger un modèle d’attestation.

![image](https://user-images.githubusercontent.com/111996289/191528573-0b17df33-c938-441c-84c6-4034e4f5531a.png)

**Comment by emsnytech** [comment]
Oups... 
Cela veut dire rescanner le documents
PB ...
Juridiquement... on perd l'opposabilité du document... 
A discuter

**Comment by guillaumelevieux** [comment]
@emsnytech bien sûr nous voudrions éviter ça.
Hypothèse : ajouter des attributs aux groupes instructeurs (Marianne, tampon, champs téléphone, contact mail, adresse du service) ?

**Comment by colinux** [comment]
Solution implémentée il y a quelques mois : les groups d'instructeurs peuvent avoir leur propre signature/tampon
