### ISSUE TITLE
ETQ super-admin, déléguer la création des comptes administrateurs (nouveau profil "gestionnaire de groupe et d’administrateurs")

### ISSUE THREAD

**Issue by dzc34** [demarches-simplifiees/demarches-simplifiees.fr#7804]
## Résumé

ETQ super-admin, déléguer la création des comptes administrateurs (nouveau profil "gestionnaire de groupe et d’administrateurs")

## Cadre de cette contribution

> - L'ADULLACT est intéressé pour proposer cette évolution sur son instance DS. 
> - Notre souhait est d'intégrer cette fonctionnalité sous forme de contribution au code source du logiciel DS. 
> - Nous avons mandaté le prestataire @synbioz pour développer cette fonctionnalité dans l'optique d'une contribution. 
> - Si c'est nécessaire, @akarzim et @jobygoude de @synbioz pourront interagir avec l'équipe `betagouv` sur ce ticket et sur les PRs (répondre aux commentaires, pousser des correctifs, ...).

[Ressource Adullact sur cette fonctionnalité](https://gitlab.adullact.net/demarches-simplifiees/evolution-du-logiciel-demarches-simplifiees/-/issues/23)

## Demande initiale

expression de besoin initiale par l'**Adullact** :
[ticket Github #6587](https://github.com/betagouv/demarches-simplifiees.fr/issues/6587)  ---> remplacé par ce ticket

reformulation :
> ETQ super-admin, déléguer la création des comptes administrateurs (nouveau profil "gestionnaire de groupe et d’administrateurs")

## Contexte

> La notion d'administrateur de groupe recoupe celle de zones. Il convient d'en définir les contours et d'établir dans quelle mesure nous pouvons mutualiser nos efforts pour aboutir à un fonctionnel qui satisfasse toutes les parties.

Lors d'un échange avec l'équipe DS (04/05/2022), nous avons identifié que c'était 2 concepts fonctionnels très différents :

Les **zones** 
- s'appliquent aux démarches
- une zone regroupe différentes démarches à des fins de reporting.
- Exemple : 
  - la zone *Ministère de la Culture* regroupe toutes les démarches qui seront facturées au dit ministère
  - afficher des stats sur les démarches de mon ministère (décideurs)
  - ...

Les **groupe** d'administrateurs et **gestionnaire** d'administrateurs 
- s'appliquent aux administrateurs 
- un groupe d'administrateurs et son gestionnaire permet de déléguer les habilitations de gestion des administrateurs 
- un gestionnaire de groupe peut créer des administrateurs associés à son groupe 
- un gestionnaire de groupe peut aussi créer un sous-groupe avec un gestionnaire dédié afin de déléguer les habilitations de gestion des administrateurs pour ce sous-groupe.
- Exemple : 
  - le super-admin créer un gestionnaire  d'administrateurs pour le mutualisant AMUE associé à un groupe AMUE
  - le gestionnaire  d'administrateurs de l'AMUE peut créer des administrateurs associés à ce groupe AMUE
  - le gestionnaire  d'administrateurs de l'AMUE peut créer des sous-groupes par université et y associer un gestionnaire  d'administrateurs.
  - ...

Suite à cet échange, nous avions prévu les étapes suivantes, mais nous avons pris du retard :
1. rédiger en amont l'expression de besoin **fonctionnelle** (en français), d'abord un ou deux paragraphes et ensuite des User Stories
2. organiser une séance de conception à 3 (Adullact, Dinum, Synbioz)

Par rapport, au cahier des charges décrit dans le [ticket Github #6587](https://github.com/betagouv/demarches-simplifiees.fr/issues/6587), voici les changements :
- wording du même concept : le "_Gestionnaire et groupe d'administrateurs_" remplace "_~~admin de groupe~~_".
- ajout d'une notion de profondeur infinie (hiérarchie de groupe).

--------------------
> `trackingAdullactContrib`  `trackingAdullactARNiaContrib `

**Comment by dzc34** [comment]
Avec un peu de retard, le résumé de la réunion de cadrage du **26/09/2022** 
entre équipe DS (@emsnytech @krichtof @tchak), Synbioz (@akarzim)  et l'Adullact (@dzc34).

- L'équipe DS est toujours Ok pour cette fonctionnalité.
- L'Adullact doit rédiger les user-stories et planifier une réunion avec l'équipe DS pour les vérifier ensemble.

**Comment by dzc34** [comment]
remarques de @akarzim

> > les groupes sont organisés de manière hiérarchique sans limite de profondeur
> 
> Il serait intéressant de discuter avec la DINUM de la pertinence d'activer l'extension [ltree] de PostgreSQL pour le requêtage en profondeur dans une arborescence. Les [avantages de cette extension][manipulate] sont multiples : calcul du nombre d'enfants, déplacement d'une branche (réaffecter un sous-groupe et tous ses descendants à un autre groupe parent), suppression d'une branche (suppression d'un sous-groupe et de tous ses descendants), etc.
> 
> Une autre option serait de faire des [requêtes récursives][with] à l'aide de `WITH RECURSIVE`.
> 
> [ltree]: https://www.postgresql.org/docs/current/ltree.html
> [with]: https://www.postgresql.org/docs/current/queries-with.html#QUERIES-WITH-RECURSIVE
> [manipulate]: https://patshaughnessy.net/2017/12/14/manipulating-trees-using-sql-and-the-postgres-ltree-extension

**Comment by cmayran** [comment]
à cloturer au profit de la #9111
