### ISSUE TITLE
ETQ superadmin, masquer une démarche de la liste des modèles proposés à la création d'une nouvelle démarche

### ISSUE THREAD

**Issue by dzc34** [demarches-simplifiees/demarches-simplifiees.fr#7806]
## Résumé

ETQ superadmin, masquer une démarche   de la liste des modèles proposés à la création d'une nouvelle démarche

## Cadre de cette contribution

> - L'ADULLACT est intéressé pour proposer cette évolution sur son instance DS. 
> - Notre souhait est d'intégrer cette fonctionnalité sous forme de contribution au code source du logiciel DS. 
> - Nous avons mandaté le prestataire @synbioz pour développer cette fonctionnalité dans l'optique d'une contribution. 
> - Si c'est nécessaire, @akarzim et @jobygoude de @synbioz pourront interagir avec l'équipe `betagouv` sur ce ticket et sur les PRs (répondre aux commentaires, pousser des correctifs, ...).

[Ressource Adullact sur cette fonctionnalité](https://gitlab.adullact.net/demarches-simplifiees/evolution-du-logiciel-demarches-simplifiees/-/issues/6)

## Contexte

* Toutes les démarches de + 30 dossiers sont affichées à tous les **administrateurs** dans `/admin/procedures/new_from_existing` (accessible via le bouton `Nouvelle Démarche` disponible sur l'URL `/admin/procedures`) ;
* Certaines de ces démarches (le plus souvent clôturées) ne sont pas carrées d'un point vue RGPD (utilisation des données d'une façon non conforme, exemple : numéro de Sécurité Sociale des  parents pour l'inscription à la cantine de l'enfant), et le super-admin devrait pouvoir interdire leur affichage à cet endroit (pour éviter de reproduire ces utilisations non conformes).

![Screenshot 2022-09-26 at 13-04-12 demarches-simplifiees fr](https://user-images.githubusercontent.com/6709977/192263954-4e65b8a8-26d4-4a60-aecd-d33d9c55b5fb.png)

### User story

> Format : “En tant que” (ETQ), “je souhaite”, “afin de”

```
ETQ super-admin, 
Je souhaite, masquer une démarche de la liste 
             des modèles proposés à la création d'une nouvelle démarche

Afin de      limiter le partage (via le bouton "cloner") 
             de démarches problématiques d'un point vu RGPD 
```

### Tests d'acceptation

> Format : “En tant que” (ETQ), “Quand je”, “Alors”

```gherkin
ETQ administrateur
Quand je consulte la page "Créer une nouvelle démarche à partir d’une démarche existante" (1) 
Alors je ne vois pas les démarches masquées par le superadmin
```

(1) `/admin/procedures/new_from_existing`

> **TODO** super-admin : 
> - UX - Wording à faire pour les boutons "interdire l'affichage dans les modèles" et "dé-masquer comme modèle"
> - UX - Autre option à étudier : remplacer les boutons par une checkbox 

```gherkin
ETQ super-admin 
Quand je consulte une nouvelle démarche dans le manager (2)
Alors un bouton "interdire l'affichage dans les modèles" est présent
```

```gherkin
ETQ super-admin
Quand je consulte une démarche dans le manager (2) qui n'est pas masqué
Alors un bouton "interdire l'affichage dans les modèles" est présent
```

```gherkin
ETQ super-admin
Quand je consulte une démarche dans le manager (2)  qui est déjà masqué
Alors un bouton "autoriser l'affichage dans les modèles" est présent
```

```gherkin
ETQ super-admin
Quand je clique sur le bouton "interdire l'affichage dans les modèles" (2)  d'une démarche qui n'est pas masqué 
Alors le bouton "autoriser l'affichage dans les modèles" est présent et remplace le bouton "interdire ..."
```

```gherkin
ETQ super-admin
Quand je clique sur le bouton "autoriser l'affichage dans les modèles" (2) d'une démarche qui est masqué 
Alors le bouton "interdire l'affichage dans les modèles" est présent et remplace le bouton "autoriser ..."
```

(2) `/manager/procedures/<idProcedure>`

--------------------
> `trackingAdullactContrib`  `trackingAdullactARNiaContrib `

**Comment by dzc34** [comment]
@tchak @krichtof ticket complété

**Comment by krichtof** [comment]
Merci pour la clarté de l'US.
C'est ok pour moi :)

**Comment by dzc34** [comment]
Avec un peu de retard, le résumé de la réunion de cadrage du **26/09/2022** 
entre équipe DS (@emsnytech @krichtof @tchak), Synbioz (@akarzim)  et l'Adullact (@dzc34).

- L'équipe DS est Ok pour cette fonctionnalité.
- 2 autres fonctionnalités ont été évoquées par l'équipe DS, mais le scope est différent et elles seront traitées dans des tickets dédiés.
  - ETQ adminstrateur, mettre en avant ma démarche dans la liste des modèles de démarches (souvent demandé)
  - ETQ adminstrateur, masquer ma démarche dans la liste des modèles de démarches

**Comment by dzc34** [comment]
remarques de @akarzim

> J'ai creusé le sujet et joué un peu avec GraphQL, il semblerait que tout soit en place de ce côté pour extraire au format JSON les données concernant les démarches. L'export pourrait ainsi se baser sur la déclaration GraphQL pour générer un fichier JSON téléchargeable par l'administrateur.
> 
> Pour être cohérent avec ce qui a été fait pour publier en OpenData les démarches publiques, le fichier ainsi généré pourrait s'inspirer de la requête GraphQL faite par le service `DemarchesPubliquesExportService`, et être retourné gzippé à l'administrateur. Ainsi, la fonctionnalité d'import pourrait indifféremment importer une démarche exportée par un administrateur ou une démarche publique récupérée depuis https://www.data.gouv.fr.

**Comment by cmayran** [comment]
## Cahier des charges

### User story

> Format : “En tant que” (ETQ), “je souhaite”, “afin de”

```
ETQ super-admin, 
Je souhaite, masquer une démarche de la liste 
             des modèles proposés à la création d'une nouvelle démarche

Afin de      limiter le partage (via le bouton "cloner") 
             de démarches problématiques d'un point vu RGPD
             
```

```
ETQ administrateur, 
Je ne vois pas les démarches masquées par le super admin dans la liste des modèles proposés à la création d'une nouvelle démarche
Afin de ne pas utiliser une démarche qui serait problématique d'un point de vue RGPD
```

### US 1. Tests d'acceptation ETQ Administrateur

#### US 1.2 ETQ administrateur utiliser un modèle à partir d'une démarche existante

```gherkin
ETQ administrateur
Quand je consulte la page "Créer une nouvelle démarche à partir d’une démarche existante" (1) 
Alors je ne vois pas les démarches masquées par le superadmin
```
(1) `/admin/procedures/new_from_existing`

#### 1.2 ETQ administrateur à partir de la page toutes les démarches

```gherkin
ETQ administrateur
Quand je consulte la page "Toutes les démarches" (2)
Alors je ne vois pas les démarches masquées par le superadmin
```
(2) `/admin/procedures/all`  (voir DS.fr)

### US 2. Tests d'acceptation ETQ super admin

> **TODO** super-admin : 
> - UX - Wording à faire pour les boutons "interdire l'affichage dans les modèles" et "dé-masquer comme modèle"
> - UX - Autre option à étudier : remplacer les boutons par une checkbox 

#### US 2.1 masquer l'affichage d'une démarche dans les modèles

```gherkin
ETQ super-admin 
Quand je consulte une démarche dans le manager (2)
* Alors un bouton "**masquer** l'affichage dans les modèles" est présent
* Le bouton **autoriser** est masqué
```
(2) `/manager/procedures/<idProcedure>`

#### US 2.2 autoriser l'affichage d'une démarche dans les modèles

```gherkin
ETQ super-admin
Quand je consulte une démarche dans le manager (2)  qui est déjà masqué
Alors 
* un bouton "**autoriser** l'affichage dans les modèles" est présent
* Le bouton ** masqué** n'apparait pas
```

(2) `/manager/procedures/<idProcedure>`
