### ISSUE TITLE
ETQ Administrateur, je ne peux pas activer le routage sans groupe

### ISSUE THREAD

**Issue by LeSim** [demarches-simplifiees/demarches-simplifiees.fr#7807]
- routage s'il y a plus d'un groupe
- label obligatoire

TL;DR :

https://secure.helpscout.net/conversation/2017952482/1990961?folderId=1653799

`il y a un champs sans label en haut, faut qu'elle selectionne le default`
`effectivement l'admin a activé le routage sans groupe`

<img width="1167" alt="Screen Shot 2022-09-23 at 2 45 45 PM" src="https://user-images.githubusercontent.com/907405/192225553-39527263-3a22-4cf2-9dbf-3bd013387cf1.png">

**Comment by E-L-T** [comment]
On a échangé avec @Olivier-Marcellin  sur le sujet et on a fait ce constat : dans le parcours actuel, on commence par activer le routage (ce qui crée un groupe "défaut" contenant les instructeurs déjà affectés à la démarche) et ensuite on peut créer de nouveaux groupes (mais ce n'est pas obligatoire). Conditionner l'activation du routage à l'existence de plusieurs groupes impliquerait donc d'inverser l'ordre des choses, et donc de pas mal modifier le parcours. 

On envisage plutôt ces changements :
- Dans le dashboard de la procédure en brouillon, dans le bloc Groupe instructeur, mettre une icône "À faire" si les conditions suivantes ne sont pas remplies :
  - Au moins 2 groupes
  - Chaque groupe doit avoir un libellé et au moins un instructeur affecté
- Dans la page "groupe d'instructeurs", remonter les blocs "gestion des groupes" puis "libellé du routage" et ajouter une description dans le premier bloc, une fois le routage activé : "Le routage est activé. Plusieurs groupes peuvent être créés et des instructeurs peuvent leur être affectés." 

Eventuellement :
- A l'activation du routage, créer 2 groupes par défaut plutôt qu'un seul.

@Olivier-Marcellin je te laisse éditer/compléter si tu veux

**Comment by E-L-T** [comment]
Suite à un point avec @tchak et @Olivier-Marcellin on part sur un découpage en 3 PR :  
- [ ] ETQ admin uniquement empêcher de mettre un espace vide comme libellé de routage 
- [ ] côté usager cacher le select de groupes d'instructeurs si on n'a qu'un seul groupe / ne pas afficher les groupes sans instructeurs dans le select (pour éviter que des dossiers passent inaperçus après avoir été déposés)
- [ ] ETQ admin, remonter en premier le bloc de création de groupe. Le routage s'active automatiquement à la création d'un 2e groupe. Et se désactive automatiquement à la suppression de l'avant dernier groupe. C'est surtout dans cette page qu'il y aurait du design à faire. Et aussi dans le tableau de bord de l'admin : voir comment afficher une alerte en cas de groupe sans instructeur.

**Comment by tchak** [comment]
done
