### ISSUE TITLE
ETQ Usager, lorsque je reste trop lontemps sur une page, les liens pour les modeles de pjs expirent 

### ISSUE THREAD

**Issue by LeSim** [demarches-simplifiees/demarches-simplifiees.fr#7920]
les liens ne fonctionnent plus et les usagers appelent les administrations.

https://secure.helpscout.net/conversation/1969132375/1985235?folderId=1653799

on ne veut pas mettre de durée plus importante pour éviter de devenir une dropbox.

peut être faire un hook js, qui vérifie la validité du lien et propose un rafraîchissement si la page est périmé ?

**Comment by colinux** [comment]
Autre option évoquée : faire un lien non expirable "proxy", qui redirige vers la PJ si l'utilisateur est bien connecté.
