### ISSUE TITLE
ETQ Usager/instructeur, je veux que la carto affiche un message s'il y a trop de point a afficher

### ISSUE THREAD

**Issue by LeSim** [demarches-simplifiees/demarches-simplifiees.fr#7925]
plutot que de planter misérablement.

https://secure.helpscout.net/conversation/2040057794/1993748/

**Comment by lisa-durand** [comment]
@LeSim est-ce possible d'avoir la façon de reproduire le bug - ça n'a pas planté de mon côté. Merci !

**Comment by LeSim** [comment]
non reproduit non plus
