### ISSUE TITLE
ETQ Administrateur, je veux pouvoir manipuler le champ routage comme les autres champs

### ISSUE THREAD

**Issue by LeSim** [demarches-simplifiees/demarches-simplifiees.fr#7936]
avec en plus avec le conditionnel 

dans le détail :

- ajouter automatiquement tout le temps ce type de champ
- visible dans l'éditeur si routage activé (plus de 2 groupes)
- non supprimable, non ajoutable
- revisable (position + libelle)
- les changements de groupe n'implique pas de changement de revision (pour l'instant en tout cas)
- un groupe qui est utilisé comme condition ne peut pas être supprimés
- modifier champ value pour qu'il prenne le type routage_type_de_champ
- ajouter une option pour cacher le champ 

- sur la construction d'un dossier, un champ routage est ajouté, sa fonction visible? dépend si le routage est activé, ou si on active l'option routage cachée
- sur le champ, on stocke le groupe_instructeur_id
- garder un export classique sur le champ

Notes
- on dénormalise on garde le groupe_instructeur_id sur le dossier
- sur la mutatino de l'api graphql il faudra modifier a la fois sur le dossier et sur le champ
- pareil sur les réassignation depuis l'interface d admin des groupes instructeur.

**Comment by E-L-T** [comment]
Je ferme le ticket suite à un changement de stratégie. Voir https://github.com/demarches-simplifiees/demarches-simplifiees.fr/issues/8620
