### ISSUE TITLE
L'estimation du temps de remplissage semble buger

### ISSUE THREAD

**Issue by Bouchralazaar** [demarches-simplifiees/demarches-simplifiees.fr#7963]
Démarche 65515 , l'estimation est trop courte par rapport au formulaire
https://app.crisp.chat/website/266ba25d-91d1-4774-b01f-a23ba63d662f/inbox/session_b66cb685-6c29-4a24-ad42-c92eaf49c66d/

**Comment by Bouchralazaar** [comment]
sujet connexe, quid du conditionnel et du temps de remplissage de la démarche? ..

**Comment by colinux** [comment]
J'ai préparé une PR qui tient compte des temps de lecture (description & explications) qui sont parfois longs.

Pour le conditionnel et améliorer la prise en charge des blocs répétables, j'ai créé le ticket #7968
