### ISSUE TITLE
ETQ Administrateur, il y a un espace blanc dans la configuration de la démarche

### ISSUE THREAD

**Issue by LeSim** [demarches-simplifiees/demarches-simplifiees.fr#7972]
![Image collée à 2022-10-28 14-00](https://user-images.githubusercontent.com/907405/198583193-7d5d3043-002b-482e-96d1-13e6ed69660c.png)

**Comment by tchak** [comment]
closed with https://github.com/demarches-simplifiees/demarches-simplifiees.fr/pull/7988
