### ISSUE TITLE
Liens explicite (Critère 6.1) - Accueil

### ISSUE THREAD

**Issue by julieSalha** [demarches-simplifiees/demarches-simplifiees.fr#8050]
@Afin de rendre les liens de la page d'accueil explicites, voici les corrections à apporter : 

- [x]  **Lien de retour à l'accueil (placé dans le header) :** 

Remplacer et compléter l'attribut  `title` par un attribut `aria-label` de la manière suivante : 
 `aria-label="demarches-simplifiees.fr - Aller à la page d’accueil"`.
Correction à appliquer en affichage mobile et desktop.

Ceci afin de reprendre le contenu visible et de préciser la fonction du lien.

L'attribut `aria-label` est mieux pris en compte par les technologies d'assistance que l'attribut `title`.

Plus d'informations ici : [Compléter les liens et les boutons non explicites avec aria-label ou title](https://www.accede-web.com/notices/html-et-css/liens-et-boutons/completer-les-liens-et-les-boutons-non-explicites-avec-aria-label-ou-title/)

- [x] Penser également à la traduction du passage de texte de l'attribut pour la version anglaise du site.

- [x]  **Pour l'image-lien beta.gouv.fr placée dans le footer :**

Option 1 :

=> intégrer l'image-logo directement dans le code source et non grâce à des propriétés CSS (balise `<img>`) pour ne pas que le contenu disparaisse lorsque les styles CSS sont désactivés.
=> lui ajouter le texte alternatif "Beta.gouv.fr" (texte visible dans l'image) grâce à l'attribut `alt="Beta.gouv.fr"`.
=> supprimer l'attribut `aria-label="Beta.gouv.fr"` sur la balise `<a>`
=> l'attribut `title` de la balise `<a>` doit contenir à minima l'intitulé du lien. Ici : "Beta.gouv.fr".
`<a title="Beta.gouv.fr [...]">[...]</a>`

Option 2 :

Supprimer l'attribut `title` du lien. L'attribut `aria-label` est mieux pris en compte par les technologies d'assistance.

- [x]  Pour le lien **"la direction interministérielle du numérique (DINUM)"** placé dans le footer, ajouter l'attribut `title="la direction interministérielle du numérique (DINUM) - Nouvel onglet"`
(cf [Documentation DSFR - Liens](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/liens))

- [x]  Pour **tous les liens s'ouvrant dans un nouvel onglet**, le préciser grâce à l'attribut `title` de la même manière que le lien de la DINUM (`title="intitulé du lien - Nouvel onglet"`). 
Sur cette page : 

1. "Aide"
2. "Accéder à l’aide en ligne"
3. "Le code source"
4. "legifrance.gouv.fr"
5. "gouvernement.fr"
6. "service-public.fr"
7. "data.gouv.fr"
8. "licence etalab-2.0"
9. Comment trouver ma démarche ?
10. Accéder à l’aide en ligne
11. Un problème avec le site ?

![Image](https://user-images.githubusercontent.com/49035942/204749213-e51e7bde-8ae0-4fed-b1e4-f49f890fb1d1.png)

**Comment by colinux** [comment]
Est-ce que tu confirmes qu'on peut définir l'`aria-label` comme tu l'indiques, tout en conservant tel quel l'attribut `title` ? (pertinent pour les navigateurs graphiques, avec l'affichage d'un tooltip)

**Comment by julieSalha** [comment]
Pour l'image-lien beta.gouv.fr placée dans le footer (Option 1) : 
- L'attribut `aria-label` n'est pas nécessaire, l'intitulé du lien est défini par le texte alternatif de l'image
- Il est possible d'ajouter un attribut `title` sur la balise `<a>` du lien afin d'ajouter une information graphique au survol de la souris. Dans ce cas, il faut à minima qu’il contienne l’info du lien, ici le texte alternatif de l'image.

**Comment by colinux** [comment]
OK donc pour ce lien beta.gouv on est bon :) merci

**Comment by julieSalha** [comment]
C'est OK en PROD. Bravo :)
