### ISSUE TITLE
Pertinence titre de page (Critère 8.6) - Accueil

### ISSUE THREAD

**Issue by julieSalha** [demarches-simplifiees/demarches-simplifiees.fr#8052]
- [ ] Remplacer le titre de page (balise `<title>` ) par "Accueil - demarches-simplifiees.fr" afin de le rendre plus explicite.
- [ ] Traduire le passage de texte pour la version anglaise du site

Plus d'informations : [Renseigner un <title> précis sur chaque page](https://www.accede-web.com/notices/html-et-css/titre-de-la-page/renseigner-un-title-precis-sur-chaque-page/)

**Comment by julieSalha** [comment]
Oui c'est plus précis :)

**Comment by colinux** [comment]
Je ferme, ça avait été traité dans une PR plus générale sur la page d'accueil
