### ISSUE TITLE
Prise de focus visible (Critère 10.7) - Accueil

### ISSUE THREAD

**Issue by julieSalha** [demarches-simplifiees/demarches-simplifiees.fr#8053]
La prise de focus n'est pas visible pour le lien "Accéder à l’aide en ligne".

Correction :
Définir un style du focus qui soit suffisamment contrasté (ratio minimum de 3:1 entre les couleurs du focus et les couleurs environnantes).
Ex : bordure blanche en pointillé.

Pour vérifier les contrastes, vous pouvez utiliser l'outil suivant : [Contrast checker](https://webaim.org/resources/contrastchecker/)

Ceci est valable pour tous les cas similaires.

**Comment by inseo** [comment]
@mfo : Le problème ne semble plus d'actualité.   
La rapport de contraste de la prise de focus est suffisant sur les deux couleurs d'arrière-plan.

![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/2088264/1c52ec4f-6130-4ef6-a430-82440e8a2794)
![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/2088264/eb3db74b-308e-4e74-8067-4236827a4198)
