### ISSUE TITLE
Au moins deux moyens de navigation différents (Critère 12.1) - Accueil

### ISSUE THREAD

**Issue by julieSalha** [demarches-simplifiees/demarches-simplifiees.fr#8054]
En terme d'accessibilité, nous devons prévoir au moins deux moyens de navigation y compris le menu principal.

Côté usager, nous avons un moteur de recherche et un menu principal.

Recommandations

- [x] Veiller à ce que le moteur de recherche soit disponible depuis toutes les pages usagers (+ [Moteur de recherche (Critère 12.6) - Résultats de recherche usagers#8588](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/issues/8588))

- [x] Proposer un footer sur toutes les pages usagers, la possibilité de contact est importante pour l'usager

**Comment by julieSalha** [comment]
@Olivier-Marcellin 
Voici les maquettes pour la refonte des footers : 
Décomposition sur la page d'accueil :
- Lettre d'information (uniquement pour les administrateurs lorsque connecté) ?
- Liens - item (Communication, etc).
- Bloque marque - item (avec bloc marque Gouvernement + DINUM)
- Mentions - item (Accessibilité, etc.)

Voici les maquettes correspondantes 
<img width="1092" alt="Capture d’écran 2023-04-26 à 16 14 14" src="https://user-images.githubusercontent.com/101646817/234604943-41723440-5e12-4527-9191-9cc23e8a09fa.png">
<img width="138" alt="Capture d’écran 2023-04-26 à 16 14 34" src="https://user-images.githubusercontent.com/101646817/234604962-aa743c53-035e-48de-8cec-35b225579f92.png">

**Comment by Olivier-Marcellin** [comment]
Suite des maquettes pour la refonte du footer :
Décomposition pour les pages de démarche côté usagers (à partir de la page d'accueil de la démarche)
- footer de la démarche (Cette démarche est gérée par, etc.)
remarque pour l'intégration : se footer est hors composant dsfr, j'ai créé une mise en page
- Mentions - item (accessibilité, etc.)

![Image](https://user-images.githubusercontent.com/101646817/234612702-a72a8f7b-8c70-4e6c-a057-59578d1621a6.png)



![Image](https://user-images.githubusercontent.com/101646817/234612315-ede65f5f-ab48-47e7-87d4-b5857a34a1c4.png)

**Comment by Olivier-Marcellin** [comment]
Suite et fin des maquettes du footer :
Décomposition pour les pages de démarche côté usagers :
- Mentions - item (accessibilité, etc.) à faire figurer sur toutes les pages

![Image](https://user-images.githubusercontent.com/101646817/234614181-914fd21a-6344-4451-8204-94b2cc4c0639.png)



![Image](https://user-images.githubusercontent.com/101646817/234614267-c1e72a72-4b86-4cc0-bd5b-42580200ba7e.png)

**Comment by Olivier-Marcellin** [comment]
Résumé sur l'affichage du footer :
- Le bloc marque item (Gouvernement, DINUM) est à faire figurer uniquement sur l'amont du parcours (page d'accueil, pages de connexion)
- Le bloc de la démarche est à faire figurer uniquement sur la page d'accueil de la démarche et sur le formulaire
- Les mentions item (accessibilité, etc.) est à faire figurer sur toutes les pages

Questions :
Devons-nous faire figurer ces mentions également sur la vue admin/instructeurs ? (autrement dit est-ce qu'elles doivent aussi être accessibles ?)

![Image](https://user-images.githubusercontent.com/101646817/234615958-3805f4d2-4c77-4ed1-a174-98669d82bf06.png)

**Comment by Olivier-Marcellin** [comment]
Maquette du footer de la démarche avec des ajustements d'espacements sur les coordonnées suite retour du support
Cette version est celle qui est en cours d'intégration
![Image](https://user-images.githubusercontent.com/101646817/234834682-f7d73005-9c85-40f8-a5ff-8f42828fd060.png)
