### ISSUE TITLE
Lien d'évitement (Critère 12.7) - Accueil

### ISSUE THREAD

**Issue by julieSalha** [demarches-simplifiees/demarches-simplifiees.fr#8055]
La page ne propose pas de lien d'accès rapide au au contenu principal de la page.

Correction :
Ajouter sur l'ensemble des pages, un lien d’évitement du type « Aller au contenu » pour ainsi faciliter la navigation. La structure HTML à mettre en place est de ce type :

`<body>
  <a class="skiplink" href="#contenu">Aller au contenu</a>`
     […]
  `<main role="main">
     <a id="contenu" tabindex="-1"></a>`
        […]
  `</main>`
     […]
`</body>`

Pour plus d'informations de personnalisation, vous pouvez consulter cette documentation :
https://www.accede-web.com/notices/html-et-css/navigation-au-clavier/mettre-en-place-un-lien-devitement/#:~:text=Un%20lien%20d'%C3%A9vitement%20du,contenu%20principal%20de%20la%20page.

**Comment by julieSalha** [comment]
C'est validé en PROD.

**Comment by colinux** [comment]
Je ferme, ça a été mergé + prodé
