### ISSUE TITLE
Contrôle de saisie et information (Critère 11.11) - Authentification

### ISSUE THREAD

**Issue by julieSalha** [demarches-simplifiees/demarches-simplifiees.fr#8074]
Les champs de saisie en erreur, qui attendent un format particulier, ne sont pas accompagnés d'un exemple réel de saisie.

C'est le cas du champ email.

Correction :
- Modifier et compléter le message d'erreur : "Veuillez saisir une adresse e-mail valide. Par exemple : john.doe@ds.fr"

**Comment by dzc34** [comment]
> "(...) Par exemple : `john.doe@ds.fr`"

Suggestion : `john.doe@example.org`, `john.doe@example.com` ou `john.doe@exemple.fr`

ressources : https://fr.wikipedia.org/wiki/Example.com

**Comment by julieSalha** [comment]
Ok en PROD
