### ISSUE TITLE
ETQ Instructeur, je souhaite voir : le numéro de dossier, le lien vers la démarche, la liste des administrateurs sur mon interface

### ISSUE THREAD

**Issue by kara22** [demarches-simplifiees/demarches-simplifiees.fr#8082]

**Comment by dzc34** [comment]
> ETQ Instructeur, je souhaite voir : ...  la liste des administrateurs sur mon interface 

@kara22, nous avons une demande similaire sur notre Gitlab : [ETQ instructeur, contacter les administrateurs de la démarche via DS](https://gitlab.adullact.net/demarches-simplifiees/evolution-du-logiciel-demarches-simplifiees/-/issues/5)

> source : [Suggestion-Votes / Instructeurs : pouvoir contacter l'administrateur d'une démarche via DS](https://demarches-simplifiees.featureupvote.com/suggestions/212006/instructeurs-pouvoir-contacter-ladministrateur-dune-demarche-via-ds)  (2021)
> 
> Les instructeurs ne savent pas forcément qui est l'administrateur d'une démarche. Il serait utile de pouvoir laisser un message sur DS pour solliciter une aide ou l'activation d'une fonctionnalité contrôlée par l'administrateur (exemple : ajouter un expert à une liste gérée, suggestion d'une fonctionnalité manquante à faire remonter...)
>
> -------------------------------
> Reformulation :
> - Les instructeurs ne savent pas forcément qui est l'administrateur d'une démarche.
> - Parfois, des instructeurs posent des questions au support de l'instance DS, alors que l'administrateur de la démarche à certainement la réponse. 
> - La solution proposée permet aux instructeurs d'utiliser un support localisé (à la démarche)  au lieu de contacter le support global de l'instance DS.
> - Exemples de fonctionnalité contrôlée par l'administrateur, pour lesquelles une prise de contact facile pour l'instructeur serait très pratique :
>   - ajouter un expert à une liste gérée,
>   - modifier le formulaire (via les révisions) en cas de soucis constatés dans les informations saisies par les usagers,  
>   - suggestion d'une fonctionnalité manquante à faire remonter...
