### ISSUE TITLE
Balises utilisées uniquement à des fins de présentation (Critère 8.9) - Création dossier (Brouillon)

### ISSUE THREAD

**Issue by julieSalha** [demarches-simplifiees/demarches-simplifiees.fr#8105]
https://www.demarches-simplifiees.fr/dossiers/10682853/brouillon

Au moins une balise est utilisée uniquement pour créer des effets de présentation.

Par exemple :
- On trouve des paragraphes `<p></p>` vides servant à créer des espacements. 

Corrections :

- [x] Supprimer les paragraphes vides et réaliser les mises en forme uniquement en CSS.

- [x] Supprimer également toutes les balises `<br>`

Astuce : Pour les repérer, vous pouvez utiliser [l'assistant RGAA](https://chrome.google.com/webstore/detail/assistant-rgaa/cgpmofepeeiaaljkcclfldhaalfpcand?hl=fr) et sélectionner le critère 8.9.

**Comment by julieSalha** [comment]
https://www.demarches-simplifiees.fr/dossiers/10659723/brouillon

Une démo via l'utilisation de l'assistant RGAA : 

<img width="1423" alt="Capture d’écran 2022-11-29 à 11 17 52" src="https://user-images.githubusercontent.com/49035942/204503108-180bcc11-938a-4722-bb9e-f4e75deeebdc.png">

Exemple de balise `<br>` à supprimer : 
<img width="1256" alt="Capture d’écran 2022-11-29 à 11 18 30" src="https://user-images.githubusercontent.com/49035942/204503262-9a29a07d-24bf-4570-bfec-3eac8444aef5.png">

Si cela est lié à la configuration de l'administrateur, on pourra en reparler et proposer des conseils...

**Comment by mfo** [comment]
@julieSalha ,en prod

**Comment by julieSalha** [comment]
Ok en PROD :)
