### ISSUE TITLE
Affichage contenus sans défilement horizontal - Fenêtre 320px (Critère 10.11) - Création dossier (Brouillon)

### ISSUE THREAD

**Issue by julieSalha** [demarches-simplifiees/demarches-simplifiees.fr#8119]
https://www.demarches-simplifiees.fr/dossiers/10682853/brouillon

Dans une fenêtre de 320px de large, le contenu n'est plus totalement lisible et il est nécessaire d'utiliser la barre de défilement horizontal.

Lorsque les pages contiennent de longues URL(s), modifier les propriétés CSS pour que les liens passent à la ligne.
Ex : https://www.demarches-simplifiees.fr/dossiers/10659723/brouillon

Utiliser par exemple `overflow-wrap: break-word;` compatible avec tous les navigateurs.
Documentation : [overflow-wrap](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap)

On peut aussi proposer un intitulé de lien plus court.

**Comment by colinux** [comment]
Pourrais-tu joindre une capture d'écran de la zone concernée ? Je ne la retrouve pas. merci !

**Comment by julieSalha** [comment]
<img width="501" alt="Capture d’écran 2022-11-29 à 09 45 52" src="https://user-images.githubusercontent.com/49035942/204481619-5c1881fc-1e71-4222-ac03-e2cb6c138f78.png">
<img width="498" alt="Capture d’écran 2022-11-29 à 09 46 34" src="https://user-images.githubusercontent.com/49035942/204481707-81fd8991-9641-41ac-bedf-33dad5de6d86.png">

**Comment by julieSalha** [comment]
Ok en PROD
<img width="244" alt="Capture d’écran 2023-02-14 à 10 51 40" src="https://user-images.githubusercontent.com/49035942/218700438-852d1273-2d97-45ee-83b5-32dde31f5128.png">

**Comment by colinux** [comment]
Closed by #8606
