### ISSUE TITLE
Information donnée uniquement par la couleur (Critère 3.1) - Création dossier (Résumé)

### ISSUE THREAD

**Issue by julieSalha** [demarches-simplifiees/demarches-simplifiees.fr#8135]
Au moins une information donnée uniquement par la couleur n'a pas d'alternative.

Par exemple : 
- L'indication de lien actif dans le menu de navigation

Corrections :
- Pour l'indication de lien actif, ajouter une mise en forme  (mise en gras, changement de taille, inversion des contrastes, soulignement) et un attribut title sur le modèle "[Intitulé] - page active"

**Comment by inseo** [comment]
@mfo : Si le menu de navigation en question est bien : "Résumé - Demande - Messagerie", le problème n'est plus d'actualité.

![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/2088264/f52cbc68-0335-4a81-8fc2-07ad7c16a291)

**Comment by inseo** [comment]
ETQ Expert, j'ai une navigation avec plusieurs éléments et ça donne ça.
La bordure et l'attribut `aria-current` font que pour moi, si la même navigation est appliquée à tous les autres profils, on est bons. :)

<img width="1257" alt="" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/2088264/a6ede350-47a8-4de6-a5ee-83fe2ef5c86f">
<img width="546" alt="" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/2088264/85adde97-f6a8-4f1c-9a9d-ff45f4859057">

**Comment by mfo** [comment]
Justement ETQ usager c'est pas le cas :/

**Comment by inseo** [comment]
J'ai ce rendu de mon côté... Pas toi ? 

![Capture d’écran 2024-04-05 à 11 08 31](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/2088264/a6b79499-38a9-4634-b43f-3c1e5bdfc639)
