### ISSUE TITLE
Liens explicites (Critère 6.1) - Création dossier (Demande)

### ISSUE THREAD

**Issue by julieSalha** [demarches-simplifiees/demarches-simplifiees.fr#8161]
https://www.demarches-simplifiees.fr/dossiers/10659723/demande

Au moins un intitulé de lien n'est pas pertinent.

Par exemple :
Les liens de téléchargement de fichiers

![Image](https://user-images.githubusercontent.com/49035942/204565199-fa3d06c7-87e6-4deb-b83e-304fb182bf92.png)

Corrections :

- [ ] Modifier l'attribut `title` de chaque lien pour qu'il reprenne le contenu visible, par exemple sur le modèle `title="[Nom du fichier]  - Télécharger la pièce jointe - Nouvel onglet"`.

- [ ] Traduire le passage de texte pour la version anglaise.

**Comment by colinux** [comment]
La livraison des uploads (puis téléchargements) multiples a résolu ce ticket : le composant DSFR de téléchargement est maintenant utilisé
