### ISSUE TITLE
Balises utilisées uniquement à des fins de présentation (Critère 8.9) - Création dossier (Résumé)

### ISSUE THREAD

**Issue by julieSalha** [demarches-simplifiees/demarches-simplifiees.fr#8168]
https://www.demarches-simplifiees.fr/dossiers/10682740
https://www.demarches-simplifiees.fr/dossiers/10659723

Au moins une balise est utilisée uniquement pour créer des effets de présentation.

Supprimer les balises `<br>` du footer.

- [x] Zone 1 : "Cette démarche est gérée par ...."
**(Dépend de la configuration administrateurs)**

![Image](https://user-images.githubusercontent.com/49035942/204804190-133478e9-ca5a-46e8-af1e-df5be4722d8b.png)

- [x] Zone 2 : "Poser une question sur votre dossier"

![Image](https://user-images.githubusercontent.com/49035942/215722628-9b3172f5-931b-4363-b5e9-7d2dfb786b2e.png)

Ceci est valable sur l'ensemble du site. Privilégier des propriétés CSS pour les espacements (margin, padding etc.).

**Comment by julieSalha** [comment]
L'ajout de balises `<br>` dépend aussi de la configuration de la part des administrateurs.
En effet, lorsque l'administrateur souhaite "Modifier le service" et renseigner l'"Adresse postale".
Lorsqu'il tape sur la touche "Entrée" pour créer un retour à la ligne, cela génère automatiquement l'ajout de balises `<br>` dans le footer lors de l'édition de dossiers.

![Image](https://user-images.githubusercontent.com/49035942/215718495-47e07673-34a6-4e31-93c6-6086479a7521.png)
![Image](https://user-images.githubusercontent.com/49035942/215718496-f5bc8949-0656-4cfb-bab5-f92ba4964136.png)

Pour ce sujet, je propose l'ajout d'un interface WYSIWYG pour toutes les zones de renseignement d'informations textuelles ainsi qu'un sensibilisation des administrateurs.

**Comment by julieSalha** [comment]
Pour la zone 2, sur certaines démarches, les informations sont manquantes pour le téléphone et les horaires d'ouverture, il apparaît parfois juste un point.

Lors de la configuration d'une démarche, dans le menu "Modifier le service", les informations demandées pour "Numéro de téléphone" et "Horaires" sont obligatoires.

Peut-on envisager que des administrateurs ne soient pas en mesure de renseigner ces informations et dans ce cas ne rien afficher dans la zone 2 du footer ?

**Comment by mfo** [comment]
@julieSalha oui c'est envisageable. J'imagine d'ailleurs que le caractère obligatoire sur le tel/horaire est arrivé en cours de route.

**Comment by mfo** [comment]
@julieSalha ,en prod

**Comment by julieSalha** [comment]
Ok en PROD :)
