### ISSUE TITLE
Structuration des listes (Critère 9.3) - Messagerie

### ISSUE THREAD

**Issue by julieSalha** [demarches-simplifiees/demarches-simplifiees.fr#8180]
https://www.demarches-simplifiees.fr/dossiers/10659723/messagerie

Sur cette page, la sémantique HTML pour créer des listes n'est pas correctement employée, ce qui invalide le critère.

Corriger en employant les balises `<ul>` et `<li>` pour structurer les listes non ordonnées.

![Image](https://user-images.githubusercontent.com/49035942/205020161-b1a810c0-8836-4dcc-97cc-7f5b088cee8e.png)

**Comment by julieSalha** [comment]
Ces erreurs dépendent de la configuration administrateurs.
Le ticket est lié au ticket [Configuration administrateurs - Analyse bugs d’accessibilité démarches en cours#8067](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/issues/8067).

**Comment by mfo** [comment]
@julieSalha ,en prod

**Comment by julieSalha** [comment]
Ok en PROD :)
