### ISSUE TITLE
ETQ administrateur, je souhaite modifier le message de fin de dépôt de dossier lorsque ma démarche est déclarative 

### ISSUE THREAD

**Issue by CamilyaDellali** [demarches-simplifiees/demarches-simplifiees.fr#8189]
Lorsqu'une démarche est déclarative, l'administrateur n'a pas la possibilité de modifier le message de fin de dépôt d'un dossier et plus précisément le texte "**Vous pouvez le modifier** et échanger avec un instructeur" . Or,  cela peut induire en erreur les usagers ( qui ne peuvent pas modifier le dossier une fois déposé). 

Il faudrait alors paramétrer cela autrement pour que cela soit générique pour toutes les démarches ( retirer ce bout de texte  ou reformuler? ) 

![image](https://user-images.githubusercontent.com/82160230/205325894-28b8f02a-2007-4d56-82c5-efc363d3c74d.png)

Retour support : https://secure.helpscout.net/conversation/2085784363/2006863?folderId=1653804

**Comment by tchak** [comment]
On ne peut pas modifier le message par défaut. Mais il n'est pas correct actuellement pour les démarches déclaratives. On peut corriger ça.
