### ISSUE TITLE
Script compatible avec les technologies d'assistance (Critère 7.1) - Accueil

### ISSUE THREAD

**Issue by julieSalha** [demarches-simplifiees/demarches-simplifiees.fr#8204]
https://www.demarches-simplifiees.fr/ - Affichage mobile

Afin d'informer les technologies d'assistance de l'état développé ou réduit du menu, utiliser l'attribut `aria-expanded`.

Plus d'informations : [aria-expanded](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded)

Ajouter l'attribut sur la balise `<button aria-controls="burger-menu">[...]</button>`.
Renseigner sa valeur de façon dynamique suivant l'état du menu : 

- `aria-expanded="false"` lorsque le menu est fermé
- `aria-expanded="true"` lorsque le menu est affiché

![Image](https://user-images.githubusercontent.com/49035942/205936541-4d0270a0-59c2-4167-a65f-3eae0300cc75.png)
![Image](https://user-images.githubusercontent.com/49035942/205936542-e758a521-9028-42d7-a956-8ea3b213ea89.png)

**Comment by colinux** [comment]
C'est un composant DSFR : curieux qu'il n'aient pas intégré cet attribut. On leur remonte le problème pour s'assurer que c'est un "oubli" de leur part ?

**Comment by julieSalha** [comment]
@colinux Fais-tu allusion à la documentation d'une [modale sur le DSFR](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/modale) ?

Je ne vois pas de documentation sur le burger menu sur le DSFR, on en parle sur l'[affichage responsive de la navigation principale (en bas de page)](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/navigation-principale).
<img width="871" alt="Capture d’écran 2023-01-03 à 11 19 26" src="https://user-images.githubusercontent.com/49035942/210338531-9ac7de00-21c4-4464-8a0f-f828059c7166.png">

Voici la [structure recommandée pour un burger menu](https://www.accede-web.com/notices/interface-riche/menu-hamburger/).

On peut le remonter oui :-)

**Comment by julieSalha** [comment]
@colinux as-tu eu des retours à ce sujet ?
N'hésite pas à me partager le lien de votre discussion :-)

**Comment by julieSalha** [comment]
@colinux Le burger menu est géré ici comme une fenêtre modale donc en effet ce n'est pas nécessaire. Je me suis chargée des corrections. Une PR est en attente :)

**Comment by julieSalha** [comment]
Ok en PROD
