### ISSUE TITLE
Balises utilisées uniquement à des fins de présentation (Critère 8.9) - Accueil

### ISSUE THREAD

**Issue by julieSalha** [demarches-simplifiees/demarches-simplifiees.fr#8205]
Supprimer les balises `<br>` suivantes utilisées uniquement à des fins de présentation (hors cas particuliers basés sur le DSFR).

Cinq balises sur la page (hors logos DSFR) : 

- Deux balises dans le passage de texte "Effectuer une démarche administrative en ligne"
- Une balise dans le passage de texte "administrations partenaires"
- Une balise dans le passage de texte "dossiers déposés"
- Une balise dans le passage de texte "de réduction des délais de traitement"

**Comment by colinux** [comment]
Pour le moment je ne sais pas comment m'en passer pour conserver l'UI attendue et les retours à la ligne là où ils doivent être. Si quelqu'un a une idée ?…

**Comment by julieSalha** [comment]
@colinux Voici des propositions de correction pour pouvoir supprimer les balises `<br>` tout en conservant l'UI : 

- [ ] "Deux balises dans le passage de texte "Effectuer une démarche administrative en ligne""

- Supprimer les balises` <br>` utilisées pour le titre "Effectuer une démarche administrative en ligne"
- Ajouter une propriété CSS sur l'élément parent `<div class="hero-text">` comme `width: 30%` pour l'affichage Bureau (Desktop)
<img width="1906" alt="Capture d’écran 2023-01-03 à 11 33 33" src="https://user-images.githubusercontent.com/49035942/210341876-ea3e2255-b147-4dbd-8ab9-9ff7e2b58186.png">

- Adapter cette propriété pour l'affichage mobile

**Comment by colinux** [comment]
Merci pour les propositions. J'avais essayé des solutions à base de width que je trouvais fragiles (ça casse un peu le layout dès que l'utilisateur utilise le zoom navigateur), mais je retenterai car je ne vois pas comment faire autrement de toute façon. Et l'a11y doit être prioritaire sur ce sujet de toute façon.

**Comment by julieSalha** [comment]
Dans ce cas, je fais comme ça la plupart du temps. Il vaut mieux éviter les tailles en pixels, cela peut être contraignant en terme d'accessibilité.
N'hésite pas à échanger en phase de développement :-)

**Comment by colinux** [comment]
J'ai cru comprendre que tu pensais te lancer dans un peu d'intégration. Dans ce cas ça me semble un ticket adapté :) (si j'ai mal compris ou si t'as besoin de support, hésite pas à revenir vers moi!).

**Comment by julieSalha** [comment]
Oui je vais vous aider après avoir terminé certains sujets :-)
Ok pour le ticket.
