### ISSUE TITLE
ETQ administrateur, la configuration de la durée maximal de conservation des dossiers (via NEW_MAX_DUREE_CONSERVATION) n'est pas prise en compte

### ISSUE THREAD

**Issue by dzc34** [demarches-simplifiees/demarches-simplifiees.fr#8418]
## Résumé

ETQ administrateur, la configuration de la durée maximale de conservation des dossiers (via la variable d'environnement `NEW_MAX_DUREE_CONSERVATION`) n'est pas prise en compte.

## Configuration d'une instance DS

Configuration de la durée maximal de conservation des dossiers
 via la variable d'environnement optionnelle `NEW_MAX_DUREE_CONSERVATION`

```diff
  # around july 2022, we changed the duree_conservation_dossiers_dans_ds, 
  # allow instances to choose their own duration
- NEW_MAX_DUREE_CONSERVATION=12
+ NEW_MAX_DUREE_CONSERVATION=18
```

## Actuellement

ETQ administrateur
- créer une démarche
- la durée maximale de conservation des dossiers est indiqué à **18** mois 
- mais le navigateur interdit toute valeur > à 12 mois (valeur hard-codé ?)

## Reproduction

- créer une nouvelle démarche vide
- dans "Conservation des données" 
  > Durée en mois après le début de l’instruction. Pour les démarches classiques, cette durée ne peut excéder **18** mois. Si vous avez besoin d’une durée supérieure à **18** mois, merci d’en faire la demande à notre support. 
- saisir **13** mois
- utiliser le bouton "Créer la démarche" ----> info bulle : "Veuillez sélectionner une valeur inférieure à **12** "
- il n'est pas possible de créer la démarche

![Capture_d_écran_de_2023-01-11_10-22-50](https://user-images.githubusercontent.com/6709977/211944543-96546834-f320-4cbf-811c-32cfe35e3172.png)

## Comportement attendu

La configuration de la durée maximale de conservation des dossiers (via la variable d'environnement `NEW_MAX_DUREE_CONSERVATION`) est prise en compte.
  
 --------------------
> `trackingAdullactContrib`   `trackingAdullactBugReport`

**Comment by akarzim** [comment]
Effectivement, il apparait que cette valeur est inscrite en dur dans le code.

```ruby
= f.number_field :duree_conservation_dossiers_dans_ds, { class: 'form-control', placeholder: '6', required: true }.merge(f.object.duree_conservation_etendue_par_ds ? {} : { max: 12 })
```

cf. https://github.com/demarches-simplifiees/demarches-simplifiees.fr/blob/main/app/views/administrateurs/procedures/_informations.html.haml#L28

**Comment by mfo** [comment]
merci pour vos retours, je regarde cette aprem

**Comment by mfo** [comment]
en effet, c'etait un default [SQL](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/blob/main/db/migrate/20221005145531_max_column_duree_conservation_dossiers_dans_ds_to_procedure.rb).
