### ISSUE TITLE
ETQ qu'utilisateur DS , je souhaite voir mon mot de passe lorsque j'en demande un nouveau 

### ISSUE THREAD

**Issue by CamilyaDellali** [demarches-simplifiees/demarches-simplifiees.fr#8458]
Cela fait suite aux pb de délivrance de mails. Lorsque les usagers souhaitent changer leur mot de passe, ils ne peuvent pas le visualiser. 

![image](https://user-images.githubusercontent.com/82160230/213190174-1859851f-712e-4f99-aa74-b5a50e7670d9.png)

**Comment by colinux** [comment]
L'input mot de passe du DSFR qu'on a mis sur la page de connexion pourrait peut-être faire l'affaire
