### ISSUE TITLE
[Bug?] [API] Adresse postale non prédécoupée lors de la duplication d'un dossier

### ISSUE THREAD

**Issue by ansrpa** [demarches-simplifiees/demarches-simplifiees.fr#8487]
**Description**
Lorsque l'autocomplétion est utilisée sur un champ de type adresse postale, cette adresse est prédécoupée [en sous-champs (numéro, voie, code postal, etc.) que l'on peut récupérer via l'API](https://www.demarches-simplifiees.fr/graphql/schema/address.doc.html).
Quand un dossier est dupliqué (ce qui arrive fréquemment lorsqu'on teste une démarche), ces informations ne sont plus disponibles. Il faut manuellement modifier le dossier, puis se rendre dans le champ adresse pour faire surgir l'autocomplétion afin d'enregistrer un prédécoupage et de le rendre disponible à travers l'API.

**Reproduction**
1. Instancier un nouveau dossier avec un champ de type adresse postale.
2. Utiliser l'autocomplétion dans le champ adresse avant de déposer le dossier.
3. Récupérer le dossier via l'API DS, et constater que les champs `streetNumber`, `postalCode`, `cityName`, etc. présentent les valeurs attendues.
4. Dupliquer le dossier.
5. Récupérer le dossier dupliqué avec l'API, et constater que les champs précédents sont désormais vides.

**Comportement attendu**
Il serait beaucoup plus pratique, notamment lors de campagnes de test intensives, de ne pas avoir à « asticoter » les champs adresse pour les rendre prédécoupés et disponibles dans l'API.
Le prédécoupage devrait être associé au dossier de manière permanente, plutôt que d'être généré à la volée suite à une action côté client (clic sur la proposition d'autocomplétion).

**Comment by tchak** [comment]
Merci pour ce rapport détaillé. Effectivement, il y a un bug. Il sera corrigé dans les prochains jours.
