### ISSUE TITLE
ETQ instructeur, je peux demander un avis sur plusieurs dossiers

### ISSUE THREAD

**Issue by tchak** [demarches-simplifiees/demarches-simplifiees.fr#8517]
On pense à une action multiple sur les dossiers. Sélectionner plusieurs dossiers. Demander un avis à un ou plusieurs experts sur tous les dossiers sélectionnés. Le message et la pièce jointe sont les mêmes pour tous les avis envoyés.

**Comment by dzc34** [comment]
doublon avec #9609

**Comment by mfo** [comment]
merci je ferme celui la et recopie le msg de tchak
