### ISSUE TITLE
Téléchargement pièces jointes et gestion focus (Critère 7.1) - Création dossier (Brouillon)

### ISSUE THREAD

**Issue by julieSalha** [demarches-simplifiees/demarches-simplifiees.fr#8553]
https://www.demarches-simplifiees.fr/dossiers/10682853/brouillon

Bien gérer la reprise de focus pour avertir de l'ajout/suppression des fichiers : 

- Ajout d'un fichier :  

- [x] Corriger la sémantique HTML du bouton de suppression : 
Il s'agit ici d'un élément déclenchant une action, la balise `<button>` est mieux adaptée qu'une balise de lien `<a role="button">`

- [x] Placer le bouton de suppression à droite de la pièce jointe téléchargée ([cf maquettes Amélioration vue usagers](https://www.figma.com/file/YKcafywdYhT6ABFlmy5d56/Am%C3%A9lioration-vue-usagers?node-id=1%3A2&t=RULLDsHE4hAzSAQF-0))

- [x] Privilégier la prise de focus sur le fichier qui vient d'être ajouté (balise `<a>` du lien), pour qu'à la tabulation suivante, les utilisateurs atteignent "supprimer". 

![Image](https://user-images.githubusercontent.com/49035942/216298132-9b80db1d-3156-4bb4-ac3d-98eee446040e.png)

- [ ] À la suppression d'un fichier, replacer le focus sur le bouton d'ajout : 

![Image](https://user-images.githubusercontent.com/49035942/216299781-10c87dfa-c497-448f-ae87-c09d9a9dff2e.png)

Ces fonctionnalités sont valables pour le téléchargement de pièces multiples.

**Comment by colinux** [comment]
Je suis surpris de tes screenshots: l'implémentation a complètement changé depuis début décembre :/ (bien que je pense que la plupart des points restent d'actualité, il y'en a peut-être d'autres maintenant avec l'ajout multiple optionnel

**Comment by colinux** [comment]
@julieSalha cf mattermost

**Comment by julieSalha** [comment]
Refactoring en cours...

**Comment by mfo** [comment]
ok je m'y remets c'est beaucoup plus clair merci !

**Comment by mfo** [comment]
en prod !

**Comment by julieSalha** [comment]
En PROD, ok pour les points 1 et 3 :)

**Comment by colinux** [comment]
@Olivier-Marcellin sur l'alignement des boutons "supprimer", finalement on le passe à droite du nom du fichier (ce qui fera perdre l'alignement horizontal avec des noms de fichiers de taille différente?) Il me semblait au départ que c'était un no-go pour toi.

**Comment by Olivier-Marcellin** [comment]
salut Colin, le placement des boutons supprimer à droite (avant l'élément à supprimer) est plus optimal que à gauche, c'est logique du point de vue de l'action utilisateurs, et pour le problème d'alignement est-ce qu'on pourrait pas régler la longueurs maximum des libellés de pièces (pièces…) ainsi on aurait un alignement vertical identique quelle que soit la longueur ?
