### ISSUE TITLE
Motif de conception Progressbar et Antivirus (Critère 7.1) - Création dossier (Brouillon)

### ISSUE THREAD

**Issue by julieSalha** [demarches-simplifiees/demarches-simplifiees.fr#8555]
(En attente évolution DSFR)

https://www.demarches-simplifiees.fr/dossiers/10682853/brouillon

1. Compléter le motif de conception Progressbar (Téléchargement de pièces jointes) : 
- [ ] Ajouter à chaque description précédant un ajout de fichier, le format/poids/taille attendu.

Ex : “Votre image de profil doit être au format png ou jpg et ne pas excéder 100ko”
Quand il n'y a pas de spécificités, préciser que tous les formats sont acceptés.

- Adapter la sémantique HTML de la barre de progression (Téléversement) :

![Image](https://user-images.githubusercontent.com/49035942/216273703-17b93223-a32f-4d83-9cbd-c2442dcb5ca6.png)
![Image](https://user-images.githubusercontent.com/49035942/216273704-d0ad12f1-f4af-4f78-b91e-4075cb98621b.png)

```
<progress role="progressbar"
          id="progressbar-id"
          tabindex="0"
          aria-label="File upload"
          value="25"
          aria-valuemin="0"
          aria-valuenow="25"
          aria-valuemax="100"
          max="100">
          Capture d’écran 2022-11-29 à 17.03.38.png (25%)
</progress>
```
Attributs manquants sur l'implémentation actuelle :

- `aria-label` afin de donner un intitulé à barre : 
- [x] `aria-label="Chargement de fichier"` pour la version française.
- [x] `aria-label="File upload"` pour la version anglaise

- [x] `tabindex="0"` : l'élément peut capturer le focus et être atteint via la navigation au clavier

- [x] `max="100"` spécifie la valeur requise par la tâche.

2. Analyse antivirus : 
![Image](https://user-images.githubusercontent.com/49035942/216291985-d0780e6b-5610-498c-bb89-376020524577.png)

- [x] Vu ensemble : Ne pas afficher nécessairement l'information d'analyse antivirus, juste un message d'erreur lorsque le fichier a un virus.

Dans ce cas, nous pouvons utiliser l'attribut `role="status"`pour informer les technologies d'assistance

**Comment by julieSalha** [comment]
@colinux m'a informé qu'il y aurait une évolution DSFR sur ce sujet.

**Comment by colinux** [comment]
@julieSalha , 


- si on voulait conserver la mention "analyse antivirus en cours", qu'est-ce qu'il faudrait modifier pour l'a11y ? Il n'y a pas de notion de progression, c'est un status, et à l'issue le nom du fichier devient cliquable (téléchargeable)
- si on l'enlève, sur quoi porter le `role="status"`

**Comment by julieSalha** [comment]
@colinux ,

- Si on conserve la mention "analyse antivirus en cours", afin de le notifier comme un message de status, on ajoute l'attribut `role="status"` sur la balise encadrant le message
- Si on l'enlève, on peut aussi ajouter un autre message de status du type "Le fichier XXX a bien été téléchargé"
