### ISSUE TITLE
Menu principal (Critère 12.6)

### ISSUE THREAD

**Issue by julieSalha** [demarches-simplifiees/demarches-simplifiees.fr#8559]
https://www.demarches-simplifiees.fr/dossiers

Ticket valable pour la navigation principale côté usager, administrateur et instructeur : 

 - [x] Dans le menu de navigation principale "Mes dossiers" (usagers), "Mes démarches..." (admin), "Démarches" (instructeur), remplacer l'attribut `aria-current="page"` par `aria-current="true"` pour le lien actif.

Cela est recommandé quand la navigation concerne un ensemble de pages.

![Image](https://user-images.githubusercontent.com/49035942/216332497-cfeebd63-90f7-45c7-ae90-908e116cb548.png)
![Image](https://user-images.githubusercontent.com/49035942/216332498-9880ee27-df14-4677-870c-d59b78c0ed06.png)
![Image](https://user-images.githubusercontent.com/49035942/216332496-0c07c2c9-036b-4930-bbae-3138288518d6.png)

**Comment by julieSalha** [comment]
@mfo Peux-tu me "pinguer" quand c'est en PROD ? Merci

**Comment by mfo** [comment]
> @mfo Peux-tu me "pinguer" quand c'est en PROD ? Merci

Je n'y manquerai pas
