### ISSUE TITLE
Accessibilité sur les actions multiples

### ISSUE THREAD

**Issue by lisa-durand** [demarches-simplifiees/demarches-simplifiees.fr#8600]
Suite à la PR https://github.com/demarches-simplifiees/demarches-simplifiees.fr/pull/8486 - voici les retours de @julieSalha à traiter

- Les attributs `colspan` sont autorisés

- Afin d’informer les technologies d’assistance du résultat de l’action "Tout sélectionner" au clique de la checkbox placée dans l’en-tête de colonne :

- [x] Ajouter l’attribut `role="status "` sur l’information "Les XX dossiers de cette page sont sélectionnés."

- [x] Afin de respecter un ordre logique de tabulation, après l’action "Tout sélectionner", placer le focus sur le bouton "Sélectionner tous les XX dossiers."

- Plus d’informations concernant l’accessibilité du tableau en général :

- [x] Afin d’associer les cellules du tableau à leurs colonnes, ajouter l’attribut `scope="col"` sur les balises `<th>` des en-têtes de colonne (N° dossier, Demandeur…)

- [x] Pour informer les technologies d’assistance des états de tris, ajouter un attribut `aria-sort` sur ces balises : 

Exemple pour «  N° dossier»
`<th class="number-col » aria-sort="ascending">[…]</th>`
Les éléments sont triés par ordre croissant par cette colonne.

`<th class="number-col » aria-sort="descending">[…]</th>`
Les éléments sont triés par ordre décroissant de cette colonne.

`<th class="number-col » aria-sort="none">[…]</th>`
Par défaut, aucun tri défini n'est appliqué à la colonne.

- [x] Pour les checkbox de chaque ligne de dossier, privilégier un intitulé dynamique grâce à l’identifiant de chaque dossier :
Exemple : `aria-label="Ajouter le dossier XXXXXXXX à la sélection pour un traitement de masse"`

**Comment by julieSalha** [comment]
@lisa-durand je ne sais si c'est prioritaire étant donné qu'on priorise l'interface usagers :)
