### ISSUE TITLE
[ADM][Toutes les démarches] Manque une colonne sur les informations complémentaires du tableau des démarches

### ISSUE THREAD

**Issue by MickaelMa** [demarches-simplifiees/demarches-simplifiees.fr#8614]
**Décrivez le bug**
Suite au traitement de l'issue https://github.com/demarches-simplifiees/demarches-simplifiees.fr/pull/8551, il semblerait que l'ajout de la colonne n'a pas été traité dans la partie "informations complémentaires" du tableau lorsque que l'on clique sur le "+" d'une démarche

**Reproduction**
Comment reproduire le problème :
1. En tant qu'administrateur, Aller sur la page 'Toutes les démarches"
2. Cliquez sur le bouton "+" d'une des démarches
3. Une colonne blanche apparait en fin de ligne

**Comportement attendu**
Pas de colonne blanche ?

**Capture d'écran**
![image](https://user-images.githubusercontent.com/17332206/218059271-51d774fe-86ad-43d7-a420-827f94985b91.png)

**Appareil et navigateur utilisé**
 - Appareil : PC
 - Navigateur : Firefox

**Comment by colinux** [comment]
Oui, un correctif est prêt et sera prochainement déployé : #8609
