### ISSUE TITLE
Autocompletion accessible - Champ adresse et similaires (API BAN) - Création dossier (Brouillon) - Critère 7.1

### ISSUE THREAD

**Issue by julieSalha** [demarches-simplifiees/demarches-simplifiees.fr#8643]
[https://www.demarches-simplifiees.fr/dossiers/10682853/brouillon](https://www.demarches-simplifiees.fr/dossiers/10682853/brouillon)

Optimiser le rendu pour les lecteurs d'écran lors de la suggestion d'adresse grâce à l'API BAN grâce aux documentations suivantes : 

Actuellement, l'utilisateur naviguant avec un lecteur d'écran n'est pas tenu au courant de l'affichage de suggestions.

- [ACCESSIBLE AUTOCOMPLETE](http://haltersweb.github.io/Accessibility/autocomplete.html) (API BAN - Base Adresse Nationale)
- [Accessible Autocomplete examples](https://alphagov.github.io/accessible-autocomplete/examples/) (API BAN - Base Adresse Nationale)

## Keyboard Interaction

- [x] UP and DOWN: Cycles through auto-suggestions and input field.
- [x] ESC: Close the menu
- [x] ENTER: Select the currently focused auto-suggestion and close the menu.
- [x] TAB: Select the currently focused auto-suggestion, close the menu, and move focus to the next focusable element.

## Screen-reader Interaction

- [x] when the search field gains focus an initial instruction is announced.
- [x] when search results are returned the count and instructions are announced.
- [ ] when suggestions are arrowed through they are spoken aloud.

## Aria

- [x] input: aria-describedby="initInstr" aria-owns="results" aria-expanded="false" aria-autocomplete="both" aria-activedescendant=""
- [x] ul: id="results" role="listbox"
- [x] li: id="" role="option" aria-selected="false"

**Comment by colinux** [comment]
@julieSalha j'ai ajouté les instructions pour les lecteurs d'écran et l'annonce des résultats dans https://github.com/demarches-simplifiees/demarches-simplifiees.fr/pull/8677

Je sais pas si tu veux vérifier le bon comportement avant qu'on merge.

A priori le reste de l'autocompletion remplit tous les critères, d'ailleurs la lib qu'on utilise est largement orientée et maintenue par des experts a11y : https://reach.tech/combobox

**Comment by julieSalha** [comment]
Top ! Je te fais confiance :) Je referai un test quand ce sera mergé.
