### ISSUE TITLE
Démarche type - Bloc répétable (a11y)

### ISSUE THREAD

**Issue by julieSalha** [demarches-simplifiees/demarches-simplifiees.fr#8661]
https://www.demarches-simplifiees.fr/dossiers/11797555/brouillon

- [x] Employer la sémantique HTML adaptée pour un élément déclenchant une action :
Remplacer les balises `<a>` par des balises `<button>` pour les actions "Ajouter un élément pour « Bloc répétable »" et "Supprimer".

- [x] Afin de respecter un ordre logique pour la navigation au clavier, à l'ajout du bloc répétable, placer le focus sur le premier champ ajouté.
- [x] Appliquer les styles du DSFR concernés.

![Image](https://user-images.githubusercontent.com/49035942/220295875-4b7f009f-584d-45c1-8171-5aea6e85160b.png)

**Comment by tchak** [comment]
> Afin de respecter un ordre logique pour la navigation au clavier, à l'ajout du bloc répétable, placer le focus sur le bouton de suppression.
Pourquoi ne pas focus sur le premier champ du bloc ?

**Comment by julieSalha** [comment]
@tchak Oui j'y ai pensé aussi, l'un ou l'autre. Étant donné que les solutions sont multiples, j'ai pensé que sur le bouton "Supprimer" ce serait plus simple à mettre en place.

**Comment by mfo** [comment]
possible que je passe dessus aujourd'hui, sujet que j'ai déjà abordé recemment

**Comment by julieSalha** [comment]
Top :) J'ai modifié l'ordre logique pour la navigation au clavier.

**Comment by mfo** [comment]
@julieSalha , pas capté le style DSFR a appliquer. on est bon la non sur le bouton de suppression et le bouton d'ajout (des actions tertiaires)

**Comment by julieSalha** [comment]
Hello @mfo c'est top pour le positionnement du focus :)
Mes retours : 

- [ ] Retirer l'attribut `type="submit"` des boutons "Ajouter un élément pour Bloc répétable"" et "Supprimer l’élément" sauf s'ils ont utilisés pour soumettre un formulaire.
- [ ] Appliquer les styles du DSFR pour les [Champ de saisie - Input](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/champ-de-saisie)
C'est valable pour tous les champs du formulaire du même type.
<img width="786" alt="Capture d’écran 2023-04-04 à 08 07 39" src="https://user-images.githubusercontent.com/49035942/229702480-b1190561-68c5-4665-8890-45250b9514cd.png">

Dispo si besoin !

**Comment by mfo** [comment]
C'est soumis par un formulaire (les formulaires déportés), donc normal pour le type "submit"

Concernant le relooking des champs, on y est pas encore (gros taff
