### ISSUE TITLE
Démarche type - Lire plus (a11y)

### ISSUE THREAD

**Issue by julieSalha** [demarches-simplifiees/demarches-simplifiees.fr#8662]
https://www.demarches-simplifiees.fr/dossiers/11573621/brouillon

- [x] Champ Explication, bouton "Lire plus"
Appliquer un style CSS de bouton cf [la documentation du DSFR - Boutons](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/bouton).

Afin de le rendre accessible, utiliser la documentation [AcceDe Web - Boutons « Afficher plus »](https://www.accede-web.com/notices/interface-riche/boutons-afficher-plus/).

![Image](https://user-images.githubusercontent.com/49035942/220296689-bea5ad6e-801c-4d15-a896-185c9bc4a6c0.png)

**Comment by colinux** [comment]
J'ai préparé le style "bouton", en revanche pour donner le focus sur l'élément déployé, le parti pris du DSFR est justement de ne pas le donner, que ce soit pour ce type de comportement, l'accordéon etc… J'ignore pourquoi mais pour le moment je n'ai pas vraiment de solution car le code JS vient d'eux. Peut-être faut'il en parler avec eux ?

**Comment by tchak** [comment]
J'ai l'impression que c'est le pattern [disclosure](https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/) qu'on veut ici, non ?

**Comment by colinux** [comment]
@tchak c'est ça oui. Le DSFR l'implémente avec ces `fr-collapse` https://github.com/GouvernementFR/dsfr/blob/b225a086f5a578ae66c0a64b5de50086c8605143/src/core/script/collapse/collapse.js ) mais bizarrement il n'y a pas la gestion du focus

**Comment by julieSalha** [comment]
@colinux @tchak c'est une bonne idée le pattern "disclosure".
La gestion du focus est différente dans ce cas.
Voici une doc à ce sujet : [AcceDe Web - Panneaux dépliants](https://www.accede-web.com/notices/interface-riche/panneaux-depliants/)

**Comment by colinux** [comment]
@julieSalha nickel donc selon moi ma PR suffit, il n'y a qu'à gérer le style du bouton qui utilise déjà le pattern disclosure via le DSFR
