### ISSUE TITLE
Démarche type - Traduction anglaise (a11y)

### ISSUE THREAD

**Issue by julieSalha** [demarches-simplifiees/demarches-simplifiees.fr#8665]
https://www.demarches-simplifiees.fr/dossiers/11585796/brouillon

- [ ] Prévoir une traduction en anglais pour toute la page
(Textes visibles et attributs)

**Comment by colinux** [comment]
J'ai commencé à traduire le menu d'aide, je vais essayer de faire une liste des éléments propres au champs (notamment boutons du bloc répétable). Hésite pas à partager si tu as une liste de tous les éléments

**Comment by julieSalha** [comment]
@colinux Je te propose qu'on parle de la traduction en globale à la réunion de 15h :)

**Comment by julieSalha** [comment]
@colinux est-il possible de traduire en anglais l'attribut `aria-label` pour le chatbot ?

<img width="545" alt="Capture d’écran 2023-03-07 à 16 52 50" src="https://user-images.githubusercontent.com/49035942/223475408-630dd0f0-25e3-40b8-b629-d8ba00d980ec.png">

**Comment by colinux** [comment]
@julieSalha je viens de le faire, il manquait un changement de config côté crisp pour ne plus forcer le français

![Capture d’écran 2023-03-07 à 18 03 04](https://user-images.githubusercontent.com/150279/223495682-6d31aa64-10d5-4c35-b90d-08bcab31d7fa.png)

**Comment by julieSalha** [comment]
Top :)
