### ISSUE TITLE
Chatbot - a11y

### ISSUE THREAD

**Issue by julieSalha** [demarches-simplifiees/demarches-simplifiees.fr#8682]
https://www.demarches-simplifiees.fr/dossiers/11573621/brouillon

- [ ] Utiliser la sémantique HTML adaptée pour les boutons d'ouverture et de fermeture du chatbot : 
Remplacer les balises `<a role="button">` par `<button>`.

**Comment by inseo** [comment]
Service externe sur lequel les équipes n'ont pas la main.
