### ISSUE TITLE
Pièce justificative - Modèle à télécharger - a11y

### ISSUE THREAD

**Issue by julieSalha** [demarches-simplifiees/demarches-simplifiees.fr#8683]
https://www.demarches-simplifiees.fr/dossiers/11573621/brouillon

- [ ] Pour les modèles de fichiers à télécharger, apporter la même information au survol de la souris et au focus clavier: "Ce lien est éphémère..."

![Image](https://user-images.githubusercontent.com/49035942/220855572-e0f014c7-362b-4296-a014-8e3f026a9ed3.png)

**Comment by colinux** [comment]
Tu veux dire que le même texte devrait être intégré à l'attribut title ? (ou peut-être mieux à l'aria-title qui combinerait les 2, et garder le title tel quel pour les desktops ?)

**Comment by julieSalha** [comment]
@colinux j'ai créé une autre démarche pour pouvoir tester : [https://www.demarches-simplifiees.fr/dossiers/11914118/brouillon](https://www.demarches-simplifiees.fr/dossiers/11914118/brouillon)

L'idée ici c'est plutôt que ce qui s'affiche au :hover de la souris s'affiche aussi au :focus. Je ne parle pas d'attribut title. En naviguant au clavier, on doit faire apparaître la même information qu'au survol de la souris :)

**Comment by julieSalha** [comment]
@colinux Finalement, ce serait sûrement plus simple d'utiliser un attribut title pour ce type de lien : 
`title="[Intitulé du lien] - Lien éphémère à ne pas partager"`

**Comment by colinux** [comment]
OK noté. Je pense de toute façon qu'il faudrait qu'on trouve un moyen que cette information soit moins pro-éminente.

**Comment by inseo** [comment]
@colinux : Il semblerait que l'issue ne soit plus d'actualité.   
Est-ce que tu pourrais me le confirmer ?

![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/2088264/7979492f-43d2-4a25-8828-bf36eb67aac3)
