### ISSUE TITLE
Dans un champ PJ, lorsque l'usager dépose un dossier en construction avec plusieurs PJ, quand il souhaite modifier le dossier, il ne peut plus supprimer les PJ, uniquement remplacer la pj. Il faut que l'usager puisse supprimer la PJ quand il en renseigne plusieurs

### ISSUE THREAD

**Issue by Bouchralazaar** [demarches-simplifiees/demarches-simplifiees.fr#8696]
Ticket associé: https://app.crisp.chat/website/266ba25d-91d1-4774-b01f-a23ba63d662f/inbox/session_ecd1abec-6404-40b0-9819-ea8c2beaed3f/

**Comment by colinux** [comment]
On a un plan pour ça, avec une nouvelle façon de gérer les modifications des dossiers en construction. C'est pas encore pour tout de suite, mais on se rapproche.

**Comment by colinux** [comment]
Closed by #9021 9021
