### ISSUE TITLE
ETQ usager, lorsque je modifie mon dossier, je ne veux pas déposer mon dossier si les champs obligatoires ne sont pas renseignés 

### ISSUE THREAD

**Issue by Bouchralazaar** [demarches-simplifiees/demarches-simplifiees.fr#8731]
Le bug se produit quand l'usager a déposé son dossier en construction, puis retourne sur le dossier pour le modifier. Il peut supprimer les champs obligatoires et son dossier reste valide. (je suppose que ca vient du fait qu'il n'y a pas de "re-dépôt" de dossier) 

Ticket associé: https://app.crisp.chat/website/266ba25d-91d1-4774-b01f-a23ba63d662f/inbox/session_3ee89171-b4ae-45b2-8488-18d7c246d408/

**Comment by colinux** [comment]
Même cause que #8696 , et ce sera la même résolution ;)
