### ISSUE TITLE
ETQ administrateur, je veux qu'il y ait un blocage sur le champ "adresse electronique" si l'usager ne renseigne pas "@"

### ISSUE THREAD

**Issue by Bouchralazaar** [demarches-simplifiees/demarches-simplifiees.fr#8738]
A ce jour, ce champ fonctionne comme un champ "texte" classique. La case est entourée en rouge lorsque le champ renseigné est erronné mais le dépôt du dossier peut encore se faire.

**Comment by kara22** [comment]
@tchak on est d'accord que c'est le "novalidate" sur le form qui empèche la validation html du @ ?
