### ISSUE TITLE
Délai de traitement d'une demande de clé API GraphQL ?

### ISSUE THREAD

**Issue by yvestan** [demarches-simplifiees/demarches-simplifiees.fr#8758]
N'ayant pas de réponse sur https://www.demarches-simplifiees.fr et n'ayant pas d'autre moyen de contact que la messagerie associée à ma demande, je me permets de demander ici le délai de traitement d'une demande d'accès aux services ? J'ai effectué ma demande le 27 janvier et j'ai relancé le 28 février sans obtenir la moindre réponse. En vous remerciant par avance

Dossier 11292517

> Notre logiciel est utilisé par des collectivités qui nous demandent de produire des formulaires de demandes administratives s’interfaçant avec notre solution. Par exemple, une communauté d'agglomération qui souhaite un formulaire pour des demandes d'occupation du domaine public. Nous trouvons donc intéressant d'analyser la possibilité d'interaction de demarches-simplifiees avec notre logiciel

**Comment by flexbox** [comment]
@yvestan tu as testé de récupérer des emails avec https://hunter.io/search/demarches-simplifiees.fr ?

**Comment by yvestan** [comment]
> @yvestan tu as testé de récupérer des emails avec https://hunter.io/search/demarches-simplifiees.fr ?

je ne vois pas le rapport
