### ISSUE TITLE
Traductions manquantes dans le parcours usager

### ISSUE THREAD

**Issue by tchak** [demarches-simplifiees/demarches-simplifiees.fr#8827]
- [x] Page de confirmation de compte
- [x] Page de récupération de mot de passe oublié
- [x] Page de changement de mot de passe
- [ ] Email de confirmation (après changement d'email)
- [x] Champ Oui/Non
- [x] Champ pièce justificative
- [ ] Pied de page des emails : "Consulter mon dossier" / "J'ai une question"
- [ ] Email "Réactiver mon compte"
- [x] Profil - Jetons d'identification d'API

En attente pour les JO

**Comment by julieSalha** [comment]
- Page de récupération de mot de passe oublié - Page de changement de mot de passe

![Image](https://user-images.githubusercontent.com/49035942/231119588-3df51250-3e47-4163-980d-610f5432d578.png)
![Image](https://user-images.githubusercontent.com/49035942/231119587-a7b89e86-dd88-46e7-9429-9263c4c5d498.png)
![Image](https://user-images.githubusercontent.com/49035942/231119586-b35387ad-29a9-42c0-ab3e-a260c2137049.png)

- Profil - Jetons d'identification d'API
![Image](https://user-images.githubusercontent.com/49035942/231119740-dd37ca91-7eb3-476a-9fd7-c23468de2e67.png)

**Comment by julieSalha** [comment]
- Page de confirmation de compte

![Image](https://user-images.githubusercontent.com/49035942/231164352-ad060a47-502d-4a47-bf25-e20cfd961a20.png)

**Comment by tchak** [comment]
> Certaines parties d'email sont traduites en créant deux fichiers séparés, l'un en français, l'autre en anglais.

Pour les emails, je pense qu'il faut privilégier l'approche par fichier, car la découpe en clé n'est pas évidente. Par exemple, l'approche ligne par ligne est problématique car, en fonction de la langue, il peut y avoir un nombre de lignes différent. Les clés sont utilisées pour factoriser certains bouts (comme les footers).

**Comment by tchak** [comment]
> La traduction du bouton de téléchargement de fichier dépend de la langue du navigateur.

Oui, on laisse comme ça. Je l'ai expliqué aux instructeurs de JO.

**Comment by tchak** [comment]
> Email de confirmation (après changement de mot de passe)

Pardon c'est après changement d'email pas de mot de passe.
