### ISSUE TITLE
[refonte usager] Tableau de bord - Ajouter continuer à remplir dernier dossier

### ISSUE THREAD

**Issue by lisa-durand** [demarches-simplifiees/demarches-simplifiees.fr#8875]
> On affiche une alerte pour compléter un dossier si dossier en cours (brouillon / en construction…)
> 
> - si plusieurs dossiers lequel on prend ?
> --> On prend le dernier dossier ouvert (et si pas possible updated_at)
> 
> à verifier en BDD : 
> - combien y a t-il d'usager avec plus d'un dossier en cours (en brouillon ou construction) ? 

**EDIT 17 avril // changement de comportement**
- l'alerte est localisée dans l'onglet "en cours" et non plus dans le header
- il y a une notion de temps - on prend les dossiers en brouillon modifié/créé dans les 48h
- on ne prend plus les dossiers en construction seulement les dossiers en brouillon

![Image](https://user-images.githubusercontent.com/6756627/230580136-fed531d7-0dd1-4d0e-b5db-31d843e855e1.png)

**Comment by Olivier-Marcellin** [comment]
proposition :
- encart avec le titre “Vous avez début un dossier récemment”
- description avec un compteur "Il y a [n] jour…” 
- CTA Continuer à remplir 

<img width="874" alt="Capture d’écran 2023-06-01 à 17 03 53" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/101646817/eb5874f8-6c3e-42be-8c3a-a8bd0871f65f">
