### ISSUE TITLE
[refonte usager] Tableau de bord - Ajouter bouton filtres

### ISSUE THREAD

**Issue by lisa-durand** [demarches-simplifiees/demarches-simplifiees.fr#8878]
EDIT 24/04/23
- apres discussion avec Olivier et Paul, on a reposé le contexte et il faut reflechir plus globalement à une interface pour les usagers qui fonctionnerait pour les "experts" qui ont plusieurs centaines de dossiers - qui sont en souffrance aujourd'hui. Olivier travaille sur l'interface. En attendant, on a souhaité ne pas bloquer le chantier des 1ers filtres simples avec les params direct dans l'URL et les filtres direct dans l'interface (car le dropdown pas encore présent).

EDIT 18/04/23
- lire les commentaires sur cette issue - Paul parle d'une refonte plus globale du systeme de tri notamment en remettant en cause le systeme d'onglet actuel qui est deja une forme de tri "en dur"
---
Reprendre les mm filtres que instructeur ?
Voir si on peut simplifier ? / en mettre moins ?

-> a priori systeme plus simple de filtres pour les usagers.

On souhaiterait utiliser le dropdown du DSFR (pas encore de date précise pour la sortie)

Les filtres seront :
- statut (change en fonction des statuts dispo de l'onglet)
- date de creation
- date de dépot

![Image](https://user-images.githubusercontent.com/6756627/230582093-e483cb69-29c4-4d9b-92e1-0dc230e0df5b.png)

![Image](https://user-images.githubusercontent.com/6756627/232538120-122cc4ad-075f-4a3d-aebf-ceb0ed20fe77.png)

**Comment by lisa-durand** [comment]
@tchak justement je me posais la question à quel point il y avait des choses en commun et s'il fallait necessairement refactorer pour attaquer ce ticket. Car comme tu dis il y a cette histoire de complexité de démarches VS procédures mais il y a aussi à mon sens une difference d'interface. Pour les usagers, on peut faire qqchose de bcp plus simple / léger, ce n'est pas une interface d'expert et il y aura à priori 3 filtres seulement : statut / date de creation / date de dépot. Techniquement je me demande si on ne peut pas juste avoir ces filtres en params dans l'URL par exemple.

**Comment by tchak** [comment]
Mais c'est bien ce qui m'embête dans le design actuel. Nous avons une demande très forte pour toute une catégorie d'usagers d'avoir accès à des filtres plus riches (aussi riches que ceux des instructeurs). Je n'ai pas de problème avec le fait que dans la v1, on reste sur quelque chose de simple, mais nous avons besoin d'avoir un chemin pour évoluer vers une interface plus riche dans certains cas (par exemple, comme nous avons discuté, basé sur le nombre de dossiers d'un usager).

Après oui, pour une v1 probablement c'est bien de partir sur des filtres avec juste un param dans l'url

**Comment by tchak** [comment]
Si l'on fait un filtre par état du dossier, on réintroduit le problème que nous avons déjà sur l'interface instructeur. Par exemple si je veux trouver tous les dossiers (peu importe leur état) qui ont été déposés depuis hier – c'est impossible avec cette interface car le filtre des états est "en dur" dans l'onglet. C'est un problème et une source d'incompréhension constante dans la vue instructeur. La proposition qui a été évoquée est de rendre les onglets paramétrables. On pourrait créer les onglets par défaut avec des filtres préconfigurés avec les options que l'on pense être pertinentes pour la magorité des utilisateurs et ensuite laisser les utilisateurs modifier ou ajouter leurs propres onglets.

Je suis désolé d'être ennuyeux, mais j'ai l'impression que nous oublions beaucoup des demandes qui étaient à l'origine de la demande de redesign. C'est super que nous allons améliorer l'expérience des utilisateurs avec peu de dossiers, mais cela fait maintenant 2 ans que l'on nous dit que les utilisateurs avancés avec beaucoup de dossiers sont en souffrance. Alors, d'accord, ils ne sont pas nombreux en proportion, mais nous avons promis de nous en occuper à de multiples reprises.

cc @Olivier-Marcellin

**Comment by tchak** [comment]
Statistiques sur le nombre de dossiers par usager :

110 users > 1000 dossiers  
4 000 users > 100 dossiers  
70 000 users >= 10 dossiers  
3 500 000 users < 10 dossiers

cc @Olivier-Marcellin
