### ISSUE TITLE
[refonte usager] Tableau de bord - Changer design de tableau à tuiles

### ISSUE THREAD

**Issue by lisa-durand** [demarches-simplifiees/demarches-simplifiees.fr#8882]
à compléter : 
- est-ce qu'on peut utiliser autant d'elements dans une tuile : boutons etc…
--> Pas forcément le bon composant ? Plutot utiliser une carte ? Si ça marche pas créer qqchose de custom
- est-ce qu'on est sur de vouloir mettre l'image de la demarche ?
--> pas forcément / c'est un petit plus
- en terme de comportement - qu'est-ce qui est nouveau en terme de tags, d'infos, d'actions : pour pouvoir redecouper en tickets pour les nouvelles actions et faire cette refonte au minimum avec ce qui existe déjà
--> nouveautés ce qui est lié au SVA : "à corriger" + "jours restants"
-  qu'est ce que le statut en "test" / uniquement pour admin ?
- quid de l'action et de l'info transfert "demande en cours" + "action de la révoquer"

aujourd'hui : 
<img width="1050" alt="Capture d’écran 2023-04-07 à 15 43 42" src="https://user-images.githubusercontent.com/6756627/230619117-d014402a-68a6-47b1-987c-5936292ef84b.png">

-  Comment on accède au détail de la démarche ?
![Image](https://user-images.githubusercontent.com/6756627/230584091-8ebbf2f5-1106-4256-9331-f6a631aef298.png)

**Comment by Olivier-Marcellin** [comment]
la proposition est la suivante : 
- on utilise pas le composant dsfr tuile le design est spécifique
- on met en avant le titre de la démarche et le numéro de dossier
- la date de création, de dépôt, la mise à jour
- si le dossier est partagé on mention le nom et prénom de la personne
- on utilise le composant badge pour le statut (sous le numéro de dossier)
- le CTA Continuer à remplir (si statut brouillon) ou Modifier le formulaire (si statut En construction) est visible (sorti du CTA Autres actions)
- lorsque le dossier est en instruction seul le menu Autre actions est actionnable et le CTA Modifier le formulaire est désactivé
- Dans Autres actions, l'usager peut demander le transfert, créer un nouveau dossier, dupliquer le dossier, supprimer le dossier (action supplémentaire pour la suppression via une popin “Voulez-vous vraiment supprimer le dossier ?” Valider la suppression/Annuler)
- zone d'alerte et badge à corriger si une correction SVA est nécessaire (cas SVA)
- zone d'information pour les démarches clôturées qui ne peuvent pas faire l'objet d'un nouveau dépôt du dossier

**Comment by Olivier-Marcellin** [comment]
@Bouchralazaar quid de l'action et de l'info transfert "demande en cours" + "action de la révoquer" pour le dossier de l'usager ?
