### ISSUE TITLE
[refonte usager] Tableau de bord - Ajouter label jours restants

### ISSUE THREAD

**Issue by lisa-durand** [demarches-simplifiees/demarches-simplifiees.fr#8884]
Ajouter le nb de jours restants + remonter le badge dans la carte.

Quel fonctionnement ?
- 1er cas de figure : deadline de dépot de la démarche ? Est-ce que toutes les démarches ont un délai ?
- 2e cas de figure : laps de temps apres le depot pour pouvoir modifier son dossier avant instruction 

![Image](https://user-images.githubusercontent.com/6756627/230618729-6ed8d1da-ce87-4712-8a40-6d70f04c082a.png)

**Comment by colinux** [comment]
La partie "jours restants" et "en attente" c'est du sva, j'ai une branche dessus (mais sur l'ancien design pour le moment)

**Comment by Olivier-Marcellin** [comment]
@colinux est-ce que la réflexion a avancée là-dessus ?

**Comment by lisa-durand** [comment]
@Olivier-Marcellin du coup ici il ne s'agirait que du SVA ? Car pour moi il s'agissait d'autres délais : deadline de la demarche etc…
Et il me semble que pour la partie SVA le nb de jours restants est uniquement pour les instructeurs - donc c'est encore autre chose et ça n'a rien avoir dans la partie "refonte usager tableau de bord". Du coup je ne comprends pas bien de quoi traite cette issue. Et s'il faut au final la supprimer ?

**Comment by colinux** [comment]
Déso j'avais zappé les pings sur github

- un dossier "à corriger", c'est pour tout le monde (indépendant du SVA), et il n'y a pas de deadline. Le dossier est en construction quand il est à corriger, et actuellement c'est via un commentaire que l'instructeur communique les corrections à faire (visible aussi dans la messagerie, via le modèle `DossierCorrection`) . Ça ne me semble pas en lien avec cette issue

- un dossier soumis au SVA: l'instructeur voit le nombre de jours restant ; mais pour l'usager c'est peut-être plus parlant de lui mettre la date butoir de décision, qui correspond à la date au plus tard à laquelle il aura des nouvelles pour son dossier (soit le dossier a été accepté automatiquement à cette date là, soit un instructeur est intervenu auparavant, pour l'accepter/refuser manuellement ou lui demander des corrections). C'est date n'est pas figée et évolue au guise des corrections demandées.

La seule deadline à laquelle je pense côté usager c'est si la démarche a une date prévisionnelle de cloture, et qu'elle est proche dans le temps: l'usager doit déposer son dossier avant cette date. C'est l'attribut `auto_archive_on` de a démarche, à 23:59.

**Comment by Olivier-Marcellin** [comment]
le design de la tuile va encore changer, donc on ferme ce ticket et on fera un nouveau ticket lorsque ce sera plus avancé
