### ISSUE TITLE
ETQ administrateur , je souhaite prévisualiser la démarche depuis l'interface "toutes les démarches"

### ISSUE THREAD

**Issue by CamilyaDellali** [demarches-simplifiees/demarches-simplifiees.fr#8969]
Ajouter un bouton "prévisualiser". 
Actuellement, les administrateurs ne peuvent que cloner la démarche sans la visualiser en amont.

**Comment by kara22** [comment]
@CamilyaDellali  Salut Camilya, est-ce qu'il existe un autre endroit dans l'app ou on peut prévisualiser les démarches ?

**Comment by CamilyaDellali** [comment]
Hello @kara22  , oui en cliquant sur "nouvelle démarche" depuis la liste des démarches clonables ( d'ailleurs, elle a vocation à être supprimé) . Les admins peuvent consulter les démarches
![image](https://user-images.githubusercontent.com/82160230/235678261-18f206bf-97d2-4d3f-8d4a-152d266a6e31.png)

**Comment by kara22** [comment]
![Image](https://user-images.githubusercontent.com/21340608/235869584-a6d11573-471d-4339-8d9a-013257b504bb.png)

@CamilyaDellali
