### ISSUE TITLE
[refonte usager] Tableau de bord - Regrouper les dossiers d’une même démarche

### ISSUE THREAD

**Issue by lisa-durand** [demarches-simplifiees/demarches-simplifiees.fr#8982]
> A verifier combien de dossiers dans la mm demarche ? CF: auto-ecole ? Car si plus de 20 difficile à implementer car pas de possibilité de pagination…

Pour faciliter la recherche pour les usagers avec bcp de dossiers, on regroupe les dossiers s'il font partie de la mm demarche.

A partir de 2 dossiers de la mm demarche, un bouton apparait et permet de deplier et faire apparaitre l'ensemble des dossiers.

Si dans ces dossiers "cachés" il y a des dossiers en brouillons, on ajoute un compteur avec une mention "n dossier à continuer à remplir" (voir capture)

<img width="573" alt="Capture d’écran 2023-05-04 à 18 26 46" src="https://user-images.githubusercontent.com/6756627/236266150-4225bf34-729b-47e0-bde1-b1ab92766c7b.png">

**Comment by lisa-durand** [comment]
@Olivier-Marcellin j'ai créé une issue pour faire un filtre par démarche comme évoqué à la dernière réunion - il me semble que cette issue n'est donc plus d'actualité. Je te laisse la fermer si c'est bien le cas !

https://github.com/demarches-simplifiees/demarches-simplifiees.fr/issues/9207

**Comment by Olivier-Marcellin** [comment]
je confirme on ferme
