### ISSUE TITLE
ETQ usager je suis guidé dans le remplissage des champs du formulaire à l'aide de textes de description

### ISSUE THREAD

**Issue by Olivier-Marcellin** [demarches-simplifiees/demarches-simplifiees.fr#9009]
Données : avons-nous des données sur le nombre d'erreurs que font les usagers en remplissant les formulaires, par exemple auprès des instructeurs ? avons-nous des données sur des problèmes de remplissages dont la cause serait une incompréhension des textes de description des champs ?

Irritants : avons-nous des remontées côté admin pour aider les usagers dans le remplissage des champs du formulaire avec des textes de descriptions

Proposition : Guider les usagers dans le remplissage des champs unitaires du formulaire à l'aide de texte de description suffisamment explicites et compléter lorsque c'est nécessaire par des exemples. Et côté admin, disposer de ces textes dans le configurateur de champs.

Objectifs :
• Limiter les erreurs de saisie lors du remplissage du formulaire
• Répondre aux enjeux d'accessibilité pour les personnes en situation de handicap
• Guider les usagers pour saisir des données particulières, par exemple le numéro Iban qui comporte X nombre pour la France

Styles de caractères pour le DSFR :
- typo : Marianne Regular 12/20 
- couleur : light/text/mention-grey (#666666)
- positionnement : visible sous le label du champ
- composition du texte de description : emploi du présent simple et directe et avec un exemple si nécessaire : “Renseignez une adresse, une voie, un lieu-dit ou une commune. Exemple : 11 rue Réaumur Paris”

Comportements :
- le texte de description est pré-rempli dans le configurateur de champ (champ description pour chacun des types de champs concernés) 
- ceux-ci peuvent être complétés par d'autres informations par l'admin dans la configuration
- ils ne peuvent pas être supprimés ou modifiés (à voir) par l'admin.
- tous les types de champs n'ont pas de textes de description, par exemple, c'est inutile pour les types de champs nom et prénom, pour les cases à cocher, etc. 

Maquette Figma de l'ensemble des textes dans la page Styles et comportements des types de champs : https://www.figma.com/proto/YKcafywdYhT6ABFlmy5d56/Am%C3%A9lioration-vue-usagers?page-id=1%3A2&type=design&node-id=2514-112880&viewport=-12866%2C-28835%2C0.8&scaling=min-zoom&starting-point-node-id=2111%3A

Exemple :
<img width="666" alt="Capture d’écran 2023-05-05 à 14 54 46" src="https://user-images.githubusercontent.com/101646817/236462942-a14190d5-90c2-4871-824a-86d961ca4f11.png">

**Comment by mfo** [comment]
mettre les textes de description par default dans le form builder
```

email: "Format attendu : nom@domaine.fr"
phone: "Le numéro de téléphone saisi doit être valide"
address: "Saisissez une adresse, une voie, un lieu-dit ou une commune. Exemple : 11 rue Réaumur Paris "
communes: "Renseignez le code postal de la ville puis, ensuite, sélectionnez la commune dans la liste"
departements: "Renseignez le code ou le nom du département"
regions: "Renseignez la région"
pays: "Renseignez le pays"
epci: "Renseignez l'EPCI"
iban: "Exemple (France) : FR76 1234 1234 1234 1234 1234 123"
siret: "Saisissez 14 chiffres sans espaces"
text: 
textarea: "Redimensionnez le champ pour saisir plus de lignes"
decimal_number: "Vous pouvez saisir jusqu’à 3 décimales après la virgule"
date: "Format attendu : JJ/MM/AAAA. Exemple : 01/12/2022"
datetime: "Format attendu : JJ/MM/AAAA HH:MM. Exemple : 01/12/2022 12:00"
titre_identite: "Taille maximale : 20 Mo. Formats supportés : jpg, png. Uniquement le recto seul. Carte nationale d’identité, passeport, titre de séjour ou autre justificatif d’identité."
rna: "Format attendu : X123456789. Exemple : W503726238"

```

**Comment by Olivier-Marcellin** [comment]
quelques remarques :

email : peut-on remplacer le libellé par “Adresse électronique” peut-on compléter le texte de description par ”L’adresse électronique saisie doit être valide. Format attendu : nom@domaine.fr” ?

communes : au singulier, sauf si on peut renseigner plusieurs communes ? ce champ pose problème, remontée au support, on va en discuter avec Camiliya, à mon avis le problème est que on demande à l'usager de saisir le code postal puis la commune dans un sélect, mais le libellé du champ est “Commune” donc il s'attend à devoir saisir la commune… 

departements : idem, au singulier ? est-ce qu'on peut renseigner le code aujourd'hui ? (évolution de ce champ avec de l'auto-complétion pour saisir indifféremment soit le code soit le département, dans le cas contraire le texte de description devrait être “Renseignez le département”

EPCI : peut-on préciser le libellé par “Département de l’EPCI”, aujourd'hui le texte de description est “Renseignez le nom du département de l’EPCI” à vérifier si c’est bien le département qu’on demande (intercommunalité)

Iban : peut-on préciser le libellé “Numéro IBAN” et composer Iban en capitale ? 

SIRET : idem, peut-on préciser le libellé “Numéro SIRET” ? 

Nombre entier : j'ai ajouté un texte de description là aussi pour mieux guider l'usager et éviter/limiter les erreurs : “Saisissez un nombre entier sans décimale ni fraction”

decimal_number : peut-on préciser le texte de description pour la traduction “You can enter up to 3 decimal places” (ou autre traduction si la mienne n'est pas parfaite)

Date : micro détail peut-on avoir l'année dans l'exemple en cours 01/12/2023 et que l'exemple se mette à jour ?

Datetime : idem que pour Date

Choix multiples : j'ai ajouté un texte de description là aussi pour lever une possible erreur (ne saisir que un seul choix alors que l'usager peut saisir un ou plusieurs) : “Cochez un ou plusieurs choix”

Deux menus déroulants liés : on a oublié ce type de champs je propose le texte de description suivant “Renseignez une option dans la liste” et l'erreur qui va avec “Le champ n’est pas valide. Sélectionner une option”, au passage j'ai revu le comportement de ce type de champ
<img width="300" alt="Capture d’écran 2023-05-18 à 13 05 16" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/101646817/4faace84-b16d-4915-8b2f-00bbb49d3d23">

Lien vers un autre dossier : je ne comprends par l'intitulé de ce type de champ pourquoi lien ? j'ai vérifié le type de champ est un champ de saisie avec à l'intérieur indiqué “Numéro de dossier”, c'est un numéro qui est demandé pas un lien (= ambiguïté entre lien URL et lien entre dossiers) aussi pouvons-nous changer le libellé par “Numéro de dossier” (ou une autre proposition plus claire) avec le texte de description : “Saisissez un numéro de dossier valide” et le message d'erreur qui va avec “Le champ n’est pas valide. Saisir un numéro de dossier valide”
<img width="550" alt="Capture d’écran 2023-05-18 à 13 06 34" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/101646817/e1745d3f-d7a7-4884-adce-f097c09f22a9">

Carte : j'ai commencé à retravailler ce champ, voici une capture écran avec les textes
<img width="760" alt="Capture d’écran 2023-05-18 à 13 13 43" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/101646817/b6a7845a-f5eb-475c-bfb6-3d04ae373cb1">
<img width="548" alt="Capture d’écran 2023-05-18 à 13 14 06" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/101646817/f35841ac-acc2-499a-91b5-214beecb24e4">

**Comment by LeSim** [comment]
super seed par #9497
