### ISSUE TITLE
ETQ usager je suis guidé dans le formulaire lorsque les champs sont obligatoires ou facultatifs

### ISSUE THREAD

**Issue by Olivier-Marcellin** [demarches-simplifiees/demarches-simplifiees.fr#9013]
Check point de l'intégration :

- [x] astérisque après le label du champ avec une espace

- [x] mention “facultatif” entre parenthèses pour les types de champs notifiés non obligatoire par l'admin.

- [x] à l'inverse, astérisque ou mention facultatif entre parenthèses avant le label – pour les types de champs cases à cocher – avec une espace (but = rapprocher l'astérisque de la case à cocher pour une meilleure lisibilité lorsque le label est long, comme par exemple pour les notifications à valider en fin de formulaire)

- [ ] astérisque de la même couleur que le label (couleurs dsfr : défaut #161616 succès #18753C erreur #CE0500)

- [x] mention à faire porter en début de formulaire dans le composant dsfr “Alerte” état “Information”

- [ ] mention à faire porter sur les pages de connexion : “Sauf mention contraire, tous les champs sont obligatoires.” et les champs identifiant et mot de passe n'ont pas d'astérisque (par défaut sont obligatoires)

Données : avons-nous des données sur le ratio champs obligatoires/facultatifs configurés par les admin ? avons-nous des données sur la part des usagers en situation de handicap (un ratio) ?

Irritants : avons-nous des retours côté admin et instructeurs sur les champs mal remplis lorsque obligatoire et facultatifs ?

Accessibilité : pouvons-nous écouter avec un lecteur d'écran un label obligatoire ?

DSFR : Préalable avant de passer en prod : refaire le point pour valider la mise en page ci-dessous

Objectifs : répondre aux enjeux d'accessibilité pour les champs notifiés obligatoires et facultatifs sachant qu'il y a plusieurs recommandations, j'ai pris en compte celle données par le DSFR et les recommandations générales soit la mention astérisque sur chaque champ unitaires lorsque obligatoires et la mention entre parenthèses facultatif pour les champs non obligatoires.

Règles DSFR : la couleur doit être identique dans un bloc texte, donc en noir pour l'astérisque et en rouge lorsque est en erreur
Le composant Alerte (Information) est ajouté en haut du formulaire avec la mention suivante : Sauf mention contraire, les champs précédés d’une astérisque ( * ) sont obligatoires.  Votre dossier est enregistré après chaque modification, vous pouvez à tout moment fermer la fenêtre et reprendre plus tard là où vous en étiez.

Styles : l'astérisque est collé au label (pas d'espace) (à vérifier : les lecteurs de mots verbalisent l'espace quand il y en a une, c'est pourquoi j'ai supprimer ce qui donne à entendre : label* (label astérisque)

Maquette Figma sur Styles et comportements des types de champs : https://www.figma.com/proto/YKcafywdYhT6ABFlmy5d56/Am%C3%A9lioration-vue-usagers?page-id=1%3A2&type=design&node-id=2681-125753&viewport=-12866%2C-28835%2C0.8&scaling=min-zoom&starting-point-node-id=2681%3A125753&show-proto-sidebar=1

Exemple de champs obligatoires et facultatifs :

![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/101646817/a4410010-1805-452e-96c0-aff7f66114c1)

**Comment by Olivier-Marcellin** [comment]
Et un second cas particulier de mise en page des champs obligatoires : sur la page de connexion à DS, j'ai ajouté la mention “Sauf mention contraire, tous les champs sont obligatoires.” mais je n'ai pas mis les astérisques sur les champs
<img width="304" alt="Capture d’écran 2023-05-09 à 15 41 48" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/101646817/6b3e70d3-9b74-48de-84ce-43628eddca49">

Maquette Figma : pages de connexion dans le parcours usagers : https://www.figma.com/file/YKcafywdYhT6ABFlmy5d56/Am%C3%A9lioration-vue-usagers?type=design&node-id=1%3A2&t=UZtcplhUPWliiSzW-1

**Comment by Olivier-Marcellin** [comment]
Cas général des champs obligatoires en erreurs : l'astérisque est de la même couleur que le libellé du champ (#CE0500)
Idem dans le cas d'un succès (#18753C)
<img width="527" alt="Capture d’écran 2023-05-09 à 15 45 41" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/101646817/709e8346-173e-4542-bd86-46be58819eb4">
<img width="542" alt="Capture d’écran 2023-05-09 à 15 51 21" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/101646817/68a391d5-cbdd-4d46-926d-cfd0e50b148f">

**Comment by kara22** [comment]
@Olivier-Marcellin c'est compliqué à mettre en place dans l'ancienne spécifiquement pour les cases à cocher et aussi le sign in. Pour ces deux derniers, est-ce qu'il ne faudrait pas passer l'interface usager au DSFR ?

**Comment by kara22** [comment]
Est-ce qu'il ne faut pas bosser pour passer petit à petit au DSFR sur l'interface usager @Olivier-Marcellin ?

**Comment by Olivier-Marcellin** [comment]
c'est la prochaine étape de passer les champs au dsfr, donc soit on le fait maintenant soit après

**Comment by Olivier-Marcellin** [comment]
j'ajoute également les mentions à faire porter sur les pages pour les champs obligatoires :

À faire figurer sur les pages de formulaires et toutes les pages qui nécessitent des champs obligatoires

![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/101646817/e279cba5-e727-49cc-88b8-443b8b1de3f4)

**Comment by Olivier-Marcellin** [comment]
et j'ajoute également la mention à faire figurer sur les pages de connexion et de création de compte.

Remarque : sur les champs des pages de connexion l'astérisque n'est pas présente

![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/101646817/a00023d7-2b60-4eb4-b0a0-986fafe4954d)

**Comment by julieSalha** [comment]
@Olivier-Marcellin @kara22 Pour répondre à vos questions : 

- Dans un label, on peut laisser un espace entre le label et l'étoile (*), le lecteur d'écran ne vocalise pas l'espace
- Pour que les lecteurs d'écran vocalisent les champs obligatoires, on utilise les attributs html `required="required"` (utilisé sur DS car il est mieux compatible avec d'anciens navigateurs), on peut aussi utiliser `required` ou `aria-required="true"`

Après avoir échangé avec plusieurs membres de l'équipe, la refonte des champs devrait être revue d'un point de vue globale. On pourra prévoir un point d'équipe.

**Comment by tchak** [comment]
Voici ce que dit DSFR :

>Champ obligatoire
>
>Etant donnée qu’il faut limiter le nombre d’information à demander aux utilisateurs, les informations optionnelles doivent être limitées au maximum. Ainsi, les champs sont obligatoires par défaut, et les champs optionnels apparaissent avec une information “(optionnel)” dans le label.
Une mention explicative doit se trouver au dessus du formulaire afin d’en informer l’utilisateur : “Sauf mention contraire “(optionnel)” dans le label, tous les champs sont obligatoires“

**Comment by Olivier-Marcellin** [comment]
je réagis à nouveau à propos des astérisques pour le cas spécifique des cases à cocher seules, j'ai regardé ce qui se fait autre part, et on retrouve bien l'astérisque y compris lorsqu'il s'agit de valider l'action, car on peut avoir le cas où il y a plusieurs cases à cochers seules à la suite, et dans ces cas, comment différencier celles qui sont obligatoires et celles facultatives, j'ai peur que si on ne met pas l'astérisque on va perdre l'usager et d'autre part pour l'accessibilité, qu'en penses-tu @julieSalha ? ou alors il faut revoir les règles d'utilisation de ces cases pour les admin.
