### ISSUE TITLE
[Refonte page accueil demarche] Infos sur les delais d'instruction

### ISSUE THREAD

**Issue by lisa-durand** [demarches-simplifiees/demarches-simplifiees.fr#9066]
à valider par l'équipe la remontée des délais d'instruction (quelles sont les règles ?)

Est-ce qu'il y a des choses reglementaires sur les delais ?
Est-ce que c'est un select ou un champ libre ?
est-ce que ça change si SVA ou non ?

![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/329b06f9-a8f8-4533-98cf-79e66c98ffdd)

![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/cecd0502-f422-407e-b396-88792ea902bf)

**Comment by lisa-durand** [comment]
@Olivier-Marcellin Du coup, qu'est-ce qu'on fait sur ce ticket ? 
1- on le modifie pour le remplacer parce ce que propose Bouchra (“Quelles sont les étapes après l'instruction du dossier”)
2- on le ferme et on ne le fait pas car les informations sur la suite sont données au dépot du dossier.

Je suis plutot d'avis du 2/ -> pour ne pas trop alourdir la page d'accueil qui va avoir déjà pas mal d'infos au final

**Comment by LeSim** [comment]
Coucou, désolé de ne découvrir le sujet que maintenant.

Il se trouve qu'on a des [stats](https://www.demarches-simplifiees.fr/statistiques/aide-projet-fonctionnement_creation-artistique) sur le traitement des dossiers d'une procédure mais elles sont cachées dans un lien `Voir les statistiques de la démarche` du [footer](https://www.demarches-simplifiees.fr/statistiques/aide-projet-fonctionnement_creation-artistique)

Que pensez-vous déplacer ce lien dans une des sections de l'accordéon, voir mm de transférer l'ensemble de la page statistiques ?

ping @lisa-durand @Olivier-Marcellin

**Comment by lisa-durand** [comment]
ça me parait une bonne idée ! Si on combine la proposition de @Bouchralazaar et @LeSim ça ferait qqchose comme :
- on garde l'intitulé pour l'accordéon "quels sont des délais d'instruction pour cette démarche ?"
- Texte à l'interieur: "Habituellement, les dossiers de cette démarche sont traités dans un délai de 8 mois. Cette estimation est calculée automatiquement à partir des délais d’instruction constatés sur 90% des demandes qui ont été traitées lors des 30 derniers jours. Le délai réel peut être différent. Pour plus d'informations, vous pouvez consulter la page statistiques de cette démarche.

ça vous irait comme ça ?

**Comment by Olivier-Marcellin** [comment]
je trouve ça très bien @lisa-durand as-tu besoin de maquette ? de test ? merci
