### ISSUE TITLE
[refonte page accueil demarche] ajouter encart SVA

### ISSUE THREAD

**Issue by lisa-durand** [demarches-simplifiees/demarches-simplifiees.fr#9068]
Encadré (composant dsfr “Mise en avant” avec icône information et couleur de fond #F5F5FE à faire figurer lorsque la démarche est en SVA)

![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/3e49e8b8-466e-4b66-9395-19c0863a7570)

**Comment by lisa-durand** [comment]
Hello @colinux - est-ce qu'il y a une issue pour le SVA - car ce ticket est dépendant de cette fonctionnalité.
On aurait également besoin de toi pour nous aider à completer le lorem avec du vrai texte. Merci !

**Comment by colinux** [comment]
@lisa-durand Hello, pas de branche SVA pour ce ticket spécifique (mais je vais la commencer cette semaine). En revanche yen a une liée aux dossiers en construction qui contient pas mal de choses, mais rien de ta meta issue

**Comment by Olivier-Marcellin** [comment]
Colin a rédigé un texte sur le fonctionnement du SVA/SVR pour lequel nous pourrions reprendre le premier paragraphe qui explique de quoi il s'agit : 

Le SVA «Silence vaut accord » ou SVR « Silence vaut rejet » est un principe législatif qui définit le comportement d’une demande en cas de silence de l’administration : soit la demande est automatiquement acceptée (SVA), soit elle est automatiquement rejetée (SVR). Démarches-simplifiees.fr permet l’application de ce principe pour les démarches concernées.

**Comment by lisa-durand** [comment]
@Olivier-Marcellin - cette issue sera fait dans le cadre du SVA bien entamé par @colinux ici #9104
