### ISSUE TITLE
En tant qu'instructeur, je veux pouvoir générer moi-même le lien de connexion sécurisé

### ISSUE THREAD

**Issue by Bouchralazaar** [demarches-simplifiees/demarches-simplifiees.fr#9083]
Il faudrait que l'instructeur puisse se renvoyer le lien sécurisé qui lui permet de se connecter à son interface instructeur sans avoir à passer par le support. 
Il y a aussi un sujet UX à aborder. 

Voici le parcours de première connexion instructeur que j'ai pu tester: 
Etape 1: réception de l'email après avoir été rajouté à une démarche par un admin
![Capture d’écran 2023-06-23 à 05 24 42](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/89633115/f715600a-2c0d-4348-80e5-fb0be168103b)

Etape 2: en cliquant sur le lien, j'arrive sur cette page (config mot de passe ?) j'ai l'impression que cet écran s'affiche car j'ai déja un autre compte.. à vérifier
![Capture d’écran 2023-06-23 à 05 24 52](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/89633115/05546a44-a7a9-4156-abb8-f3023b132368)

Etape 3: accès à la démarche: 
![Capture d’écran 2023-06-23 à 05 25 06](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/89633115/cfb9ec02-f760-45a4-9b0e-78c5c07dab61)

Etape 4: je me déconnecte et en repassant par le lien d'activation, le lien est expiré (au bout de 2,3 minutes)
![Capture d’écran 2023-06-23 à 05 25 47](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/89633115/70dc7d89-04c6-41d2-a68a-98670d26f077)

Etape 5: ils nous contactent sur le support: 

![Capture d’écran 2023-06-23 à 05 25 57](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/89633115/3184337b-6028-4fbf-b140-5a63ffa1117d)

**Comment by Olivier-Marcellin** [comment]
besoin de revoir les parcours :

aujourd'hui comment est-ce que l'instructeur se connecte de façon sécurisé ?
il y a t-il dans le parcours une distinction entre instructeur et les autres utilisateurs ?
il y a t-il une pag de profil spécifique pour l'instructeur ?

la solution est à priori ajouter un bouton d'action dans la page de profil de l'instructeur lui permettant de recevoir le lien à nouveau pour se connecter seul

**Comment by mfo** [comment]
<img width="619" alt="Screenshot 2023-06-26 at 4 36 39 PM" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/125964/5b024f58-0496-4ca4-88db-4b4fd1125bfa">
@Olivier-Marcellin nous suggere le bon wording

**Comment by Olivier-Marcellin** [comment]
voici la proposition de nouveau parcours d'activation de compte et de connexion pour les instructeurs : 
https://www.figma.com/proto/YKcafywdYhT6ABFlmy5d56/Amélioration-vue-usagers?page-id=1%3A2&type=design&node-id=3878-142695&viewport=6757%2C-11587%2C0.39&scaling=min-zoom&starting-point-node-id=3878%3A142695&show-proto-sidebar=1&mode=design

ceci résout l'irritant suivant : qui doit résoudre l'irritant ETQ instructeur lorsque j'ai déjà activé mon compte et que je clique à nouveau sur le lien un message d'erreur m'indique de m'adresser au support (et je ne sais pas comment me connecter = KO)

dans ce nouveau parcours l'instructeur active son compte (il doit créé son mot de passe, son mail est celui que l'admin a saisi) depuis le lien d'activation
puis il reçoit un lien de connexion (renouvelé chaque mois)
il se connecte avec ses identifiants (j'ai rajouté le code OTP en prévision d'évolutions)
il peut recevoir un lien d'activation depuis sa boite mail lorsqu'il se connecte
en gestion des erreurs :

si il clique sur le lien d'activation alors qu'il a déjà un compte il est averti par une page et il reçoit un nouveau lien de connexion
si il clique sur un lien de connexion périmé depuis un mois, il est averti par une page et il reçoit un nouveau lien de connexion (et il doit ensuite se connecter)

dans l'attente de vos commentaires 

à suivre : donner à tester à un échantillon représentatif d'instructeurs voir admin/instructeurs

**Comment by Olivier-Marcellin** [comment]
en résumé, voici la préconisation ergonomique : 

le lien d'activation ne doit servir que pour cela, ensuite le parcours doit basculer vers la connexion, pour cela il est nécessaire 1) de guider l'utilisateur (via un message de confirmation) 2) automatiser l'envoi du mail de connexion 3) si pas reçu pouvoir le renvoyer (bouton de renvoi sur la page de confirmation) 4) enfin, pouvoir se connecter depuis le lien de connexion, ci-joint les écrans correctifs (ps ne pas tenir compte de l'évolution graphique charte dsfr)


![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/101646817/e7eed9c4-2a39-4b8d-97a3-53bdbfe2fcd1)

![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/101646817/8cd2c2a0-2ba1-470b-80b5-643109eb8731)

En attente de vos retours pour pouvoir passer à un test utilisateurs, merci
