### ISSUE TITLE
[Tableau de bord instructeur] ETQ instructeur je peux retrouver facilement les démarches ouvertes en cours d'instruction

### ISSUE THREAD

**Issue by Olivier-Marcellin** [demarches-simplifiees/demarches-simplifiees.fr#9141]
- [ ] classement des démarches ouvertes dans le tbd instructeur

Irritant remonté par un admin et instructeur (préfet de l'Aveyron) sur helpscout
remarque : il a été proposé à l'utilisateur de remonter son irritant sur la plateforme : https://demarches-simplifiees.featureupvote.com/

Verbatim utilisateur :

“J’utilise régulièrement "Démarches simplifiées" soit en tant qu'administrateur soit en tant qu'instructeur.
Je vous écris pour vous suggérer une petite amélioration.
Quand je suis en instructeur, je retrouve la liste des démarches (anciennes démarches en test, démarches ouvertes, démarches closes).
Je suis obligé de chercher dans la liste les dossiers en cours que je dois instruire dans les démarches ouvertes.
C'est assez fastidieux car les démarches en haut de la liste sont les anciennes démarches qui ont été testées.
Ce qui serait très bien, ce serait d'avoir en haut de liste les démarches ouvertes en cours d'instruction ou bien pouvoir les monter et descendre afin de les classer.
Merci de prendre en compte si possible ma suggestion.
Bien cordialement”

Proposition d'amélioration à prototyper :

- Soit la possibilité de filtrer les démarches en cours d'instruction dans le tbd
- Soit afficher de façon séparée les démarches en cours des démarches anciennes

**Comment by colinux** [comment]
Je m'occupe de l'extraction de ces données

**Comment by colinux** [comment]
Version graphée des données :

> 27% des instructeurs n'ont qu'1 démarche ; moins de 5% en ont 10 ou +, mais ça représente + de 2000 instructeurs

![Capture d’écran 2023-06-21 à 18 42 40](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/150279/f6f35628-c087-4b74-ac62-0bee43ccf3ae)


> 22% des instructeurs ne sont pas admins , 68% sont admins d'une démarche
![Capture d’écran 2023-06-21 à 18 42 33](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/150279/eb24ec4e-c404-460f-a6cf-88a2e9bb0ae4)
