### ISSUE TITLE
[Refonte tableau de bord] ETQ instructeur je peux remonter les dossiers en cours d'instruction dans le tableau de bord

### ISSUE THREAD

**Issue by Olivier-Marcellin** [demarches-simplifiees/demarches-simplifiees.fr#9233]
Cet irritant a été remonté par un usager 

Bonjour,
J'utilise régulièrement "Démarches simplifiées" soit en tant qu'administrateur soit en tant qu'instructeur.
Je vous écris pour vous suggérer une petite amélioration.
Quand je suis en instructeur, je retrouve la liste des démarches (anciennes démarches en test, démarches ouvertes, démarches closes).
Je suis obligé de chercher dans la liste les dossiers en cours que je dois instruire dans les démarches ouvertes.
C'est assez fastidieux car les démarches en haut de la liste sont les anciennes démarches qui ont été testées.
Ce qui serait très bien, ce serait d'avoir en haut de liste les démarches ouvertes en cours d'instruction ou bien pouvoir les monter et descendre afin de les classer.
Merci de prendre en compte si possible ma suggestion.
Bien cordialement

Proposition :

ajouter un filtre dans le statut en instruction

**Comment by lisa-durand** [comment]
J'ai l'impression que c'est un doublon de https://github.com/demarches-simplifiees/demarches-simplifiees.fr/issues/9141. Si c'est bien le cas je te laisse fermer ce ticket ? Et potentiellement relancer @colinux pour l'extraction des données pour voir si c'est un cas qui touche bcp d'utilisateurs ?

**Comment by colinux** [comment]
J'avais transmis l'extraction directement à @Olivier-Marcellin je te la fais suivre aussi

**Comment by lisa-durand** [comment]
Top merci :) C'est confidentiel ? Si non , c'est plus simple d'en garder une trace direct dans le ticket.

**Comment by colinux** [comment]
![Capture d’écran 2023-06-21 à 18 42 33](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/150279/fa669f78-4f10-4f5e-be34-7eebb4d3fe42)

![Capture d’écran 2023-06-21 à 18 42 40](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/150279/4a52b01a-ad09-4f02-8941-4d42732f9804)

**Comment by Olivier-Marcellin** [comment]
oui c'est un doublon @lisa-durand, je ferme ce ticket

**Comment by Olivier-Marcellin** [comment]
ou en est-on avec ce ticket ?
