### ISSUE TITLE
ETQ Administrateur, l'appel de données à API Entreprise doit utilise mon siret comme recipient si possible

### ISSUE THREAD

**Issue by LeSim** [demarches-simplifiees/demarches-simplifiees.fr#9242]
voir la [discussion](https://mattermost.incubateur.net/betagouv/pl/ayytugc1q3rr5bhxzzgg114e3h)

le code se trouve [la](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/blob/main/app/lib/api_entreprise/api.rb#L161)

**Comment by mfo** [comment]
il faudrait une campagne auprès des admins pour renseigné le siret
