### ISSUE TITLE
ETQ admin, lien mort dans la configuration du jeton API Entreprise

### ISSUE THREAD

**Issue by seb-by-ouidou** [demarches-simplifiees/demarches-simplifiees.fr#9307]
dans le fichier [app/views/administrateurs/procedures/jeton.html.haml](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/blob/2a8b97a30d12acb50e76850c60a29420ce6ce824/app/views/administrateurs/procedures/jeton.html.haml#L18)
il y a un lien
      = link_to 'API Entreprise', "https://entreprise.api.gouv.fr/demander_un_acces/"
      
qui est mort
sur la page https://entreprise.api.gouv.fr/ , le nouveau lien semble etre https://api.gouv.fr/les-api/api-entreprise/demande-acces

**Comment by dzc34** [comment]
page concernée : `/admin/procedures/<idProcedure>/jeton `

![Screenshot 2023-07-21 at 01-53-23 demarches-simplifiees fr](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6709977/ae9bdcd6-411f-4281-b35b-f7459dc7412d)

**Comment by dzc34** [comment]
@seb-by-ouidou suggestion pour le titre du ticket : "ETQ admin, lien mort dans la configuration du jeton API Entreprise"
