### ISSUE TITLE
Le terme démarche "close" dans le tableau de bord instructeur prête à confusion

### ISSUE THREAD

**Issue by LeSim** [demarches-simplifiees/demarches-simplifiees.fr#9334]
Les instructeurs ne comprennent pas qu'il y a encore des dossiers à instruire dans les procédure closes.

![Screenshot 2023-07-19 at 15-36-18 Démarches · demarches-simplifiees fr](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/907405/bab6c96c-aae6-4f43-bd16-cb4e8d802687)

- peut être renommer en procédures "fermées aux nouveau dossiers" et mettre avant "En test" ?
- renommer en "fermé et sans dossiers" et ne mettre que les démarches fermés et sans dossiers non terminés, mettre les autres dans "publiée" que l'on renomme en "En cours" ?

**Comment by Bouchralazaar** [comment]
Mettre des pastilles de couleur?

**Comment by LeSim** [comment]
essaye de faire un échange avec nos VIP pour confirmation

**Comment by kara22** [comment]
@Bouchralazaar Salut Bouchra est-ce que tu as du nouveau / des idées pour cela ? Est-ce que c'est à cadrer ou c'est déjà fait ?
