### ISSUE TITLE
ETQ usager, dossiers et procedures supprimées => erreur 404

### ISSUE THREAD

**Issue by seb-by-ouidou** [demarches-simplifiees/demarches-simplifiees.fr#9344]
Si je supprimer une procedure, puis clique sur l'onglet "supprimées" (/admin/procedures?statut=supprimees) j'ai bien la liste des procedures supprimées. mais si ensuite je clique sur une procedure (/admin/procedures/XXX) , alors j'ai une erreur 404.
cela est du a 

```
class Procedure < ApplicationRecord
  [...}
  include Discard::Model
  self.discard_column = :hidden_at
  
```

de meme, depuis la page /dossiers , si je clique sur "supprimés définitivement" (/dossiers?statut=dossiers-supprimes-definitivement) et que l'un des dossiers est associé a une procedure supprimées, alors j'ai une erreur 404
```
ActionView::Template::Error (Couldn't find Procedure with 'id'=201 [WHERE "procedures"."hidden_at" IS NULL]):
```

```

    13:           %th Date de suppression
    14:       %tbody
    15:         - deleted_dossiers.each do |dossier|
    16:           - libelle_demarche = Procedure.find(dossier.procedure_id).libelle
    17:
    18:           %tr{ data: { 'dossier-id': dossier.dossier_id } }
    19:             %td.number-col
    
```

**Comment by seb-by-ouidou** [comment]
---------------------
> `trackingAdullactContrib`

**Comment by dzc34** [comment]
closed by https://github.com/demarches-simplifiees/demarches-simplifiees.fr/commit/44859b8217e650d49ccb08bb4183bbb8e1184a19
