### ISSUE TITLE
ETQ ministère, je souhaite intégrer un nouveau référentiel dans DS : le Répertoire National des Fondations

### ISSUE THREAD

**Issue by emsnytech** [demarches-simplifiees/demarches-simplifiees.fr#9404]
On intègre un nouveau référentiel, le `Répertoire National des Fondations` (RNF)

Le end point de dev se situe ici : `https://rnf.dso.numerique-interieur.com/api/foundations`

on l'interroge avec le numéro de la fondation, par exemple pour le l'identifiant RNF (`rnf_id`) `075-FDD-00003-01` , ça donne https://rnf.dso.numerique-interieur.com/api/foundations/075-FDD-00003-01

il faut rajouter :
- [ ] un service `app/services/RNFService`
  - `def call(rnf_id)` qui s'inspire de `app/services/COJOService` mais sans tout la partie authentification
  il ira chercher les info à partir de l'url plus haut et renverra directement le result de `API::Client.new. `
  - faire la verif du schema avec `JSONSchemer` de la mm facon que `cojo`
- [ ] un type de champ `app/models/types_de_champ/rnf_type_de_champ.rb`
- [ ] dans `model/types_de_champ.rb` rajouter `rnf` dans l'enum `type_champs` et  `rnf: REFERENTIEL_EXTERNE` dans `TYPE_DE_CHAMP_TO_CATEGORIE`
- [ ] le champ `app/models/champs/rnf_champ.rb` . Il devra suivre le principe de `app/models/champs/cojo_champ.rb`
  - `def fetch_external_data? = true`
  - `def poll_external_data? = true`
  - `def fetch_external_data = RNFService.new.(rnf_id:)`
- [ ] un composant `app/components/editable_champ/rnf_component/`
  - avec un input type texte associé au libellé 'identifiant de la fondation' , on stockera la valeur dans `external_id
- [ ] une view `app/views/shared/champs/rnf/_show.html.haml qui affiche les données stockées dans `data`
  - titre: Fondation SFR
  - email: fondation@sfr.fr
  - numéro de téléphone: +33185060000
  - crée le : 07/09/2023, mise à jour le 07/09/2023 (si mise à jour différente)
  - disolu le : .... (si dissolu)
  - identifiant
  - adresse:  16 Rue du Général de Boissieu 75015 Paris
  - status: (si status différent blank)

RAF:
- [ ] décrire l'export graphql
- [ ] décrire l'export csv
- [ ] décrire l'affichage dans l'export pdf

**Comment by LeSim** [comment]
ticket original :

demande d'intégration d'un nouveau référentiel : https://secure.helpscout.net/conversation/2334882208/2037907/

Bonjour 

Comme nous l'avions évoqué il y a quelques mois avec Éric et Patrick, nous développons dans le cadre du projet Bibliothèque Numérique un Répertoire National des Fondations (RNF).

Il nous serait très utile d'avoir dans Démarche Simplifiées un champ RNF, à l'image du champ RNA.
Celui-ci permettra au déclarant de ne saisir que l’identifiant de la fondation.
Comme pour le champ RNA, le déclarant pourra vérifier que l'identifiant saisi correspond bien à la fondation à l'aide du message de validation associé au champ de saisie.
Les informations remontées par l'API RNF seront jointes au dossier.

Cette fonctionnalité est très importante pour la DLPAJ. Elle impacte les démarches qui doivent être crées pour répondre à la loi confortant le respect des principes de la République (CRPR). De plus, comme la validation de ces démarches fait l'objet d'une publication au JO, elle aura aussi un impact sur les traitements automatiques de la DILA.

Tu nous avais laisser entendre que ce n'était pas une difficulté pour tes équipes.
Peux tu nous dire quand cette fonctionnalité pourrait être développée ?

L'API RNF n'est pas encore en production.
Pour l'instant vous pouvez faire des requêtes sur notre environnement de qualification dont l'url est https://rnf.numerique-interieur.com/
Pour la requête il est nécessaire de fournir l'identifiant de la fondation
Vous pouvez tester la requête suivante pour la fondation de test 035-FDD-00001-10 avec la requête suivante :
GET https://rnf.numerique-interieur.com/api/foundation/035-FDD-00001-10
Je te joins le swagger actuel de l'API RNF.
Il n'y a pas de contrôle d'accès pour le moment. Nous vous fournirons un token quand se sera nécessaire.
L'url de l'environnement de production sera rnf.interieur.gouv.fr.

N'hésite pas à revenir vers nous si toi ou ton équipe avez des questions.

Bien cordialement,

Joël
 
Attached: [rnf-documentation.yaml](https://secure.helpscout.net/notification-file/53d8d0af004dda87/6982412601/601195940/rnf-documentation.yaml) (9 KB)
