### ISSUE TITLE
ETQ équipe DS, je dois modifier le mode d'interrogation des API de l'IGN avant fin 2023

### ISSUE THREAD

**Issue by emsnytech** [demarches-simplifiees/demarches-simplifiees.fr#9409]
L'IGN migre ses services d'API geoplateforme

Informations ci jointe :

[Bascule vers la Géoplateforme : quels changements si j'utilise les API JavaScript Géoportail (SDK, extensions pour Leaflet, OpenLayers, ou iTowns) ? | Géoservices (ign.fr)](https://geoservices.ign.fr/2023-03-api-javascript-geoportail).

![image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/27733126/2d248f45-a425-48ce-81f2-8e16756a9354)

Contact : Boris Wattrelos
Chef de projet - Département études et Pilotage | Service des Projets et Prestations 
direction des programmes et de l’appui aux politiques publiques
73 avenue de Paris – 94165 Saint-Mandé
Tél. +33 (0)1 43 98 70 47 / 06 11 41 03 02
ign.fr

**Comment by tchak** [comment]
done
