### ISSUE TITLE
ETQ Administrateur, je veux pouvoir contraindre des saisies dans les champs avec des règles simples (regexp)

### ISSUE THREAD

**Issue by emsnytech** [demarches-simplifiees/demarches-simplifiees.fr#9411]
Suite aux échanges avec le ministère de l'économie 👍 Il s'agit du « Champ du formulaire contrôlé par regexp (type pattern HTML5) » :
 
1.       La fonctionnalité est essentielle pour nous, ( bloquante en l'état ) . Elle permettra d’avoir le contrôle fin, en amont, sur la qualité des données des démarches qui donnent lieu à publication automatique au grand public.
Ex. DérogConso
https://www.economie.gouv.fr/dgccrf/rechercher-produit-recette-temporairement-modifiee?q=*
Ex. Prix des contrôles techniques ; Prix des carburants ; Prix bancaires ; etc.
https://www.prix-carburants.gouv.fr/ 
Stratégie que nous mettons en place (suite au succès de DérogConso sur DS.fr) : remplacer toutes nos téléprocédures « sur mesure » par DS.fr, avec récupération des données par API.
 
2.       L’impact en terme de volume :
Prix des contrôles techniques = 5 000 dossiers établissement et au moins 10 000 dossiers prix/an.
 
3.       Ex. de champs à contrôler. Possibilités infinies :
EAN13 : 0000000000000
EAN8 : 00000000
EAN13 ou 8 séparés par des espaces : 0000000000000 0000000000000 00000000
Code emballeur : EMB 00000L
Estampille vétérinaire : FR 00.000.00 UE
N° d’agrément de centre de contrôle technique : L000L000
Trois prix séparés par un pipe et des espaces éventuels : 85,00 | 72,50 | 91,00
NOR : ECOE2306062D
Réf. qualité : DM-5B-ENQ-016
etc.

**Comment by emsnytech** [comment]
d'autres liens sur ce sujets : https://demarches-simplifiees.featureupvote.com/suggestions/133930/administrateur-restreindre-le-texte-dun-champ-avec-une-expression-reguiere-regex
https://demarches-simplifiees.featureupvote.com/suggestions/80841/administrateur-imposer-une-limite-de-caractere-a-un-champ
https://demarches-simplifiees.featureupvote.com/suggestions/88274/administrateur-restreindre-les-valeurs-autorisees-dans-un-champ-nombre

**Comment by LeSim** [comment]
Pour limiter la casse, prévoir dans l'UI que l'admin donne un exemple de format attendu, et vérifier que cet exemple passe sa regexp

**Comment by chache7000** [comment]
C'est prévu en effet de donner un exemple :-)

**Comment by kara22** [comment]
Quelqu'un est dessus ? Est-ce que c'est cadré ?

**Comment by kara22** [comment]
@LeSim est-ce que c'est cadré ? Je peux prendre la feature ?

**Comment by mfo** [comment]
cadrage rapido ac kara

```
Besoin

    L’admin entre sa regex et s’assure qu’elle est bonne

    Il doit donner un exemple de rendu de résultat (un exemple qui fait que la regexp soit valide)

    Vérifier que cet exemple passe la regex

    Afficher cela en exemple

    Il doit mettre le message d’erreur lui-même en cas de fail


Solution

    un nouveau type de champ regexp

    un nouveau champ regexp (qui va de pair avec le tdc)

    utiliser l'attribut pattern="//" html5

    appliquer la validation quand on sauvegarde le champs (on peut s'inspirer des validation type iban)
```

Exemple de visuel : 


Saisie valide du champs coté admin
![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/125964/9afdfdd5-8a41-4e9c-a576-ae68fa7ba1cf)

Saisie invalide du champs coté admin
![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/125964/f42edf64-5a4a-472c-862c-08b84cb6fa02)
`+` a decliner si la regexp plante ex: `Regexp.new("?!")`

Visuel du champs coté usager

![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/125964/b0a9b083-144a-45a0-a3b9-01f48a35216b)

**Comment by mfo** [comment]
pardon c'etait floue sur la spec. 

>     appliquer la validation quand on sauvegarde le champs (on peut s'inspirer des validation type iban)

donc l'intention etait de l'avoir client/serveur, et a en reparler en effet, ca servirait a rien de doubler client/serveur.

**Comment by tchak** [comment]
Ça m'embête que ce soit un nouveau type de champ

**Comment by chache7000** [comment]
Bonjour, est-ce que nous pouvons échanger sur le besoin si cela peut vous aider ? Je suis joignable au 06 31 74 11 72. N'hésitez pas, nous sommes très motivés pour avoir cette fonctionnalité pour un projet qui est imminent.

**Comment by chache7000** [comment]
Bonjour ! je vois que vous avez fermé le cas, est-ce que la fonctionnalité est finie :-D ? J'adorerais la tester :-)

**Comment by kara22** [comment]
Bonjour @chache7000 nous avons mergé la fonctionnalité aujourd'hui, elle sera en ligne à la prochaine mise en production. Je vous contacterai pour que vous puissiez la tester, elle est ouverte uniquement à la demande pour l'instant.

**Comment by kara22** [comment]
@chache7000 voici la documentation réalisée
