### ISSUE TITLE
Affichage d'une carte dans un formulaire lorsque le champ `Carte` est imbriqué dans une logique conditionnelle

### ISSUE THREAD

**Issue by cmayran** [demarches-simplifiees/demarches-simplifiees.fr#9417]
**Affichage de la carte à l'utilisation d'une logique conditionnelle dans un formulaire**

ETQ Administrateur, lorsque j'utilise un champ `Carte` dans un formulaire et que j'y associe une logique conditionnelle pour faire apparaitre ladite carte, la taille de la carte est résolument inférieure à l'affichage de cette même carte sans logique conditionnelle (voir capture d'écran ci-dessous)

**Reproduction**
Comment reproduire le problème :
1. Aller sur une démarche. 
2. créer un champ `Choix simple`
3. créer un champ `Carte` --> cadastre
4. ajouter une logique conditionnelle sur le champ carte avec une donnée du champ `Choix simple`
5. prévisualiser le formulaire

La carte est réduite.

**Comportement attendu**
![image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/121302145/2516994f-870d-4b79-9a04-ef8ee90f6658)

**Capture d'écran du comportement actuel**
![image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/121302145/b4d7b5bf-591f-4cc5-84de-4e918925bc22)

**Appareil et navigateur utilisé**
 - Appareil : [ PC]
 - Navigateur : [Firefox, Chrome, Edge]

**Comment by dzc34** [comment]
---------------------
> `trackingAdullactContrib`  `trackingAdullactBugReport`
