### ISSUE TITLE
ETQ super manager, je veux pouvoir transférer un dossier d'un usager à l'autre 

### ISSUE THREAD

**Issue by Bouchralazaar** [demarches-simplifiees/demarches-simplifiees.fr#9435]
Comme pour les fusions de compte, je veux pouvoir transférer uniquement un dossier (plutôt que le compte entier) d'un usager à l'autre, depuis le manager. 

Peut être faudrait il envisager un envoi d'email à l'usager initial lors du transfert de dossier?

**Comment by tchak** [comment]
L'utilisateur à l'origine du dossier peut déjà le faire. Si de toute façon on dit que l'utilisateur d'origine doit valider le transfert, je suppose que ce qui est demandé, c'est de pouvoir initier le transfert depuis le manager avec passage par une étape de validation par l'utilisateur original.

**Comment by Bouchralazaar** [comment]
@tchak on veut pas forcément validation par l'utilisateur car deux cas de figure: 
L'usager n'a plus accès à sa boîte mail (boite email supprimée, mot de passe oublié etc)
L'usager a quitté l'organisation (dossiers déposés par des pro)

On veut pouvoir transférer un dossier d'un compte à l'autre. (aujourd'hui on peut fusionner le compte entier mais pas juste un seul dossier). 

A ta dispo pour plus d'infos

**Comment by mfo** [comment]
je vais proposer qqch sans validation par mail, cf:

> L'usager n'a plus accès à sa boîte mail (boite email supprimée, mot de passe oublié etc)
> L'usager a quitté l'organisation (dossiers déposés par des pro)

Donc difficile de valider un tranfert si l'usager n'est plus la (j'ai qd même un petit questionnement autour de qui prend la responsabilité).

**Comment by mfo** [comment]
@emsnytech – faut p-e se couvrir question juridique la dessus ? Ex: stocker la demande de l'usager, ou confirmer par mail avec l'usager qui fait la demande de transfert ?

**Comment by colinux** [comment]
Selon moi il faut protéger l'usager titulaire du dossier de demandes abusives en essayant de le prévenir pour qu'il puisse s'y opposer. Cas classique: un ex-conjoint/parent essaie de récupérer abusivement un dossier déposé sur un autre compte et peut faire croire n'importe quoi pour y parvenir. La procédure que j'ai déjà vu passer chez plusieurs services c'est qu'un email très clair annonce au titulaire qu'untel réclame le dossier, et on indique que si cette demande n'est pas légitime, il peut s'y opposer en cliquant sur un lien dans un délai de 15 jours par exemple.
En gros ça pourrait donner un message comme ceci :  

> Notre service a été sollicité pour transférer votre dossier blalbla vers le compte col****ie@gm**.com [pour cette raison là]. Si vous ne faites rien dans les 15j, le dossier sera automatiquement transféré sur son compte et vous n'y aurez plus accès. Si vous pensez qu'il s'agit d'une erreur ou avez le moindre doute, cliquez sur le lien suivant ou contactez-nous.

Autrement dit, dans le cas habituel où la personne n'est plus là / n'a plus accès à l'email, ya rien de plus à faire qu'attendre les 15j de temporisation.

**Comment by LeSim** [comment]
Coucou, je vous propose de réaliser telle quelle la story sachant qu'aujourd'hui le un super admin peut déjà carrément changer tout le compte. On n'accorde pas ici plus de droit qu'avant.

On refera un point sur ces droits en général.
