### ISSUE TITLE
ETQ Instructeur je veux pouvoir filtrer les dossiers qui sont en attente de demande de correction

### ISSUE THREAD

**Issue by tchak** [demarches-simplifiees/demarches-simplifiees.fr#9483]
Les instructeurs devraient pouvoir filtrer les dossiers qui sont en attente de demande de correction. Idéalement, cela serait un nouveau filtre et un nouvel onglet. C'est bloquant pour le fonds vert.

**Comment by lisa-durand** [comment]
@tchak est-ce possible d'avoir plus de précision sur ce ticket.
Il me semble qu'on a déjà un filtre sur le statut "en attente"
![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/27b89e2c-0b77-4390-8cbf-3b6ef73a3cc1)
Et qu'ajouter un nouvel onglet semble pas la bonne piste car on essaye déjà de les réduire il me semble.

Il faudrait peut-être avoir un peu plus de contexte sur le cas d'usage pour essayer de reflechir à une eventuelle solution ?

**Comment by AndyBarakat** [comment]
En tant qu'instructeur, il est difficile de différencier les dossiers 'En construction' des dossiers 'En construction & En attente'. 
Les dossiers En attente ne devant pas etre disponible à l'instruction (cf ticket https://github.com/demarches-simplifiees/demarches-simplifiees.fr/issues/9485), il est important pour les instructeurs de ne pas avoir tous les dossiers ici. 

Le filtre actuellement en place ne permet pas de filtrer les dossiers qui ne sont pas 'En attente'. @lisa-durand

**Comment by colinux** [comment]
J'ai mergé une évolution du filtre "_en construction_" qui exclut d'office les dossiers en attente, mais j'ai une réserve :

Je comprends l'intérêt de vouloir dans certains cas ne pas voir les dossiers en attente, mais maintenant on ne peut plus avoir tous les dossiers en construction (et uniquement ceux-là). Ça me paraissait utile, mais je trompe peut-être et j'ai pas de solution toute simple à proposer, à part rajouter un nouveau filtre "_en construction & en attente_".
Ou plutôt celui ci serait renommé en "_en construction, pas en attente_" 😨

On verra quels besoins se font ressentir.

**Comment by tchak** [comment]
On peut avoir plusieurs filtres à la fois aujourd'hui. Donc, un filtre en attente/pas en attente pourrait être combiné avec un filtre d'état. Ce qui nous manque, c'est la possibilité d'appliquer la négation à certains filtres.

**Comment by tchak** [comment]
@AndyBarakat Est-ce que tu considères que le problème est résolu pour vous, ou devons-nous rouvrir le ticket ?

**Comment by colinux** [comment]
@tchak je crois qu'en l'état, la négation de certains filtres est vraiment compliquée à implémenter, sans parler de l'interface.
A court terme si le besoin s'en fait ressentir, étant donné que ces filtres sont dans un select "statut" (ou "état" je ne sais plus), on pourrait avoir ces variantes : 

- en construction
- en attente
- en construction et en attente <-- correspond à l'ancien "en construction")
- les autres

C'est surtout une histoire de libellé

**Comment by tchak** [comment]
@colinux en fait, ce que tu es en train de mettre en évidence, c'est que "en attente" est un vrai état et nous aurions dû faire évoluer la machine à états pour en tenir compte :)

**Comment by AndyBarakat** [comment]
En ce qui me concerne, l'évolution proposée permet de répondre à notre besoin. Mais je pense que la création d un statut différent permettrait plus de clarté en effet. 
Lorsqu on filtre sur les dossiers 'En attente', L UI a tendance à montrer que ces dossiers sont en fait aussi en statut 'En construction'. Alors même que si on filtre les dossiers 'En construction', on ne les retrouve pas. Cela pourrait être perturbant pour certains instructeurs.

**Comment by colinux** [comment]
@tchak, à l'époque on s'était dit que c'était trop proche de `en_construction` pour en faire un état à part, mais on avait réfléchi peut-être un peu trop vite.
