### ISSUE TITLE
ETQ usager, je voudrais avoir un bouton d'action à côté des messages de demande de correction

### ISSUE THREAD

**Issue by tchak** [demarches-simplifiees/demarches-simplifiees.fr#9484]
Le message de demande de correction devrait contenir un bouton qui mène directement à l'écran de modification du dossier.

Aujourd'hui, ces messages incitent à l'action, mais l'action n'est pas facilement réalisable :

<img width="1028" alt="image" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/12428/aa7aad30-cd89-4a0c-8003-2e7a74531e2b">

![CleanShot 2023-09-18 at 10 26 20@2x](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/12428/7189bd8b-2d28-441a-a1eb-91daaad1c73c)

**Comment by lisa-durand** [comment]
@tchak est-ce possible d'avoir plus de précision sur ce ticket, car juste en -dessous du message d'alerte, il y a le bouton d'action "modifier le dossier" facilement accessible. Mais il me semble que le souci de l'usager est qu'il ne sait pas quoi modifier sans passer par la messagerie ? Du coup, est-ce qu'on doit rajouter un bouton d'action qui mène à la messagerie ?

**Comment by mfo** [comment]
fait
