### ISSUE TITLE
ETQ instructeur, je voudrais pouvoir demander une mise à jour de dossier

### ISSUE THREAD

**Issue by tchak** [demarches-simplifiees/demarches-simplifiees.fr#9485]
Le cas de demande de mise à jour du dossier suite à une évolution du formulaire avec des conflits est un bon cas d'usage de la fonction de demande de corrections. Cependant, les types de demande de correction actuellement disponibles ne correspondent pas complètement à l'usage et posent quelques défis en termes d'expérience utilisateur.

Je propose d'introduire un troisième type de demande de correction "update", en plus des types "incorrect" et "incomplete". Du côté de l'instructeur, ce nouveau type de correction devrait bloquer le passage en instruction tant que les corrections ne sont pas apportées au dossier. Du côté de l'usager, le message devrait être adapté pour refléter qu'il ne s'agit pas d'une simple correction, mais d'une mise à jour.

* Je pense que ce type de correction ne devrait pas apparaître pour les démarches en vrai SVR/SVA.
* Il faut peut-être envisager un moyen de contourner le blocage du passage des dossiers en instruction (ou un moyen de révoquer la demande de correction) afin de ne pas se retrouver avec des dossiers complètement bloqués.

**Comment by AndyBarakat** [comment]
Quel serait le message reçu par le porteur de projet dans ce cas? Y aurait-il possibilité de le paramétrer?

**Comment by lisa-durand** [comment]
@tchak je pense qu'il faudrait un peu plus de contexte sur ce ticket car déjà le fait d'avoir 2 demandes de corrections différentes semblaient pas hyper évident à comprendre ni à mettre en place sur l'interface pour l'instructeur. Est-ce qu'on "met un dropdown", "comment bien différencier les 2 actions". Du coup là comme ça, l'idée d'en rajouter une 3e - alors qu'il s'agit au final tjs de la même chose "on demande à l'utilisateur de "modifier/corriger son dossier" ne me parait pas évident. Peut-être qu'il faut juste pouvoir mieux adapter le texte ?

**Comment by tchak** [comment]
@lisa-durand Effectivement, comme le souligne @AndyBarakat, le plus important est de trouver un moyen de bloquer le passage en instruction des dossiers en attente de corrections dans certains cas. Une autre option serait de pouvoir le configurer par démarche.

**Comment by AndyBarakat** [comment]
@lisa-durand @tchak Avez vous des avancées concernant le blocage du passage en instruction des dossiers en attente de correction? 
Merci d'avance!

**Comment by colinux** [comment]
Le plan qu'on a validé : 

- un nouveau type de "correction" (une nouvelle `reason`, par exemple `update`)
- dans un premier temps, uniquement disponible par API, car les FV ne les créeront pas par l'interface
- un wording usager un peu plus adapté notamment pour l'email, le badge rouge _à corriger_ , et peut-être quelques autres endroits de l'interface usager.

NB: le besoin pourra resservir à d'autres démarches, quand nous aurons trouver l'UX instructeur/admin qui va bien pour ces types de corrections.
