### ISSUE TITLE
contacter par mail les administrateurs qui ont un service sans siret, et leur demander de le remplir

### ISSUE THREAD

**Issue by LeSim** [demarches-simplifiees/demarches-simplifiees.fr#9502]
Faire une tache rake, en s'inspirant de `lib/tasks/hotfix.rake` qui

- supprimerait tous les services non utilisé
`Service.joins('LEFT OUTER JOIN "procedures" ON "procedures"."service_id" = "services"."id"').where(procedures: { id: nil }
).destroy_all` . 

Ne pas passer par `where.missing(:procedures)` car on supprimerait des services de procedures cachées.

- enverrait un mail à tous les administrateurs de services sans siret
` Administrateur.joins(:services).where(services: { siret: nil }).map(&:email)`

ce mail dirait grosso modo:

```
Bonjour
Vous êtes administrateur sur la plateforme demarches-simplifiees.fr et au moins un de vos services n'a pas son siret renseigné. 

Afin d'éviter tout disfonctionnement sur la plateforme, nous vous invitons à le remplir au plus vite à cette adresse (et mettre la l'adresse des procedures https://www.demarches-simplifiees.fr/admin/procedures, il y a le bandeau qui demande le siret)

Cordialement ...
```

**Comment by krichtof** [comment]
Et pour le mail aux admins, j'ai bien envie de l'envoyer uniquement aux admins de procedures publiées sans service
