### ISSUE TITLE
Export, quid des PJs des expert ?

### ISSUE THREAD

**Issue by mfo** [demarches-simplifiees/demarches-simplifiees.fr#9510]
il faudrait intégrer les PJs des experts aux exports

**Comment by colinux** [comment]
Est-ce qu'on intègre tous les avis experts, ou seuls les non confidentiels ?

**Comment by tchak** [comment]
La confidentialité, c'est entre les experts. Dans un export à destination des instructeurs/administrateurs, tous les exports doivent apparaître je pense.

**Comment by colinux** [comment]
Closed by #9558
