### ISSUE TITLE
Sur l'interface administrateur, le message lors de la modification d'un champ du formulaire peut faire "peur" 

### ISSUE THREAD

**Issue by Bouchralazaar** [demarches-simplifiees/demarches-simplifiees.fr#9514]
Au moment de la publication : 

![Capture d’écran 2023-09-25 à 04 54 39](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/89633115/0973913a-39f9-4d90-9c56-0cd5eec0923e)

**Alternatives proposées :** 
Enlever le signe "attention" et garder les informations du cadre 
Ou bien formuler la phrase tel que suit: "les modifications apportées ne s'appliqueront pas aux dossiers déja déposés"

Il faudrait également rajouter une mention que lorsqu'un champ est supprimé, il est aussi supprimé sur les dossiers déja déposés.

Dispo si besoin d'en parler :)

**Comment by colinux** [comment]
+1 pour la reformulation

On doit aussi inverser l'ordre des boutons: Publier (action principale) à gauche, car les boutons sont alignés à gauche

**Comment by krichtof** [comment]
J'ai fait une PR. A noter que de mon côté, je n'ai pas eu à inverser l'ordre des boutons, ils étaient dans le bon ordre :shrug:

**Comment by colinux** [comment]
Sur l'ordre des boutons j'ai fait une pr qui a été mergee ce matin

Par contre je questionnais l'intérêt de devoir passer par 2 écrans identiques avec un bouton Publier. Je pense que c'est limite un bug (depuis qu'on a la nouvelle page de publication ?)
