### ISSUE TITLE
En tant qu'instructeur, lorsque j'utilise la fonctionnalité de filtre de dossiers sur un champ choix (multiples?), les valeurs possiblent ne s'affichent pas

### ISSUE THREAD

**Issue by Bouchralazaar** [demarches-simplifiees/demarches-simplifiees.fr#9515]
Les valeurs des champs ne s'affichent pas, les instructeurs doivent ressaisir la valeur exacte (en prennant en compte les espaces, etc..) 
![Capture d’écran 2023-09-25 à 05 25 27](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/89633115/05b2b381-52bb-485c-9247-48e8f7b5532e)

**Comment by colinux** [comment]
On doit afficher un `<select>` avec les options proposées, plutôt qu'un champ libre.
