### ISSUE TITLE
Bug de migrations empêchant de lancer une instance de l'application

### ISSUE THREAD

**Issue by Yann-TF** [demarches-simplifiees/demarches-simplifiees.fr#9521]
**Décrivez le bug**
Il ne semble pas possible de partir d'une base vierge et faire tourner le projet : 
Les migrations du db:migrate échouent comme par exemple la première (20190709140415_add_export_queued_to_procedures) qui ajoute des colones à une table qui n'existe pas encore.

**Reproduction**
Cloner le projet et partir d'une base de données vierge.
Lancer la commande bin/setup ou bin/rake db:migrate

**Comportement attendu**
Les migrations devraient passer et on devrait pouvoir lancer une version vierge de l'application

**Comment by dzc34** [comment]
En utilisant `bin/rails db:setup ` ? (si la base de données n'existe pas)
En utilisant `bin/rails db:drop db:setup` ? (si la base de données existe déjà, avec des tables et plus)
En utilisant `bin/rails db:schema:load db:seed` ?  (si la base de données est créé vide par un autre outil)

voir à ce sujet : https://guides.rubyonrails.org/active_record_migrations.html#setup-the-database

-

**Comment by Yann-TF** [comment]
Merci beaucoup pour votre réponse, ça a l'air de fonctionner.

Il vaut peut-être le coup de mettre à jour le README en ce sens ou ajouter `bin/rails db:setup ` au fichier bin/setup
