### ISSUE TITLE
Afficher l'astérisque ou la mention "facultatif" pour un champ " case à cocher seule" 

### ISSUE THREAD

**Issue by CamilyaDellali** [demarches-simplifiees/demarches-simplifiees.fr#9526]
L'astérisque à droite du champ" case à cocher seule" n'est pas affichée lorsque le champ est paramétré comme obligatoire et même chose lorsque c'est facultatif : 
![image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/82160230/fcd3a361-f6e3-4471-a8ee-b2bc7dcf6b64)

![image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/82160230/d44a1603-7022-408c-8cc1-d521745d3108)

**Comment by tchak** [comment]
C'est normal car la signification de facultatif ou obligatoire n'est pas la même pour les cases à cocher que pour les autres champs. Si l'on souhaite s'assurer que le choix a bien été fait, que ce soit oui ou non, il faut utiliser le champ Oui/Non qui dispose d'un état vide et donc sur lequel il y a une notion de non rempli, contrairement à la case à cocher où il n'y a pas de différence entre "vide" et "non".

**Comment by tchak** [comment]
De plus, il me semble qu'on penche vers l'idée de supprimer les mentions "facultatif"

**Comment by colinux** [comment]
Je ferme car on enlève partout a mention facultatif dans #9553
