### ISSUE TITLE
ETQ instructeur je vois que "En attente" est un statut de dossier à part entière

### ISSUE THREAD

**Issue by E-L-T** [demarches-simplifiees/demarches-simplifiees.fr#9562]
Suite à l'ajout du badge "En attente" qui apparait après une demande d'information à l'usager, il y a eu plusieurs retours d'admin/instructeurs : 
- besoin de distinguer "en construction" et "en attente"  au niveau des filtres (voir https://github.com/demarches-simplifiees/demarches-simplifiees.fr/issues/9483 )
-  besoin de distinguer "en construction" et "en attente"  dans les exports. voir https://secure.helpscout.net/conversation/2375394318/2041537

C'est peut-être le moment de faire de "En attente" un état au sens de la machine à état (comme discuté en commentaires ici : https://github.com/demarches-simplifiees/demarches-simplifiees.fr/issues/9483)

**Comment by colinux** [comment]
Je suis susceptique sur la transformation en statut : ça le rendrait beaucoup trop proche  _en construction_, et ça dépend de la façon dont il est utilisé par les instructeurs. C'est plus un flag de _en construction_, c'est à dire un sous ensemble de ces dossiers.
Aussi certains veulent l'utiliser de manière bloquante (à la rigueur ça pourrait justifier d'en faire statut), d'autres non

L'incompréhension vient peut-être de pb d'affichages qu'on pourrait améliorer  : 

- dans le tableau on le voit dans la même colonne que statut (essentiellement car gain de place pour éviter de rajouter une colonne, mais aussi car ça précise le sous ensemble)
- il est stylé comme un statut, avec un badge.
- on le retrouve dans le même filtre.

Le truc le plus simple pourrait être d'en faire un filtre dédié pour permettre de voir les dossiers : 
- en construction  (en attente ou non)
- en attente (qui sont de facto en construction)
- pas en attente (mais en construction quand même ?)

Ça pourrait aussi être un sous-filtre quand on a choisi en attente. L'avantage c'est que ça ancre l'idée de sous-ensemble de ce statut.
