### ISSUE TITLE
ETQ admin, je souhaite associer une démarche existante depuis le bouton "clore" du tableau de bord de la démarche

### ISSUE THREAD

**Issue by CamilyaDellali** [demarches-simplifiees/demarches-simplifiees.fr#9593]
la fonctionnalité "cette démarche remplace une démarche existante" n'est pas disponible depuis le bouton "clore" du tableau de bord administrateur de la démarche : 
![image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/82160230/b0602e0e-153c-4580-a608-fe83ad52ac02)

On retrouve cela uniquement si l'administrateur clore la démarche depuis le bouton situé dans la liste déroule "action" 
![image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/82160230/eecfb31e-b124-4502-a70f-109e41e548ca)

De plus, il doit y avoir un bug d'affichage car le champ pour sélectionner la démarche ne s'affiche pas directement : 
![image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/82160230/19fcd115-8cb9-4213-9d8b-ffb7f5e9dad5)

**Comment by colinux** [comment]
On doit pouvoir enlever l'un des 2 boutons , et unifier l'interface?
Pour le bug d'affichage, probablement un ancien form restant qui n'a pas été converti au dsfr
