### ISSUE TITLE
Attestation v2 à la charte de l'état

### ISSUE THREAD

**Issue by LeSim** [demarches-simplifiees/demarches-simplifiees.fr#9596]
La méta issue est la #9200 et un début de pr est la #9594  et l'implém éditeur #9903

la charte est [la](https://www.gouvernement.fr/charte/charte-graphique-les-applications/ministeres-secretariats-d-etat-services-deconcentres-ou-a-l), on fait un mix entre le communiqué de presse et le masque traitement de texte.

on doit respecter :
- la police ~~Arial Bold et Regular~~ Marianne (il y a incohérence dans la spec ds fr, entre la partie typo et les images, et les blocs marque sont en Marianne)
- les marges en mm autour de la page et essayer entre les différents éléments en hauteurs

Notre layout doit contenir
- une zone bloc marque avec un ou plusieurs logo
- une zone direction
- la date
- un titre
- un sous titre
- le corps de l'attestation pouvant contenir
  - des titres
  - des sous titres
  - des paragraphes
    - le contenu du paragraphe doit pouvoir contenir des balises  gras / italique / souligné
- une zone signature avec une ou plusieurs signatures
- une zone information réglementaire
- une zone contact
- un numéro de page en bas de page de type '1/3'

Liens utiles pour faire tout ça :
- https://printcss.net/
- https://print-css.rocks/
- https://www.smashingmagazine.com/2015/01/designing-for-print-with-css/
- https://www.smashingmagazine.com/2018/05/print-stylesheets-in-2018/

exemples de doc à la chartre :
- https://www.systeme-de-design.gouv.fr/uploads/2_Note_SIG_d_application_du_DSFR_et_gouv_fr_13_07_2023_e4824418a3.pdf
- https://www.systeme-de-design.gouv.fr/uploads/3_Note_DINUM_qualite_des_services_numeriques_17_07_2023_9bd158313d.pdf -> utilise du Marianne

**Comment by lisa-durand** [comment]
--
**Version cropée taille ordi (logo charte de l'état)**
![Identité-2](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/9acb91fe-6a2e-4387-9431-3854674682a3)

--
**Version cropée taille ordi (logo non charte de l'état)**
![Identité-3](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/42d00544-5b9d-402a-9dce-506f9f119c1b)

--
**version full length**
![Identité](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/61397d43-faf7-4a43-8926-dd25b06fbe61)

--
**version full length (avec placeholder et intitulé de direction intégrée à l'éditeur)**

![Identité-1](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/0060c22a-7bdf-4d4f-8daf-06ad0ad5ba10)

**Comment by colinux** [comment]
Closed by #10465
