### ISSUE TITLE
Ajouter les champs RNF aux exports + API

### ISSUE THREAD

**Issue by lisa-durand** [demarches-simplifiees/demarches-simplifiees.fr#9670]
Suite à l'ajout du nouveau référentiel RNF : #9648 
Commentaire de @tchak "Il faudrait ajouter aux données affichées la décomposition de l'adresse : INSEE et département. Ce serait bien aussi d'ajouter quelques colonnes aux exports (xls) : INSEE et département. Même chose sur l'API"

**Comment by krichtof** [comment]
@tchak @lisa-durand Voici donc la liste des données que je compte exporter et exposer côté API :

- -rnfId
- title
- cityCode (code insee)
- department
