### ISSUE TITLE
Notifier les experts ayant accès à la messagerie des nouveaux messages

### ISSUE THREAD

**Issue by colinux** [demarches-simplifiees/demarches-simplifiees.fr#9725]
Remontées sur HS car ils sont pas prévenus et doivent revenir régulièrement sur DS

**Comment by kara22** [comment]
@colinux Salut Colin. En codant, je me rend compte qu'on a pas de gestion des notifications pour les experts, les instructeurs eux ont la possibilité de ne pas être notifiés pour une démarche particulière.

J'imagine qu'il y a des experts qui ne veulent pas être spammés par autant de mails ?

**Comment by colinux** [comment]
@kara22 hello, honnêtement je ne sais pas. J'imagine que oui, idéalement ça devrait être paramétrable, mais on a rien de tel encore pour les experts (la page existante des instructeurs pourrait être généralisée au niveau du compte utilisateur pour régler toutes les préférences d'email).
Cependant on peut peut-être faire plus simple dans un premier temps, activer ça pour tout le monde, et en fonction des retours le rentre paramétrable ?

**Comment by kara22** [comment]
@colinux oui j'ai fait une PR https://github.com/demarches-simplifiees/demarches-simplifiees.fr/pull/9890
