### ISSUE TITLE
ETQ Admin, lorsque je clos une démarche pour la sortir de DS, je peux ajouter un lien et alerter les usagers

### ISSUE THREAD

**Issue by E-L-T** [demarches-simplifiees/demarches-simplifiees.fr#9777]
Lors de la clôture d'une démarche l'admin choisit l'une des 3 raisons possibles de clôture : 
- démarche remplacée par une démarche dans DS
- démarche remplacée par une démarche hors DS
- autre

Si le choix est hors DS, alors l'admin peut désormais ajouter un lien.
Dans les 3 cas, l'admin a la possibilité de prévenir les usagers (en brouillon et/ou en cours).

Sur l'ecran admin : on rajoute une alerte lorsque la démarche est close (avec ou sans lien) pour que ce soit plus visible par l'administrateur.

Pour l'usager : lorsqu'il tente d'aller sur une démarche close, il arrive dessus avec un message d'alerte lui indiquant l'adresse de la nouvelle démarche si besoin. (on supprime la redirection vers la page d'accueil)

NB : 
attention a l'envoi de l'email, le cas d'une démarche avec 6k de dossier en construction ferait péter le rate limit dolist. il y a un rate limiter qui fait ca ds l'app : https://github.com/demarches-simplifiees/demarches-simplifiees.fr/blob/main/app/services/expired/mail_rate_limiter.rb

![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/b4917f36-67f2-4a18-9b04-9d8e9de508c0)
![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/30b651f4-3713-45a7-bfad-fd93e84a45e9)
![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/843b31c7-de2b-47e7-a91e-e3c2b3022666)
![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/13d46841-c521-46cf-9198-62a6855c2b83)
![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/40f03ffe-54d6-421a-a6ec-ed4ea31d539b)

**Comment by lisa-durand** [comment]
Lié aux tickets : #9779 - #9780 - #9781 
Voir si on ne peut pas les rassembler - s'ils sont tous utiles en fonction du flow utilisateur ?

**Comment by lisa-durand** [comment]
Après discussion avec @E-L-T et @LeSim on change un peu le fonctionnement. 
On a désormais que 2 raisons pour la cloture : "Remplacement par une demarche dans DS" ou "autre". Dans le cas de "autre", l'admin doit renseigner un texte d'information qui va se retrouver sur une nouvelle page de clôture de la démarche. Puis l'admin peut s'il le souhaite envoyer des mails aux usagers. 
Voici les nouveaux écrans : 
![page-1](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/5f3d1efa-880a-4235-8054-d05557b5c381)
![page-2](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/f02710ac-dade-497a-a4c8-25b3ef0b4078)
![page-3](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/e94fc6b8-c8f3-43e5-87a0-c155e2bd70c8)
