### ISSUE TITLE
ETQ instructeur, je veux pouvoir apposer un label à un dossier

### ISSUE THREAD

**Issue by LeSim** [demarches-simplifiees/demarches-simplifiees.fr#9787]

**Comment by colinux** [comment]
# Propositions 

## Cas d'usage remontés

- je veux faire comme un "post-it" (organisation personnelle)
- je veux faire valider le dossier à ma hiérarchie 
- je veux faire valider le dossier par un second instructeur
- je veux avoir des états intermédiaires entre _en instruction_ et _accepté/refusé_
- je veux marquer un dossier comme "prêt pour la commission" ou équivalent

Les labels seraient une façon d'y répondre.

Les caractéristiques d'un label sont : 

- un nom au choix
- une couleur au choix 
- visibilité : personnel ou partagé par tous les instructeurs de la démarche (auquel cas n'importe quel instructeur peut aussi le supprimer, il n'y a pas de notion d'appartenance)
- invisible par l'usager
- limité à une démarche
- assigné à un ou plusieurs dossiers de cette démarche

Pour associer un label à un dossier (ou à plusieurs dossiers en masse), un instructeur choisit son label depuis une liste de labels qu'il a déjà ajouté (ou qui sont partagés avec lui via la démarche), et peut en créer un autre. Un peu comme sur github pour les issues/PR.
Un dossier peut avoir plusieurs labels.
On trace qui assigne chaque label et quand (information visible sur "Personnes impliquées" par exemple).

## Cas d'usage type "post-it" / organisation perso :  

- les labels sont affichés à côté du dossier
- on peut filtrer pour ne voir que les dossiers ayant un label donné (ou une combinaison de labels)
- éventuellement, à la demande de l'instructeur, on peut figer des onglets correspondant à un label pour les lister facilement, y appliquer des actions de masse…

## Cas d'usage statut partagés entre autres instructeurs / hiérarchie / commission / états intermédiaires …

- un instructeur assigne un label partagé (visible par tous) par exemple _vérifiable par N+1_ ou _éligible commission_
- le N+1 se connecte à son espace instructeur. Dans la liste des dossiers de la démarche, il retrouve les dossiers concernés par un filtre sur ce label et/ou un onglet dédié à ce label.
- le N+1 fait sa vérification. Comme n'importe quel autre instructeur : il peut accepter/refuser le dossier, assigner un autre label , par exemple _accepté pour commission_, _vérifié par N+1_, _vérifiable par N+2_, etc… Il peut supprimer le label _vérifiable par N+1_ s'il le souhaite.

Remarques :

- dans cette implémentation, les instructeurs de la démarche ne sont pas discriminés : du point de vue de DS il n'y a pas de hiérarchie, et tous peuvent voir ce dossier. S'il ya des groupes instructeurs, tous les instructeurs susceptibles de voir les dossiers doivent être dans tous les groupes concernés. De la même manière n'importe quel instructeur pourrait agir sur ces labels (comme n'importe autre action sur DS.) On mise sur la responsabilité de chacun.
- dans les nouveaux exports qui permettront de choisir les colonnes exportées, les instructeurs pourraient choisir ou non d'exporter les labels 
- on pourrait imaginer qu'un instructeur s'abonne à une notification par email lorsqu'un nouveau label de son choix est ajouté ou supprimé à un dossier

**Comment by marleneklok** [comment]
# Description
Les **LABELS** sont à distinguer des **NOTIFICATIONS**.
## LABELS
= tags entièrement **personnalisables** par l’instructeur, qui choisit de les afficher ou non.
_Format « tag - non cliquable »_
![image](https://github.com/user-attachments/assets/a96fe6ad-f52f-4b10-89e0-721a1a5b79f7)

## NOTIFICATIONS
= badges affichés / désaffichés **automatiquement par DS (et sur lesquels l’instructeur n’a pas la main)**, en fonction de l’état d’un dossier (ex. : délai du SVA/SVR, dossier qui expire bientôt, dossier qui sera bientôt supprimé…) ou d’un événement détecté sur le dossier (ex. : dossier en attente de correction, dossier modifié, nouveau message usager, nouvelle annotation privée, avis externe rendu…).
_Format « badge »_
![image](https://github.com/user-attachments/assets/9e84d422-9058-4a75-8716-a5441c790c0d)

## Ajout de labels sur un dossier
L’instructeur peut ajouter un ou plusieurs labels depuis la page de consultation d’un dossier :
![image](https://github.com/user-attachments/assets/4cafa8cf-004a-4f75-aaa4-35e2a38366ff)
![image](https://github.com/user-attachments/assets/39e6ff34-fe74-48bc-a7fe-745638ecd3ff)

## Personnalisation des labels
En cliquant sur **« Personnaliser les labels »**, l’instructeur accède à la liste de labels (au sein d’une modale) créés par lui-même et/ou les autres instructeurs de la démarche / de son groupe instructeurs.
![image](https://github.com/user-attachments/assets/d0616576-aa69-46b6-9a92-0fec0eba268d)
![image](https://github.com/user-attachments/assets/cfefb707-a658-4097-9174-f234d04cecdf)

## Modification d'un label
L’instructeur peut modifier un label existant (créé par lui-même ou un autre instructeur - il n’y a pas de notion d’appartenance) :
![image](https://github.com/user-attachments/assets/919eec38-7315-45f7-b4e2-4ffe821ff95e)
![image](https://github.com/user-attachments/assets/d0e07394-a6ec-480d-ae6e-38f5c5c434dc)
Il peut modifier :
• le **nom** (avec un nombre de caractères limités)
• la **couleur** (à choisir parmi une palette prédéfinie, qui propose des couleurs suffisamment discriminantes entre elles et offrant un bon contraste caractères-fond)
![image](https://github.com/user-attachments/assets/e6aa7300-1bf3-4108-bf3e-127751ab6dd2)
• le niveau de **visibilité** :
   Personnel / visible uniquement par lui
   Partagé avec tous les instructeurs de la démarche / du groupe instructeurs de la démarche
N.B. : à chaque modification, l’aperçu se met automatiquement à jour.
![image](https://github.com/user-attachments/assets/ca1ef859-1e3c-4593-afa4-62e0b4584ba6)
Il enregistre ensuite ses modifications et la liste de labels se met à jour :
![image](https://github.com/user-attachments/assets/0df6671c-6388-4c21-9ef9-aa0f5735a5d2)
![image](https://github.com/user-attachments/assets/486f01b7-0904-4f27-8262-4f99de409f59)
### Palette de couleurs
![image](https://github.com/user-attachments/assets/5cab8c71-cae7-435c-904e-53e45211cdff)

## Suppression d'un label
L’instructeur peut aussi supprimer un label existant (créé par lui-même ou un autre instructeur - il n’y a pas de notion d’appartenance).
Lorsqu’il souhaite supprimer un label avec une visibilité partagée **par tous les instructeurs**, le navigateur affiche une demande de confirmation :
![image](https://github.com/user-attachments/assets/3da0630b-9799-4f1d-8184-f33407414c48)

## Création d'un nouveau label
L’instructeur peut aussi créer un nouveau label :
![image](https://github.com/user-attachments/assets/46a4d95e-a55d-45bc-a8f2-0affb5ba6aaf)
Il retrouve alors la même zone d’édition (nom du label, couleur, visibilité - avec mise à jour automatique de l’aperçu) :
![image](https://github.com/user-attachments/assets/8ef5bc76-5b83-48f4-832a-23cabd0ab88c)
Il enregistre ensuite sa création et la liste de labels se met à jour :
![image](https://github.com/user-attachments/assets/1c7b270a-40e6-47d7-adf3-557207e90121)
![image](https://github.com/user-attachments/assets/3464fd11-076a-479c-bb5b-25e506f86605)

# Évolutions à venir sur l’écran Tableau-liste des dossiers
Les labels seront à terme également visibles dans le tableau-liste des dossiers, au sein d’une **colonne dédiée « Label »**, l’instructeur pourra également **ajouter des labels en masse** après avoir sélectionné plusieurs dossiers dans le tableau-liste :
![image](https://github.com/user-attachments/assets/4ef345fb-27db-4de4-a374-9614fe7d256f)
L’instructeur pourra également **filtrer** sa liste de dossiers à partir d’un (ou plusieurs) label(s) :
![image](https://github.com/user-attachments/assets/73962bd4-2321-4f0e-898f-9dff478a6d01)
![image](https://github.com/user-attachments/assets/fda77d0f-f919-4b98-a2db-cd0db2f6f021)

**Comment by colinux** [comment]
Je me dis que dans une évolution ultime, un instructeur pourrait "s'abonner" à un label pour avoir une notification lorsqu'un dossier se voit attribuer ou retirer ce label. (cas de la hiérarchie pour l'organisation personnelle du N+1). Je ne sais pas quelle forme ça prendrait , par exemple simplement faire apparaître sur la nouvelle page multi-démarches les dossiers de ce label.
A voir comment les instructeurs s'approprient les labels

**Comment by marleneklok** [comment]
# Personnalisation des labels par l'ADMINISTRATEUR
## Côté INSTRUCTEUR
L'instructeur dispose d'une **liste de labels par défaut**.
Dans le menu d'ajout de labels, on lui indique que s'il a besoin d'autres labels, il doit **contacter un des administrateurs** de la démarche :
![image](https://github.com/user-attachments/assets/0c9b0330-2f58-4289-9d4f-4bc02fbe6133)

En cliquant sur le lien "administrateurs de la démarche", il accède à la page **"Administrateurs de la démarche"** :
- Actuellement : page "Administrateurs" (https://www.demarches-simplifiees.fr/procedures/00000/administrateurs)
- Version cible : sous-rubrique "Administrateurs de la démarche" de la rubrique "Gestion de la démarche" (avec action directe "Contacter par email" pour chaque administrateur) :
![image](https://github.com/user-attachments/assets/5d8eb911-da57-46e3-9ba5-65f3157d1f5d)
## Côté ADMINISTRATEUR
On ajoute une tuile **"Labels instructeurs"**, avec des actions d'ajout / modification / suppression de labels, sur le même principe que l'écran de la tuile "Service".
