### ISSUE TITLE
ETQ instructeur je souhaite mieux comprendre le terme " démarrés"  depuis les stats 

### ISSUE THREAD

**Issue by CamilyaDellali** [demarches-simplifiees/demarches-simplifiees.fr#9806]
Les instructeurs ne savent pas ce qui signifie le nombre de dossiers  "démarrés" depuis les statistiques relatives à "l'avancée des dossiers". Le wording utilisé n'est pas clair, ils pensent qu'il s'agit du nombre de dossier en brouillon et qui seront potentiellement déposés cela a créé de la panique ( retour du Pole emploi services) Or, cela intègre également les dossiers déposés 

![image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/82160230/2dc747ca-0c9f-4fef-bde1-765128ababb0)

**Comment by lisa-durand** [comment]
Est-ce que "tous les dossiers" te semble un terme plus compréhensible @CamilyaDellali ?

![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/3709b252-cdbb-4062-914c-a85caa92c8f8)

**Comment by CamilyaDellali** [comment]
après avoir discuté avec @lisa-durand et @marleneklok , le terme **" tous (dont brouillon)"** sera affiché

**Comment by colinux** [comment]
(Pour info j'ai une branche quelque part qui revoit l'affichage des pages de stats pour être compatible thème sombre et mobile)
