### ISSUE TITLE
ETQ admin, je veux avoir comme balise "date de dernière mise à jour" car visible dans le tableau de bord mais pas en balise 

### ISSUE THREAD

**Issue by Bouchralazaar** [demarches-simplifiees/demarches-simplifiees.fr#9825]
Dispo pour plus d'infos 

on parle des balises mails et attestations

**Comment by emsnytech** [comment]
Je pense qu'avant de faire cela il faut poser la question pourquoi exporter le dossier pour le transmettre.
Il faudrait déroulé le cas d'usage
