### ISSUE TITLE
ETQ instructeur je souhaite pouvoir solliciter plusieurs experts à la fois en copiant leurs adresses mails 

### ISSUE THREAD

**Issue by CamilyaDellali** [demarches-simplifiees/demarches-simplifiees.fr#9838]
Cas d'usage : de plus en plus d'instructeurs sollicitent plusieurs dizaines experts par dossier. Or, malgré la liste prédéfinie par l'administrateur, cela reste chronophage de rechercher et de taper l'adresse mail de l'expert pour chaque dossier. Par exemple, la Caisse des dépôts a une liste de 400 experts et sollicite jusqu'à 100 experts par dossier. Ils ont 3 groupes d'experts, les instructeurs aimeraient alors avoir des groupes d'experts à solliciter ( il s'agit d'une démarche sans routage). Elles souhaiteraient **pouvoir copier une série d'adresses mails d'experts lorsqu'elles demandent un avis :**  

![image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/82160230/7323ffe3-5507-49ca-9c5a-46582aabf95b)

![image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/82160230/ed936ef1-da06-4392-9fed-d8e511f5c916)

Autre proposition : avoir des titres de section dans la liste déroulante pour catégoriser les groupes d'experts comme c'est le cas pour les menus déroulants liés ? 

Ticket support : https://secure.helpscout.net/conversation/2433960175/2046848?folderId=4539161

@E-L-T

**Comment by E-L-T** [comment]
@CamilyaDellali je suis partant. Par contre @LeSim a des réserves quant à l'impact pour les experts

**Comment by CamilyaDellali** [comment]
@E-L-T @LeSim oui pas de souci, on peut en discuter . Il y a aussi l'autre piste pour "soulager" et mieux s'u retrouver avec le fait d'avoir des "groupes" ou des "catégories"

**Comment by colinux** [comment]
Faudra gérer les cas où des emails collés ne sont pas dans la liste définie par l'admin, et n'inviter réellement que les emails "autorisés".
