### ISSUE TITLE
Supprimer ou modifier la mention "pour aller plus loin" du tableau de bord admin de la démarche 

### ISSUE THREAD

**Issue by CamilyaDellali** [demarches-simplifiees/demarches-simplifiees.fr#9844]
Constat suite à des points d'accompagnement : La mention "pour aller plus loin"  porte à confusion car les admins pensent que ce n'est pas "important" . Ils ne prennent pas alors connaissance des autres fonctionnalités et des options paramétrables . De plus, pour les démarches clonées, on peut retrouver des informations de l'ancien service dans les mails automatiques  notamment parce que le nouveau admin pense qu'il n'est pas nécessaire de vérifier au regard de cette mention " pour aller plus loin". 

![image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/82160230/dfd0ca9e-9316-4aaf-ae9c-57866868b695)

**Comment by CamilyaDellali** [comment]
A voir avec notre UX

**Comment by marleneklok** [comment]
Renommer par "Autres paramètres" ?
