### ISSUE TITLE
ETQ Administrateur je souhaite ajouter un tampon attestation de mon groupe instructeur - obtention d'une erreur 500

### ISSUE THREAD

**Issue by cmayran** [demarches-simplifiees/demarches-simplifiees.fr#9845]
**Décrivez le bug**
Lorsqu'ETQ administrateur, je souhaite configurer un tampon d'attestation d'un groupe instructeur. Après avoir ajouté l'image et cliqué sur `Ajouter le tampon` j'obtiens une page en erreur

**Reproduction**
Comment reproduire le problème :
1. Aller sur la page 'https://www.demarches-simplifiees.fr/admin/procedures/XXX/groupe_instructeurs/XXX. il faut au préalable avoir configuré une démarche avec du routage instructeur. L'administrateur de la démarche doit également être instructeur de ce groupe d'instructeur pour avoir accès au module `Tampon de l'attestation`
2. Cliquez sur 'Parcourir pour ajouter un fichier sélectionné' (format png de 6,0kB pour le test effectué)
3. cliquez sur "Ajouter le tampon"
4. Une erreur 'Une erreur est survenue --> message erreur 500 voir capture et affichage des infos

**Capture d'écran**
page :
![image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/121302145/092a3d38-2253-4224-9b57-9dda0523f947)

erreur :
![image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/121302145/0f66a6a1-3ebf-4442-8c61-dab2ba72de45)

**Appareil et navigateur utilisé**
 - Appareil : PC
 - Navigateur : Firefox 120.0.1 (64 bits)

**Comment by colinux** [comment]
Salut,

je crois que j'ai retrouvé ton erreur dans nos logs (c'est erreur au niveau de notre infra qui refuse de traiter ce fichier, pas directement lié au code DS). Tu pourrais m'envoyer ton PNG qui a provoqué l'erreur par un moyen ou un autre ?
Merci

**Comment by cmayran** [comment]
hello ! j'ai utilisé une image lambda dont je me sert pour mes test ds. 

c'est un logo de service. je te joins l'image dans le commentaire
![icon-96x96](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/121302145/c5ffdc13-a21d-4ac8-ac54-bff30242654b)
j'ai essayé avec une image non transparente également, même constat

**Comment by colinux** [comment]
Hello, le problème est corrigé. Ça venait de notre infra et des nouvelles policies d'ImageMagick (on va vous partager le fix aussi). Merci pour le retour !
