### ISSUE TITLE
Ne plus utiliser le modèle de mail avec le logo DS et Betagouv

### ISSUE THREAD

**Issue by lisa-durand** [demarches-simplifiees/demarches-simplifiees.fr#9883]
En travaillant sur le mail du transfert (https://github.com/demarches-simplifiees/demarches-simplifiees.fr/pull/9882), j'ai vu qu'il y avait un layout de mail avec le logo DS en header et le logo Betagouv en Footer. Pour un rendu plus pro, on pourrait réutiliser tjs le mm layout avec le logo avec la marianne et en footer " demarches-simplifiees.fr est un service fourni par la DINUM" 

![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/4d1fc53e-b7fa-45c9-9bbf-55698bed3b33)
![Image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/1151229a-3763-4c21-a40b-7da3d248534c)

**Comment by colinux** [comment]
Fermé par #10224
