### ISSUE TITLE
En tant qu'utilisateur, l'analyse antivirus reste bloquée sur l'état analyse antivirus en cours et l'utilisateur n'a pas accès à son dossier. 

### ISSUE THREAD

**Issue by JOP-Temesis** [demarches-simplifiees/demarches-simplifiees.fr#9902]
**Décrivez le bug**
Depuis sa boite mail, à l'élaboration d’un dossier sur [demarches-simplifiees.fr](http://demarches-simplifiees.fr/).
Le page de consultation du dossier reste sur "Analyse antivirus"

**Reproduction**
Comment reproduire le problème :
1. Depuis sa boite mail 
2. Cliquez sur le lien **Pour le consulter, merci de suivre ce lien : https://www.demarches-simplifiees.fr/targeted_user_links/xxxxxxxxx**
3. Une erreur *'analyse antivirus en cours'* ne change pas de status et ne permet pas de consulter son dossier

**Comportement attendu**
L'analyse antivirus ne devrait pas prendre autant de temps sans informer l'utilisateur  

**Capture d'écran**
![demarches-simplifiees](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/102220624/e08b20c3-9ef6-4dc2-9553-75e45cb570f5)

**Appareil et navigateur utilisé**
 - Appareil : Pc Windows 
 - Navigateur : Firefox et Chrome dernière version

**Comment by tchak** [comment]
Ce genre d'erreurs est généralement intermittent. Nous avons beaucoup amélioré notre infrastructure des queues ces six derniers mois, donc normalement il devrait y avoir beaucoup moins de ce genre de problèmes
