### ISSUE TITLE
ETQ instructeur, je veux que les pièces jointes soient tournées dans le bon sens

### ISSUE THREAD

**Issue by E-L-T** [demarches-simplifiees/demarches-simplifiees.fr#9911]
Une fois la galerie de pjs mise en place dans #9912 on souhaiterait détecter l'orientation des images (avec la gem Tesseract a priori) pour les remettre dans le bon sens automatiquement

**Comment by colinux** [comment]
Essai rapide rien qu'avec un petit modèle en local de 7B de paramètres ([dolphin-mistral 2.7](https://ollama.ai/library/dolphin-mistral)) pour voir ce que ça pourrait donner : 


## Système prompt : 
```
FROM dolphin-mistral
PARAMETER temperature 0.2
PARAMETER top_k 30
PARAMETER top_p 0.75
SYSTEM """
You are tasked with analyzing a document submitted by a user as part of an administrative procedure. Your role is to extract all relevant information from the document related to this context, to assist an administrative agent in verifying user-specific information. Focus on identifying and extracting dates from the document and specific details about the user, such as names, first names, address, and any other information that could be useful to the administrative agent. Format dates in ISO standard. Organize the information in a JSON-formatted response. Use snake case keys, and adhere to standardized naming conventions. The JSON response should be clear and categorized, with the most relevant attributes first, to facilitate the administrative agent's processing of the file.

The response MUST contain only information present in the document and UNDER NO CIRCUMSTANCES should it include deduced or invented information.
"""
```

## Résultat : 
![Capture-d’écran-2024-01-18-à-11-52-54](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/150279/051395f5-1ecf-43ae-bda7-d60f51906068)


Le même essai sur un modèle plus gros/adapté à la prod fournit des infos mieux structurées et détaillées (notion de co-titulaire…). On pourrait sans problème forcer l'output avec un nommage de clés déterminé pour faciliter leur utilisation
