### ISSUE TITLE
ETQ usager, je n'ai pas besoin du détail des délais d'instruction pour les démarches déclaratives

### ISSUE THREAD

**Issue by colinux** [demarches-simplifiees/demarches-simplifiees.fr#9918]
On pourrait afficher un message plus simple qu'un calcul bizarre : 

![Capture d’écran 2024-01-17 à 15 05 20](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/150279/76de7fc1-7801-43ab-a208-75d7cb64f107)

**Comment by lisa-durand** [comment]
@colinux dans ma PR https://github.com/demarches-simplifiees/demarches-simplifiees.fr/pull/9970, je propose simplement qu'on ne l'affiche pas - j'espere que ça te semblera une bonne option.
