### ISSUE TITLE
ETQ support, je voudrais pouvoir marquer une démarche comme "Modèle" afin qu'il soit facilement identifiable par les admins

### ISSUE THREAD

**Issue by kara22** [demarches-simplifiees/demarches-simplifiees.fr#9937]

**Comment by Bouchralazaar** [comment]
Super Kara !! ça va nous aider

**Comment by kara22** [comment]
- Ajouter un bolléen dans la démarche
- Permettre au support de cocher sur le bolléen dans le manager pour ajouter la démarche comme modèle
- Si la démarche est identifiée comme modèle, ajouter un badge dans les résultats de la page "toutes les démarches" pour identifier la démarche comme modèle

@Bouchralazaar
