### ISSUE TITLE
ETQ instructeur, je veux pouvoir filtrer sur les infos d'un bloc répétable

### ISSUE THREAD

**Issue by CamilyaDellali** [demarches-simplifiees/demarches-simplifiees.fr#9980]
Exemple de cas d'usage : un admin utilise le champ bloc répétable afin que les usagers puissent indiquer les informations en fonction d'un ordre de préférence. Afin de simplifier l'instruction des dossiers, les instructeurs aimeraient filtrer les dossiers en fonction de l'ordre de préférence indiqué dans les blocs répétable. 

Exemple de démarche :  88996

![image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/82160230/36419954-b850-4c17-b090-f776f0584853)

**Comment by E-L-T** [comment]
Besoin remonté ici aussi : https://mattermost.incubateur.net/betagouv/pl/d43btfzm1f8q5rzimm8ihzahiw
Besoin de filtrer sur les infos d'un bloc répétable, mais aussi de router et d'avoir le contenu dans les exports

**Comment by tchak** [comment]
done
