### ISSUE TITLE
En-tête CORS "Access-Control-Allow-Origin" manquante pour l'API GraphQL

### ISSUE THREAD

**Issue by hugoattal** [demarches-simplifiees/demarches-simplifiees.fr#9992]
**Décrivez le bug**
Hello, il semblerait que l'entête `Access-Control-Allow-Origin` est manquante pour l'API GraphQL.
Le problème est qu'on ne peut pas faire de requêtes API depuis un site web à cause des sécurités web par défaut.

**Reproduction**
Comment reproduire le problème :
Ouvrir un fichier HTML avec ceci :
```html
<script>
    fetch("https://www.demarches-simplifiees.fr/api/v2/graphql", {
    "credentials": "include",
    "headers": {
        "Content-Type": "application/json",
        "Authorization": "Bearer myToken"
    },
    "body": "{}",
    "method": "POST"
}).then(response => response.json())
</script>
```

Ouvrir la console du navigateur, onglet "Réseau".
On a une erreur `CORS Missing Allow Origin`
![image](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/4563971/0ba3484f-3ec1-4c7b-94e3-262536d31a14)

**Comportement attendu**
On devrait avoir une réponse du serveur. (Même si c'est une erreur parce que le jeton d'authentification est mauvais ou que la requête est invalide)

Vu que c'est une API publique et que l'authentification se fait avec un jeton, il me semble qu'il faut rajouter cet en-tête pour permettre l'utilisation de l'API dans un contexte de site web :
`Access-Control-Allow-Origin: *`

**Capture d'écran**
Si besoin, ajoutez une capture d'écran de votre problème. Cela nous aide à identifier plus rapidement le souci.

**Appareil et navigateur utilisé**
 - Appareil : PC
 - Navigateur : Firefox, Chrome

**Comment by hugoattal** [comment]
J'y connais absolument rien en Ruby, mais je suppose que le header devrait être ajouté quelque part par là ?

https://github.com/demarches-simplifiees/demarches-simplifiees.fr/blob/48644ae407658748bc5c162efc3b2e18d683328b/app/controllers/api/v2/graphql_controller.rb#L2-L6

Avec un truc dans ce style ? (J'avoue que je sais même si ça compile)

```ruby
render json: result, headers: { 'Access-Control-Allow-Origin' => '*' }
```

Merci d'avance en tout cas 🙂 !

**Comment by mfo** [comment]
Hello Hugo. Merci pour ton retour, malheureusement nous ne comptons pas supporter les CORS (on pourrait se retrouver avec des tokens exposé côté client... trop risqué niveau sécu).

Belle journée
